### ISSUE TITLE
passing java file name from command line is failing

### ISSUE THREAD

**Issue by vikramvi** [cucumber/cucumber-jvm#1043]
mvn clean verify -Dcucumber.options="src/test/java/com/Login_Stories.java"

is throwing error as below

Caused by: gherkin.lexer.LexingError: Lexing error on line 1: 'package com.cucumber;

%_FEATURE_END_%'. See http://wiki.github.com/cucumber/gherkin/lexingerror for more information.
	at gherkin.lexer.En.scan(En.java:872)
	at gherkin.lexer.I18nLexer.scan(I18nLexer.java:36)
	at gherkin.parser.Parser.parse(Parser.java:62)
	at cucumber.runtime.FeatureBuilder.parse(FeatureBuilder.java:131)
	at cucumber.runtime.model.CucumberFeature.loadFromFeaturePath(CucumberFeature.java:104)
	at cucumber.runtime.model.CucumberFeature.load(CucumberFeature.java:54)
	at cucumber.runtime.model.CucumberFeature.load(CucumberFeature.java:34)
	at cucumber.runtime.RuntimeOptions.cucumberFeatures(RuntimeOptions.java:235)
	at cucumber.api.junit.Cucumber.<init>(Cucumber.java:60)

But below works when I pass just feature file

mvn clean verify -Dcucumber.options="src/test/resources/LoginPage/login_stories.feature"

Please clarify if this is an issue 

Thanks,
Vikram

**Comment by aslakhellesoy** [comment]
You're asking Cucumber to run a Java source file. I'm not sure what you expected would happen?

**Comment by vikramvi** [comment]
@aslakhellesoy do you have a way to pass java file from command line ?

Without  asking cucumber to run .java , is there a way around ?

Also to answer your question , I would expect nice error message instead of above cryptic one.

**Comment by aslakhellesoy** [comment]
I don't understand what you're trying to do @vikramvi. What do you mean when you say "pass a java file"?

It's a bit like trying to open an word document in photoshop if you know what I mean.

**Comment by vikramvi** [comment]
`@RunWith(CucumberWithSerenity.class)

@CucumberOptions(features={"src/test/resources/LoginPage/password_positive.feature"}{../password_negative.feature}{..})
public class PreLogin_Stories {}`

I've multiple feature files linked in single java class and multiple java classes.

In this case I don't want to run all the java classes but one at a time from command line.

Please let me know if this is possible ?

**Comment by aslakhellesoy** [comment]
Oh I see. You want to tell Maven's JUnit plugin (surefire) to only run a particular JUnit test?

Try this: http://maven.apache.org/surefire/maven-surefire-plugin/examples/single-test.html
