### ISSUE TITLE
HtmlFormatter doesn't close Stream for embedded image.

### ISSUE THREAD

**Issue by christopherfrieler** [cucumber/cucumber-jvm#1108]
## Summary

It looks like the HtmlFormatter forgets to close the FileOutputStream of an image being embedded.

## Expected Behavior

The HtmlFormatter should close all streams and there should be no log-error about a stream not being closed.

## Current Behavior

Although my tests pass, I get the following exception:
```
A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                             java.lang.Throwable: Explicit termination method 'close' not called
                                                 at dalvik.system.CloseGuard.open(CloseGuard.java:180)
                                                 at java.io.FileOutputStream.<init>(FileOutputStream.java:222)
                                                 at java.io.FileOutputStream.<init>(FileOutputStream.java:169)
                                                 at cucumber.runtime.io.URLOutputStream.<init>(URLOutputStream.java:34)
                                                 at cucumber.runtime.io.URLOutputStream.<init>(URLOutputStream.java:24)
                                                 at cucumber.runtime.formatter.HTMLFormatter.reportFileOutputStream(HTMLFormatter.java:229)
                                                 at cucumber.runtime.formatter.HTMLFormatter.embedding(HTMLFormatter.java:157)
                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                 at cucumber.runtime.Utils$1.call(Utils.java:40)
                                                 at cucumber.runtime.Timeout.timeout(Timeout.java:16)
                                                 at cucumber.runtime.Utils.invoke(Utils.java:34)
                                                 at cucumber.runtime.RuntimeOptions$1.invoke(RuntimeOptions.java:294)
                                                 at java.lang.reflect.Proxy.invoke(Proxy.java:813)
                                                 at $Proxy6.embedding(Unknown Source)
                                                 at cucumber.runtime.ScenarioImpl.embed(ScenarioImpl.java:61)
                                                 ...
```

## Possible Solution

In HtmlFormatter there is a private method `writeBytesAndClose(byte[], OutputStream)`, which writes bytes, but does not close the stream as the method-name indicates. Closing the stream could possibly help.

## Context & Motivation

If not fixed, I'm scared of a memory-leak, when our test-suite grows.

## Your Environment

* Version used: cucumber-core:1.2.5
* Operating System and version: Windows 7
* I'm using cucumber to test an Android-app.

**Comment by mpkorstanje** [comment]
Would recommend:
- https://github.com/damianszczepanik/cucumber-reporting
- https://github.com/damianszczepanik/cucumber-sandwich
- https://github.com/jenkinsci/cucumber-reports-plugin

Uses the json output and works better overall.
