### ISSUE TITLE
Kotlin and Java8 lamda parsing results in ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by lunivore** [cucumber/cucumber-jvm#1123]
I'm running with a Cucumber JVM feature file, using Java8 and PicoContainer. Here's my feature:

    Feature: Full Journey

    Scenario: Can load a typical JIRA csv and calculate the distribution from it

    Given a typical JIRA export "/closed_only_JIRA.csv"
    When I import it into Montecarluni
    Then I should see the distribution
    """
    6, 15, 3, 14, 2, 5, 6, 8, 5, 10, 15, 4, 2, 1
    """
    When I copy it to the clipboard
    Then I should be able to paste it somewhere else

Running this step in Kotlin causes an error:

    import cucumber.api.java8.En

    class ClipboardSteps(val world : World) : En {
        init {
            When("^I copy it to the clipboard$", {
                // Errors even without any code here 
            })
        }
    }

While this Java class runs just fine:

    import cucumber.api.java8.En;

    public class JavaClipboardSteps implements En {

        public JavaClipboardSteps(World world) {
            When("^I copy it to the clipboard$", () -> {
                // Works just fine with code or without
            });
        }
    }

This Kotlin step also runs fine, so you can see this is pretty unpredictable:

    import cucumber.api.java8.En
    
    class FileImportSteps(val world: World) : En {
        init {
            // There's a Given here

            When("^I import it into Montecarluni$", {
                // There's some code here
            })
        }
    }

The Runner, for completion:

    import cucumber.api.CucumberOptions
    import cucumber.api.junit.Cucumber
    import org.junit.runner.RunWith

    @RunWith(Cucumber::class)
    @CucumberOptions(
        format = arrayOf("pretty"),
        glue = arrayOf("com.lunivore.montecarluni.glue"),
        features = arrayOf("."))
    class Runner {
    }

Stacktrace is:

    cucumber.runtime.CucumberException: java.lang.ArrayIndexOutOfBoundsException: 52

	at cucumber.runtime.java.JavaBackend.addStepDefinition(JavaBackend.java:166)
	at cucumber.api.java8.En.Then(En.java:280)
	at com.lunivore.montecarluni.glue.DistributionSteps.<init>(DistributionSteps.kt:8)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.injectors.AbstractInjector.newInstance(AbstractInjector.java:145)
	at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:342)
	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
	at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
	at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
	at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
	at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:678)
	at cucumber.runtime.java.picocontainer.PicoFactory.getInstance(PicoFactory.java:40)
	at cucumber.runtime.java.JavaBackend.buildWorld(JavaBackend.java:131)
	at cucumber.runtime.Runtime.buildBackendWorlds(Runtime.java:141)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:38)
	at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:102)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:95)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:38)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.api.junit.Cucumber.run(Cucumber.java:100)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:51)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
    
    Caused by: java.lang.ArrayIndexOutOfBoundsException: 52
	at jdk.internal.org.objectweb.asm.Type.getArgumentTypes(Type.java:358)
	at cucumber.runtime.java8.ConstantPoolTypeIntrospector.getGenericTypes(ConstantPoolTypeIntrospector.java:32)
	at cucumber.runtime.java.Java8StepDefinition.getParameterInfos(Java8StepDefinition.java:54)
	at cucumber.runtime.java.Java8StepDefinition.<init>(Java8StepDefinition.java:44)
	at cucumber.runtime.java.JavaBackend.addStepDefinition(JavaBackend.java:162)
	... 44 more

Other things you might want to look at:

[My Github code, with Kotlin step commented out](https://github.com/lunivore/montecarluni)

[Dan's response on Stackoverflow](http://stackoverflow.com/a/43981507/363592)

I am happy to act as tester on this one if you would like.

**Comment by mpkorstanje** [comment]
Very interesting. Can you try building [support-java-8-method-references](https://github.com/cucumber/cucumber-jvm/tree/feature/support-java-8-method-references) locally and add a dependency to `io.cucumber:cucumber-kotlin-java8:2.0.0-SNAPSHOT`? Note that the groupId has also changed.

This should solve the problem.

**Comment by kashano** [comment]
Hi, I had the same issue and I can verify this works, I was getting

```
1) Error injecting constructor, cucumber.runtime.CucumberException: java.lang.ArrayIndexOutOfBoundsException: 66
```

But after building the [support-java-8-method-references](https://github.com/cucumber/cucumber-jvm/tree/feature/support-java-8-method-references) branch and updating the dependencies, everything worked OK.

PS. I tried for a couple of days with a Gradle project but I was getting this error

```
Warning:<i><b>root project 'cm-service-it': Unable to build Kotlin project configuration</b>
Details: java.lang.reflect.InvocationTargetException: null
Caused by: org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration ':testCompileClasspath'.
Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve io.cucumber:cucumber-kotlin-java8:2.0.0-SNAPSHOT.
Required by:
    project :
Caused by: org.gradle.internal.resolve.ModuleVersionResolveException: Could not resolve io.cucumber:cucumber-kotlin-java8:2.0.0-SNAPSHOT.
Caused by: org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser.MetaDataParseException: Could not parse POM /Users/jorge.vargas/.m2/repository/io/cucumber/cucumber-kotlin-java8/2.0.0-SNAPSHOT/cucumber-kotlin-java8-2.0.0-SNAPSHOT.pom
Caused by: org.gradle.api.internal.artifacts.ivyservice.ivyresolve.parser.UnresolvedDependencyVersionException: Unable to resolve version for dependency 'io.cucumber:cucumber-java8:jar'</i>
```

So I got it working with maven.

**Comment by mpkorstanje** [comment]
Cheers!

PS: Owh yeah. Looks like using dependency management in a profile is a bad practice and gradle doesn't grok it. I have pushed a new branch that should fix this.

https://blog.gradle.org/maven-pom-profiles

**Comment by mpkorstanje** [comment]
Also for future reference. `cucumber-kotlin-java8` won't available as a dependency (for now). You can use `cucumber-java8` directly in Kotlin.
