### ISSUE TITLE
Cucumber Tests to be run in JMeter. Getting "No backends were found" exception

### ISSUE THREAD

**Issue by mathan91** [cucumber/cucumber-jvm#1144]
I have a piece of **Cucumber + JUNIT + Selenium WebDriver** code to be used in JMeter for load testing. 

Following is the piece of code, 

```
public class Runner extends ClassUtility {
	public ClassLoader load;
	public Logger log = Logger.getLogger(Runner.class.getName());
	// JUNIT requires at least one empty constructor. Hence I have added the below constructors.
	public Runner(String test) {
		this();
	}
	public Runner() {
		// TODO Auto-generated constructor stub
	}
	// Before Method to notify that the test case has started.
	@Before
	public void beforeMethod() throws Exception{
		System.out.println("Test case has started");
	}
	// Test method is defined with Cucumber Main run method. 
	// "-g" signifies glue code (package where the code is), "-t" signifies the tag.  The location of the feature file which defines the test scripts 
	
	@Test
	public void runTest() throws Throwable {			
		try {
			String[] getRequest = GetRequest.testValuesReturn();
			Main.run(new String[]{"-g", "com.sanity.step.definition","-t", "@New", "C:/Users/IBM_ADMIN/Documents/Automation/Performance Testing/PerformanceTesting/MyFeature.feature"}, ClassLoader.getSystemClassLoader());
			log.info("Print");
			System.out.println("Print");
		} catch (Exception e) {
			e.printStackTrace();
		}
	}
	// Post Test what the JUNIT test needs to do
	@After
	public void afterMethod() throws Exception {
		System.out.println("The script is done");
		log.info("The script is done");
	}
```

This is the feature file, 

```
@New
Scenario: To load test New Path scenario
When Start the performance Test
When Open the Inventory Page
When Click on environment link "OM402"
When It should go to Account "OR"
When Click on account "New"
When Click on Start Order and Navigate to Page "Product Configuration"
When Click on Click_Title "Mr"
When Click on name "firstName""Mathan"
When Click on name "lastName""Mohan"
When Click on cust address info radio "Phone"
When Enter Phone Number "4162163145"
When Click on Search Order
When Click on Additional Line "No"
When Click on Next Button1
When Click on Seamless Switch
When Transfer of services to bell "No"
When Click on Save Response on SSP "SaveResponse"
```

When I try to run from Eclipse, there's no issue, the execution is completed without any glitch. 

But when I export it as a jar and import it in JMeter while copying the following jars to the JMeter library. 
Cucumber Core 1.2.5
Cucumber html 0.2.3
Cucumber Java 1.2.5
Cucumber JVM deps 1.0.5
Cucumber picocontainer 1.2.5
gherkin 2.12.2

I'm getting the following exception while trying to run,

```
cucumber.runtime.CucumberException: No backends were found. Please make sure you have a
 have a backend module on your CLASSPATH.
        at cucumber.runtime.Runtime.<init>(Runtime.java:80)
        at cucumber.runtime.Runtime.<init>(Runtime.java:69)
        at cucumber.runtime.Runtime.<init>(Runtime.java:65)
        at cucumber.api.cli.Main.run(Main.java:35)
        at com.sanity.mainRunner.Runner.runTest(Runner.java:50)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl
java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcce
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.apache.jmeter.protocol.java.sampler.JUnitSampler$AnnotatedTestCa
e.runTest(JUnitSampler.java:593)
        at org.apache.jmeter.protocol.java.sampler.JUnitSampler$1.protect(JUnit
ampler.java:673)
        at junit.framework.TestResult.runProtected(TestResult.java:142)
        at org.apache.jmeter.protocol.java.sampler.JUnitSampler.sample(JUnitSam
ler.java:395)
        at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterTh
ead.java:465)
        at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.j
va:410)
        at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:241)
        at java.lang.Thread.run(Thread.java:745)
The script is done
```

It seems to be an issue with the latest jar. because I was not facing any issue with 1.1.2 Cucumber versions.  The only difference was that, I am using **run method instead of the main method**. The Cucumber 1.1.2 version contains the following jars - 

cobertura 2.1.1
Cucumber core 1.1.2
Cucumber Java 1.1.2
Cucumber JUNIT 1.1.2
Cucumber jvm deps 1.1.2
Cucumber Pico contains 1.1.2
Cucumber reporting 0.1.0
gherkin 2.12.1
JUNIT 4.11
mockito-all 2.0.2

Am I missing something with the two Cucumber versions? Thanks in advance for your answers!

**Comment by mpkorstanje** [comment]
Some changes have been made to the way resources are loaded yes, but nothing that should affect jmeter from what I can see. If I remember this correctly JMeter loads all jars at startup. Did you restart jmeter after adding the jars? 

You could also try to create  create your own instance of the JavaBackend. If you are unable to do so in JMeter then the JavaBackend is probably not on the class path when JMeter runs.

If so you should probably find a way to list all the jars in the classpath so you can ensure that the jars are indeed there. That narrows the problem down quite a bit.

**Comment by mpkorstanje** [comment]
And perhaps I should add. If you can create an instance of the JavaBackend in your unit test, instead of using `ClassLoader.getSystemClassLoader()`, please try using the class loader of the unit test instead.

**Comment by mathan91** [comment]
Thanks a lot @mpkorstanje . It's working fine. I will close the issue.
