### ISSUE TITLE
Why is it returning AmbiguousStepDefinitionsException

### ISSUE THREAD

**Issue by tfcardoso** [cucumber/cucumber-jvm#1169]
## Summary

I have the following different steps:

    @Then("^device (.*) taps on (.*) icon")
    @Then("^device (.*) taps on (.*) option")

And I'm trying to use:

    Then device Samsung S5 taps on more options icon

Witch is leading to:

    cucumber.runtime.AmbiguousStepDefinitionsException: ✽.Then device Samsung S5 taps on more options icon(C:/Users/my_user/Desktop/myGIT/automated/android/features/02_01contacts_manage.feature:12) matches more than one step definition:
    ^device (.*) taps on (.*) icon in GenericSteps.tapsIcon(String,String)
    ^device (.*) taps on (.*) option in GenericSteps.tapsOption(String,String)

    at cucumber.runtime.RuntimeGlue.stepDefinitionMatch(RuntimeGlue.java:71)
    at cucumber.runtime.Runtime.runStep(Runtime.java:267)
    at cucumber.runtime.model.StepContainer.runStep(StepContainer.java:44)
    at cucumber.runtime.model.StepContainer.runSteps(StepContainer.java:39)
    at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:44)
    at cucumber.runtime.model.CucumberScenarioOutline.run(CucumberScenarioOutline.java:46)
    at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
    at cucumber.runtime.Runtime.run(Runtime.java:122)
    at cucumber.api.cli.Main.run(Main.java:36)
    at cucumber.api.cli.Main.main(Main.java:18)

Why is cucumber considering this as AmbiguousStepDefinitionsException? I though by having the "icon" part in the end of the step, only steps that ended with icon would be considered for that step.

Any ideas on what I'm doing wrong here?

Thanks

**Comment by aslakhellesoy** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and contributions exclusively.

You need to add a `$` anchor at the end of both step definitions to remove the ambiguity.

**Comment by tfcardoso** [comment]
Wow, you'r right... It got lost in some copy-paste and I didn't spot it. thx
