### ISSUE TITLE
Getting "cucumber.runtime.CucumberException: java.net.MalformedURLException" since it doesn't take the prefix 'file://' for jars

### ISSUE THREAD

**Issue by mathan91** [cucumber/cucumber-jvm#1192]
When I try to run the cucumber jar from Weblogic server, I'm getting the following exception. 
```

public void runC(String env, String path, String user) throws Exception {
		
	try {	
	File featureFile = new File("C:/Users/IBM_ADMIN/Documents/Automation/Performance Testing/PerformanceTesting/MyFeature.feature");	
	String featureFileloc = featureFile.getAbsolutePath();	
	profile = DataBase.GetProfile(claUtilityEnv.environmentValue);
	profileNeeded = profile[0];
    returnCode = Main.run(
		new String[] {"-g", "com.sanity.step.definition",/*"-t", "@" + path,
			"C:/Users/IBM_ADMIN/Documents/Automation/Performance Testing/PerformanceTesting/MyFeature.feature"},
			SeparateClassloaderTestRunner.class.getClassLoader());
		}			
	catch (Exception e) {
		e.printStackTrace();
		if(returnCode == 1) {
			if (e.equals("ProfileException")) {
				String profileNeeded = profile[1];
				returnCode=Main.run(new String[] { "-g", "com.sanity.step.definition",
						"-t", "@" + claUtilityPath.pathValue,featureFile.replace("\\", "\\\\") },
					SeparateClassloaderTestRunner.class.getClassLoader());
				assertEquals(returnCode, 0);
			}
			else {
				System.out.println("There is an exception in the script");
			}
		}
	}
```
Getting the below exception, 

```
cucumber.runtime.CucumberException: java.net.MalformedURLException: unknown protocol: c
-> at cucumber.runtime.io.Helpers.jarFilePath(Helpers.java:39)
```

Seems that file:// prefix is missing when trying to fetch the jar files from windows machine. Have mentioned the issue in Gitter, @mpkorstanje has asked me to raise a ticket on the same.

**Comment by mpkorstanje** [comment]
@mathan91 could you include the full stacktrace and version of Cucumber? Right now can't reproduce this with just the unit tests and I don't have windows available to experiment on. You might have to do this yourself.

**Comment by mlvandijk** [comment]
I could have a look on a Windows machine, but not until after my holiday (Aug 17th earliest)...

**Comment by mathan91** [comment]
Please find the full stack trace,

```
cucumber.runtime.CucumberException: java.net.MalformedURLException: unknown protocol: c
	at cucumber.runtime.io.Helpers.jarFilePath(Helpers.java:39)
	at cucumber.runtime.io.ZipResourceIteratorFactory.createIterator(ZipResourceIteratorFactory.java:23)
	at cucumber.runtime.io.ZipThenFileResourceIteratorFactory.createIterator(ZipThenFileResourceIteratorFactory.java:21)
	at cucumber.runtime.io.DelegatingResourceIteratorFactory.createIterator(DelegatingResourceIteratorFactory.java:49)
	at cucumber.runtime.io.ClasspathResourceIterable.iterator(ClasspathResourceIterable.java:33)
	at cucumber.runtime.io.ResourceLoaderClassFinder.getDescendants(ResourceLoaderClassFinder.java:22)
	at cucumber.runtime.Reflections.instantiateSubclasses(Reflections.java:28)
	at cucumber.runtime.Runtime.loadBackends(Runtime.java:99)
	at cucumber.runtime.Runtime.<init>(Runtime.java:66)
	at cucumber.api.cli.Main.run(Main.java:35)
	at com.sanity.mainRunner.CucumberRunner.runC(CucumberRunner.java:77)
	at com.sanity.mainRunner.CucumberRunner.main(CucumberRunner.java:50)
	at com.sanity.servlet.SanityAutoPick.doPost(SanityAutoPick.java:52)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:227)
	at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:125)
	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:301)
	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:184)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3732)
	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3696)
	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321)
	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120)
	at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2273)
	at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2179)
	at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1490)
	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:256)
	at weblogic.work.ExecuteThread.run(ExecuteThread.java:221)
Caused by: java.net.MalformedURLException: unknown protocol: c
	at java.net.URL.<init>(URL.java:592)
	at java.net.URL.<init>(URL.java:482)
	at java.net.URL.<init>(URL.java:431)
	at cucumber.runtime.io.Helpers.jarFilePath(Helpers.java:36)
	... 27 more
```

**Comment by olleolleolle** [comment]
@mathan91 Perhaps 

```java
File featureFile = new File("C:/Users/IBM_ADMIN/Documents/Automation/Performance Testing/PerformanceTesting/MyFeature.feature")
```

must be something like

```java
File featureFile = new File("file://C:/Users/IBM_ADMIN/Documents/Automation/Performance Testing/PerformanceTesting/MyFeature.feature")
```

**Comment by mpkorstanje** [comment]
This problem does not appear to be related to the feature path. `cucumber.runtime.Runtime.loadBackends(Runtime.java:99)` indicates that this exception occurs while the Runtime is searching the class path for the JavaBackend.

So the problem appears to be that the class loader provided by `SeparateClassloaderTestRunner.class.getClassLoader()` does not return urls of the form `wsjar:file:c:\....` but apperently `wsjar:c:\`.

@mathan91 can your verify this by executing the statement below from `runC`?
```
Enumeration<URL> resources = SeparateClassloaderTestRunner.class.getClassLoader().getResources("classpath:com/sanity/step/definition");
while (resources.hasMoreElements()) {
    URL url = resources.nextElement();
    System.out.println(url)
}


```

**Comment by brasmusson** [comment]
I have checked on Windows that running:
```
java -cp <only jar files> cucumber.api.cli.Main <options>
```
does work, so there is no general problem of loading feature files or step definitions from jar files on Windows.

**Comment by mpkorstanje** [comment]
@brasmusson yup. Appears to be a class loader thing.

**Comment by mpkorstanje** [comment]
Closing this issue due to a lack of response. Please feel free to reopen when the requested information is available.
