### ISSUE TITLE
NullPointerException at Java8StepDefinition.isDefinedAt

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-jvm#1217]
## Summary

Test failure produces this stack trace. Not sure about the circumstances:

```
java.lang.NullPointerException
	at cucumber.runtime.java8.Java8StepDefinition.isDefinedAt(Java8StepDefinition.java:111)
	at cucumber.runtime.StepDefinitionMatch.removeFrameworkFramesAndAppendStepLocation(StepDefinitionMatch.java:153)
	at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:44)
	at cucumber.api.TestStep.executeStep(TestStep.java:78)
	at cucumber.api.TestStep.run(TestStep.java:61)
	at cucumber.api.TestCase.run(TestCase.java:28)
	at cucumber.runner.Runner.runPickle(Runner.java:80)
	at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:140)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:99)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:41)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:393)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

## Your Environment
* Version used: cucumber-jvm:2.0.0
* Operating System and version: Unix

**Comment by brasmusson** [comment]
Well, technically [`StackTraceElement.getFileName()`](http://docs.oracle.com/javase/7/docs/api/java/lang/StackTraceElement.html#getFileName()) can return `null`. It looks like if [`new Exception().getStackTrace()[3]`](https://github.com/cucumber/cucumber-jvm/blob/master/java8/src/main/java/cucumber/runtime/java8/Java8StepDefinition.java#L41) was to return a `StackTraceElement` without the file name information, this stack trace would appear. However, I have not been able to reproduce the problem.

**Comment by mpkorstanje** [comment]
I'll look into reproducing this.

**Comment by mpkorstanje** [comment]
I'm stumped.

1. I can reproduce this exception by running my existing test set on the build server but not my development machine.
2. A scenario must fail to produce the error, but not every failure generates the error. 
3. Repeated failure of the same scenario has an apparently random chance to produce this error.
4. Failing steps range in complexity from trivial to complex.

This all leads me to thinking that it might be specific jdk version of the buildserver that has an issue in combination with some jdk jit magic.

Despite being unable to properly diagnose this I think following the technical specification would the right solution so:  `return location.getFileName() != null && location.getFileName().equals(stackTraceElement.getFileName());`
