### ISSUE TITLE
Arity mismatch for datatable. Works for intellij and doesn't work for maven

### ISSUE THREAD

**Issue by seraphimaTW** [cucumber/cucumber-jvm#1243]
**Cucumber step:**

 When config API Client creates a **multiple** layers to **3** catalogs "**catalog_name**"
      | PAR1 | layer_name1 |
      | PAR2 | layer_name2 |
      | PAR3 | layer_name3 |

**Step definition:**
```
@When("^config API Client creates a (multiple|single) layers to (\\d+) catalogs \"([^\"]*)\"$")
public void configApiClientPushesMultipleConfig(String layers, int catalogNum, String catalogId, Map<LayerTypeEnum, String> layerTypesAndIds) throws Throwable {
....
}
```

This works perfectly when I run it through intellij and it fails in maven with this error:

_cucumber.runtime.CucumberException: Arity mismatch: Step Definition '...' with pattern [^config API Client creates a (multiple|single) layers to (\d+) catalogs "([^"]*)"$] is declared with 4 parameters. However, the gherkin step has 3 arguments [multiple, 3, catalog_name]. 
Step: When config API Client creates a multiple layers to 3 catalogs "catalog_name"_

I tried for cucumber jvm version 1.2.0, 1.2.4, 1.2.5

Could you please advice what I'm doing wrong and how I can make it workable for maven
Thanks!

**Comment by brasmusson** [comment]
Can you try Cucumber-JVM v2.0.1 (note the group id has changed to "io.cucumber") with maven? Cucumber-JVM v2.0.x uses a much newer Gherkin library compared to v1.2.x. Unfortunately the IntelliJ Cucumber-JVM plugin needs to be updated to work with Cucumber-JVM v2.0.x.

**Comment by seraphimaTW** [comment]
Thank you for your answer, @brasmusson 
I've updated cucumber-JVM to v2.0.1 and I'm still getting the same error...

**Comment by mlvandijk** [comment]
@seraphimaTW 
I'm trying to reproduce your error. I'm unable to reproduce when using the following step:
    @When("^config API Client creates a (multiple|single) layers to (\\d+) catalogs \"([^\"]*)\"$")
    public void configAPIClientCreatesAMultipleLayersToCatalogs(String s, int arg0, String arg1, Map<String, String> layers) throws Throwable {
        // Write code here that turns the phrase above into concrete actions
        throw new PendingException();
    }
However, when I use Map<Enum, String> instead of <String, String> I get the following error:
cucumber.runtime.CucumberException: Can't convert DataTable to Map<class java.lang.Enum,class java.lang.String>

Could you provide the code to LayerTypeEnum for further analysis?
(Alternatively: you could try to use a Map<String, String> in your StepDefinition, and get the LayerTypeEnum from that String inside the StepDef to see if that works)

*Side note:* When using the StepDef as provided, IntelliJ gives me an error "Illegal escape character in string literal. Use this instead:
    @When("^config API Client creates a (multiple|single) layers to (\\d+) catalogs \"([^\"]*)\"$")

**Comment by mlvandijk** [comment]
Full stack trace for the error if anybody's interested:
cucumber.runtime.CucumberException: Can't convert DataTable to Map<class java.lang.Enum,class java.lang.String>
        at cucumber.runtime.table.TableConverter.toMap(TableConverter.java:177)
        at cucumber.runtime.table.TableConverter.convert(TableConverter.java:71)
        at cucumber.runtime.StepDefinitionMatch.tableArgument(StepDefinitionMatch.java:106)
        at cucumber.runtime.StepDefinitionMatch.transformedArgs(StepDefinitionMatch.java:82)
        at cucumber.runtime.StepDefinitionMatch.runStep(StepDefinitionMatch.java:40)
        at cucumber.api.TestStep.executeStep(TestStep.java:102)
        at cucumber.api.TestStep.run(TestStep.java:83)
        at cucumber.api.TestCase.run(TestCase.java:58)
        at cucumber.runner.Runner.runPickle(Runner.java:80)
        at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:140)
        at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)
        at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
        at cucumber.api.junit.Cucumber.runChild(Cucumber.java:99)
        at cucumber.api.junit.Cucumber.runChild(Cucumber.java:41)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:108)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

**Comment by seraphimaTW** [comment]
Hi @brasmusson 
So, I've played around, trying to narrow it down.
I removed all other params and left only this datatable and I tried to use Map<String, String>.
And I've got the same issue. It works for intellij and it doesn't work for maven.
Here is the step:

    When some step with table data
    | val01 | val04 |
    | val02 | val05 |
    | val03 | val06 |

    @When("^some step with table data$")
    public void someStepWithTableData(Map<String, String> var) throws Throwable {
        System.out.println("WORKS" + var);
    }

I also tried 

    @When("^some step with table data$")
    public void someStepWithTableData(ArrayList<String, String> var) throws Throwable {
        System.out.println("WORKS" + var);
    }

And still no luck

**Comment by mlvandijk** [comment]
@seraphimaTW When you say "It works for intellij and it doesn't work for maven.", please can you let me know exactly how are you running the test from InteliJ and how are you running it from maven?

**Comment by aslakhellesoy** [comment]
@seraphimaTW can you prepare a [Minimal, Complete, and Verifiable example](https://stackoverflow.com/help/mcve) in a git repo please?

**Comment by seraphimaTW** [comment]
@brasmusson @mlvandijk @aslakhellesoy Thank you so much for participating, guys, I really appreciate it!
So, the issue is resolved for now.
In my project I'm using cucable maven plugin for parallel running. Updating this plugin version from 0.0.4 to 0.0.8 fixed the issue.
