### ISSUE TITLE
cucumber-java 2.0.1 IntelliJ Context Menu Run Scenario Class Not Found

### ISSUE THREAD

**Issue by drdamour** [cucumber/cucumber-jvm#1266]
I had a very simple .feature file and went to cucumber-java 2.0.1 and when i context run in intellij 2017.2.5 i get:

```
Exception in thread "main" java.lang.NoClassDefFoundError: gherkin/formatter/Formatter
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1007)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:801)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:699)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:622)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:580)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at cucumber.runtime.formatter.PluginFactory.loadClass(PluginFactory.java:170)
	at cucumber.runtime.formatter.PluginFactory.pluginClass(PluginFactory.java:162)
	at cucumber.runtime.formatter.PluginFactory.getPluginClass(PluginFactory.java:214)
	at cucumber.runtime.formatter.PluginFactory.isFormatterName(PluginFactory.java:192)
	at cucumber.runtime.RuntimeOptions$ParsedPluginData.addPluginName(RuntimeOptions.java:472)
	at cucumber.runtime.RuntimeOptions.parse(RuntimeOptions.java:156)
	at cucumber.runtime.RuntimeOptions.<init>(RuntimeOptions.java:114)
	at cucumber.runtime.RuntimeOptions.<init>(RuntimeOptions.java:107)
	at cucumber.runtime.RuntimeOptions.<init>(RuntimeOptions.java:99)
	at cucumber.api.cli.Main.run(Main.java:31)
	at cucumber.api.cli.Main.main(Main.java:18)
Caused by: java.lang.ClassNotFoundException: gherkin.formatter.Formatter
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 20 more

```

ran into this while trying to workaround #1267

**Comment by mpkorstanje** [comment]
Please follow https://youtrack.jetbrains.com/issue/IDEA-179579 for updates.
