### ISSUE TITLE
@Before and After method not working

### ISSUE THREAD

**Issue by Ganeshankarthik** [cucumber/cucumber-jvm#1351]
Hi ,

When i add @Before and @After method in cucumber Java it throws the below error.

java.lang.NoClassDefFoundError: gherkin/IGherkinDialectProvider
	at cucumber.runtime.RuntimeOptionsFactory.create(RuntimeOptionsFactory.java:28)
	at cucumber.api.junit.Cucumber.<init>(Cucumber.java:75)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createUnfilteredTest(JUnit4TestLoader.java:87)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:73)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:46)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:522)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:760)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:460)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:206)
Caused by: java.lang.ClassNotFoundException: gherkin.IGherkinDialectProvider
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 19 more

Below are my code snippet below.
![image](https://user-images.githubusercontent.com/24904232/39127059-8f4bdd86-4721-11e8-8c5c-032419833534.png)
![image](https://user-images.githubusercontent.com/24904232/39127089-a0d8a30e-4721-11e8-9ce0-ca9031fb6552.png)
![image](https://user-images.githubusercontent.com/24904232/39127104-ae1c8940-4721-11e8-98fa-68030cb7e39f.png)

I suspect the issue with the jar files but not sure. Please provide the solution at earliest. 
Thanks a lot for your help.

thanks,
Ganeshan

**Comment by mpkorstanje** [comment]
It looks like you're missing the `gherkin` dependency and it also looks like you're not using a dependency management system. You really should use one. Have a look at the tutorial for maven:

https://docs.cucumber.io/10-minute-tutorial/
