### ISSUE TITLE
cucumber.runtime.CucumberException: Couldn't find /cucumber/formatter/formatter.js. Is cucumber-html on your classpath?

### ISSUE THREAD

**Issue by NandamuriSrihari** [cucumber/cucumber-jvm#1374]
Summary

When I ran a test using Cucumber framework with Selenium Webdriver, after completion of test run default HTML report(index.html) is not generating as expected. Instead I am able to see an error message as below:

cucumber.runtime.CucumberException: Couldn't find /cucumber/formatter/formatter.js. Is cucumber-html on your classpath? Make sure you have the right version.
	at cucumber.runtime.formatter.HTMLFormatter.copyReportFiles(HTMLFormatter.java:187)
	at cucumber.runtime.formatter.HTMLFormatter.done(HTMLFormatter.java:108)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:40)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:34)
	at cucumber.runtime.RuntimeOptions$1.invoke(RuntimeOptions.java:294)
	at com.sun.proxy.$Proxy12.done(Unknown Source)
	at cucumber.runtime.junit.JUnitReporter.done(JUnitReporter.java:208)
Response Code : 200	at cucumber.api.junit.Cucumber.run(Cucumber.java:99)

Environment:
OS: Windows 10

Could someone help on this please?

**Comment by mlvandijk** [comment]
Hi @NandamuriSrihari, Please note that the issue tracker is used to report bugs or request features. 
If you need help, please use one of the [support options](https://cucumber.io/support).
I'm closing your issue as it is a question, but would be happy to help you on Slack.

**Comment by JMVM** [comment]
Which tracker ticket pls?

Just happened to me the same!

**cucumber.runtime.CucumberException: Couldn't find /cucumber/formatter/formatter.js. Is cucumber-html on your classpath? Make sure you have the right version.**
