### ISSUE TITLE
Data Tables with Delimiter are not correctly parsed as List<String>

### ISSUE THREAD

**Issue by mszalbach** [cucumber/cucumber-jvm#1385]
## Summary
Since Cucumber 3 List<String> with Delimiter like "a, b, c"  is not working anymore for me.
## Expected Behavior

Step is parsed and a List is used as parameter argument.

## Current Behavior
The step:
`Given a stack with the elements "Java, C++, PHP"`

With the following method:

```
@Given( "^a stack with the elements \"(.+)\"$" )
 public void stackInitWithList( List<String> elements )
```

seems to be parsed as string instead of a List.

When using a DataTable Syntax it is correctly parsed as List<String>.

This Exception is thrown:

`cucumber.runtime.CucumberException: Failed to invoke StackStepDef.stackInitWithList(String>) in file:/home/ms/macd/workspace/BDD/cucumber/target/test-classes/, caused by java.lang.IllegalArgumentException: argument type mismatch

	at cucumber.runtime.Utils$1.call(Utils.java:29)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:20)
	at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:48)
	at cucumber.runtime.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:50)
	at cucumber.runner.TestStep.executeStep(TestStep.java:55)
	at cucumber.runner.TestStep.run(TestStep.java:42)
	at cucumber.runner.PickleStepTestStep.run(PickleStepTestStep.java:53)
	at cucumber.runner.TestCase.run(TestCase.java:47)
	at cucumber.runner.Runner.runPickle(Runner.java:44)
	at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:140)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:98)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:55)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:107)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.IllegalArgumentException: argument type mismatch
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:26)
	... 33 more
`

## Your Environment

I have an example project showing the problem at https://github.com/mszalbach/BDD/tree/cucumber3.0
this can be executed via `./mvnw clean package -pl cucumber`. The master branch shows how this worked with Cucumber 2.4.

**Comment by mpkorstanje** [comment]
Cucumber 3.0 removed XStream and replaced it with Cucumber expressions.  You'll have to use a cucumber expression and add an extra step definition.

Make sure the following is anywhere on your glue path:

```java
public class TypeRegistryConfiguration implements TypeRegistryConfigurer {

    @Override
    public void configureTypeRegistry(TypeRegistry typeRegistry) {
        typeRegistry.defineParameterType(new ParameterType<>(
            "strings",
            singletonList("\"([^\"\\\\]*(\\\\.[^\"\\\\]*)*)\"|'([^'\\\\]*(\\\\.[^'\\\\]*)*)'"),
            new TypeReference<List<String>>() {}.getType(),
            (CaptureGroupTransformer<List<String>>) s ->
                asList(s[0]
                    .replaceAll("\\\\\"", "\"")
                    .replaceAll("\\\\'", "'")
                    .split(",")),
            false,
            false)
        );

    }

    @Override
    public Locale locale() {
        return ENGLISH;
    }
}
```

Then you can use this expressions to capture your list:

```java
Given(" a stack with the elements {strings}", (List<String> what) -> System.out.println(what));
```

**Comment by aslakhellesoy** [comment]
Hopefully @mpkorstanje’s suggestion works for you @mazalbach.

I’m reopening this issue because I think we should improve the error message.

What do you think about adding a default `{stringlist}` parameter type @mpkorstanje?

**Comment by mpkorstanje** [comment]
The reason this question pops up is because it is one of those auto-magical conversions that XStream supported. As far as XStream was concerned  `Given a stack with the elements "Java, C++, PHP"` was identical to:

```gherkin
Given a stack with the elements
 | Java |
 | C++  |
 | PHP  |
```

So unless this question also pops up for Js and Ruby I don't think this single example is a convincing use case.

I also think this is a particularly bad way to do lists. In natural language lists are not closed by quotes. Most people would write `Given a stack with the elements Java, C++, PHP`.  This however means that lists can only be captured by  `.*`, must occur at the end of a step definition and step definitions using a list must be somewhat unique. This would make a a really bad default.

**Comment by aslakhellesoy** [comment]
Good points. At the very least we should provide a better error message that points users in the right direction. `java.lang.IllegalArgumentException` is from the bellows of Java :-)

**Comment by mpkorstanje** [comment]
Definitely. It all runs through Util.invoke right now which will make it hard to get at the right info.  Lets move this to #1386.

**Comment by mszalbach** [comment]
One problem is that the documentation is telling me this should work:
https://docs.cucumber.io/cucumber/api/#data-tables

So even when I copy the step and the method from the documentation (which did not use quotes around the list elements) it is not working.

So I agree a  better error message would help but also the docu needs to be adjusted to show hot this should be done.
