### ISSUE TITLE
Incompatible class change error

### ISSUE THREAD

**Issue by Larry19b** [cucumber/cucumber-jvm#1392]
## Summary

Tried to run a test after upgrading from Cucumber 2.1.0 to 3.0.2 

## Expected Behavior

Test runs successfully

## Current Behavior

The following exception is thrown:
```
Exception in thread "main" java.lang.IncompatibleClassChangeError: Found interface cucumber.api.TestCase, but class was expected
	at org.jetbrains.plugins.cucumber.java.run.CucumberJvm2SMFormatter.handleTestCaseStarted(CucumberJvm2SMFormatter.java:80)
	at org.jetbrains.plugins.cucumber.java.run.CucumberJvm2SMFormatter.access$000(CucumberJvm2SMFormatter.java:17)
	at org.jetbrains.plugins.cucumber.java.run.CucumberJvm2SMFormatter$1.receive(CucumberJvm2SMFormatter.java:32)
	at org.jetbrains.plugins.cucumber.java.run.CucumberJvm2SMFormatter$1.receive(CucumberJvm2SMFormatter.java:30)
	at cucumber.runner.EventBus.send(EventBus.java:28)
	at cucumber.runner.TestCase.run(TestCase.java:37)
	at cucumber.runner.Runner.runPickle(Runner.java:44)
	at cucumber.runtime.Runtime.runFeature(Runtime.java:120)
	at cucumber.runtime.Runtime.run(Runtime.java:106)
	at cucumber.api.cli.Main.run(Main.java:35)
	at cucumber.api.cli.Main.main(Main.java:18)
```
## Possible causes

Here are some of the versions of the dependencies for the project. Maybe related?
```
        <spring.version>4.3.7.RELEASE</spring.version>
        <cucumber.version>3.0.2</cucumber.version>
        <junit.version>4.12</junit.version>
        <selenium.version>3.7.1</selenium.version>
```

## Environment

Mac OS X
IntelliJIDEA

**Comment by mlvandijk** [comment]
Could you please provide the code you are running and how you are running it, so i cam try tp reproduce? Thanks!

**Comment by Larry19b** [comment]
Apologies for not adding this earlier. I'm using a feature file that contains scenarios in gherkin. The scenario steps are linked to step definitions. All written in java using cucumber. The tests were all working fine when I was on Cucumber 2.1.0. However, when I upgrade to Cucumber 3.0.2, I got the error message mentioned above. I think it may be related to multiple choices of the same dependency or an interface becoming a class or vice versa. I have included a more expanded version of my pom file:

```
   <name>cucumber-jvm-maven</name>
    <url>http://maven.apache.org</url>
    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>1.16.6</version>
            <scope>compile</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-java8</artifactId>
            <version>${cucumber.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-junit</artifactId>
            <version>${cucumber.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-spring</artifactId>
            <version>${cucumber.version}</version>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>commons-logging</groupId>
                    <artifactId>commons-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>javax.inject</groupId>
            <artifactId>javax.inject</artifactId>
            <version>1</version>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-context</artifactId>
            <version>${spring.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>commons-logging</groupId>
                    <artifactId>commons-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-core</artifactId>
            <version>${spring.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>commons-logging</groupId>
                    <artifactId>commons-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-beans</artifactId>
            <version>${spring.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>commons-logging</groupId>
                    <artifactId>commons-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-test</artifactId>
            <version>${spring.version}</version>
            <exclusions>
                <exclusion>
                    <groupId>commons-logging</groupId>
                    <artifactId>commons-logging</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework</groupId>
            <artifactId>spring-tx</artifactId>
            <version>${spring.version}</version>
        </dependency>
        <dependency>
            <groupId>ch.qos.logback</groupId>
            <artifactId>logback-classic</artifactId>
            <version>1.1.2</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-api</artifactId>
            <version>1.7.22</version>
        </dependency>
        <dependency>
            <groupId>org.codehaus.janino</groupId>
            <artifactId>janino</artifactId>
            <version>2.6.1</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>${junit.version}</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-java</artifactId>
            <version>${selenium.version}</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-chrome-driver</artifactId>
            <version>${selenium.version}</version>
        </dependency>
        <dependency>
            <groupId>org.seleniumhq.selenium</groupId>
            <artifactId>selenium-remote-driver</artifactId>
            <version>${selenium.version}</version>
        </dependency>
............
```

**Comment by mpkorstanje** [comment]
This is caused by IDEA's CucumberJvm2SMFormatter. It being the formatter for Cucumber2, runs into a breaking change in Cucumber 3.

![image](https://user-images.githubusercontent.com/6946919/41260605-5e5266c2-6dd8-11e8-93b3-19bdabcd5061.png)

If you remove  `--plugin org.jetbrains.plugins.cucumber.java.run.CucumberJvm2SMFormatter` from the run configuration it will work again. You'll have to do this until InteliJ fixes this.

**Comment by tunovic** [comment]
Please vote https://youtrack.jetbrains.com/issue/IDEA-192612

**Comment by RajaRaviTeja** [comment]
When I have updated cucumber plugin from V1.2.4[info.cukes]  to V.4.2.2[io.cucumber]  With the below code, i am getting error, The import cucumber.api.java.en.Given(Or When/Then) cannot be resolved
POM.XML
                <dependency>
                    <groupId>io.cucumber</groupId>
                    <artifactId>cucumber-core</artifactId>
                    <version>4.2.2</version>
                </dependency>

                <dependency>
                <groupId>io.cucumber</groupId>
                <artifactId>cucumber-java</artifactId>
                <version>4.2.2</version>
                </dependency>
                
                <dependency>
                    <groupId>io.cucumber</groupId>
                    <artifactId>cucumber-junit</artifactId>
                    <version>4.2.2</version>
                    <scope>test</scope>
                </dependency>
                
                <dependency>
                    <groupId>io.cucumber</groupId>
                    <artifactId>cucumber-jvm-deps</artifactId>
                    <version>1.0.6</version>
                    <scope>provided</scope>
                </dependency>
                
                <dependency>
                    <groupId>io.cucumber</groupId>
                    <artifactId>gherkin</artifactId>
                    <version>6.0.14</version>
                </dependency>
                
                <dependency>
                    <groupId>org.mockito</groupId>
                    <artifactId>mockito-all</artifactId>
                    <version>1.10.19</version>
                    <scope>test</scope>
                </dependency>
                                
                <dependency>
                    <groupId>io.cucumber</groupId>
                    <artifactId>cucumber-testng</artifactId>
                    <version>2.0.0</version>
                </dependency>
                
                <dependency>
                    <groupId>io.cucumber</groupId>
                    <artifactId>cucumber-picocontainer</artifactId>
                    <version>2.1.0</version>
                    <scope>test</scope>
                </dependency>


RunFile from where execution is starting
@RunWith(Cucumber.class)
@CucumberOptions(features = "classpath:features/functional/",
				     glue = {"com.jacksparrow.automation.steps_definitions.functional" },
					 tags = { "@guest_search_in_progress" },
				   plugin = { "pretty","json:target/cucumber-json/cucumber.json",
							  "junit:target/cucumber-reports/Cucumber.xml", "html:target/cucumber-reports"},
				   strict = false,
				   dryRun = false,
			   monochrome = true)

public class FunctionalRunCuke {
} 



Please suggest, what is the mistake

**Comment by mlvandijk** [comment]
@RajaRaviTeja Please don't comment on closed issues. If you want help using Cucumber, please try one of the [support options](https://docs.cucumber.io/community/get-in-touch/).

**Comment by mlvandijk** [comment]
@RajaRaviTeja But to give a hint: Note that you are using both Junit and TestNG dependencies, and the testng dependency is a different version.
