### ISSUE TITLE
java.lang.IllegalArgumentException: Not a file or directory with cucumber 4.0.0

### ISSUE THREAD

**Issue by upanshu-yadav** [cucumber/cucumber-jvm#1472]
## Summary

I am trying to use cucumber 4.0.0 with android instrumented tests but  everytime I get error : java.lang.IllegalArgumentException: Not a file or directory: /src/androidTest/resources.

Initially I was using older version 3.0.2 but with that version I was getting "**No backends were found**" exception so in order to get rid of that I switched to the latest version but now I am stuck with this.

I have tried all sorts of folder combinations but none of them has worked so far. I am using android studio to create an apk project to be executed on an android hardware(OS : Jellybean)

My project set up is as below
```
|-src
  |-androidTest
    |-java
      |-com
        |-steps
          |-Implement
              -RunCucumberTest
              -Stepdefs
    |- resources
          -MyFeature.feature
```
here's what is in RunCucumberTest.java:
```java
@RunWith(Cucumber.class)
@CucumberOptions(plugin = {"pretty"},
                features = "src/androidTest/resources/",
                glue = "com.steps.Implement"
                )
public class RunCucumberTest {
}
```
This is the error i am getting:
java.lang.IllegalArgumentException: Not a file or directory: /src/androidTest/resources
at cucumber.runtime.io.FileResourceIterator$FileIterator.<init>(FileResourceIterator.java:63)
at cucumber.runtime.io.FileResourceIterator.<init>(FileResourceIterator.java:28)
at cucumber.runtime.io.FileResourceIterator.createFileResourceIterator(FileResourceIterator.java:14)
at cucumber.runtime.io.FileResourceIterable.iterator(FileResourceIterable.java:19)
at cucumber.runtime.model.FeatureLoader.loadFromFeaturePath(FeatureLoader.java:112)
at cucumber.runtime.model.FeatureLoader.load(FeatureLoader.java:48)
at cucumber.runtime.model.FeatureLoader.load(FeatureLoader.java:30)
at cucumber.runtime.FeaturePathFeatureSupplier.get(FeaturePathFeatureSupplier.java:22)
at cucumber.api.junit.Cucumber.<init>(Cucumber.java:90)
at java.lang.reflect.Constructor.constructNative(Native Method)
at java.lang.reflect.Constructor.newInstance(Constructor.java:417)
at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
at android.support.test.internal.runner.junit4.AndroidAnnotatedBuilder.runnerForClass(AndroidAnnotatedBuilder.java:63)
at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
at android.support.test.internal.runner.AndroidRunnerBuilder.runnerForClass(AndroidRunnerBuilder.java:153)
at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
at android.support.test.internal.runner.TestLoader.doCreateRunner(TestLoader.java:73)
at android.support.test.internal.runner.TestLoader.getRunnersFor(TestLoader.java:104)
at android.support.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:789)
at android.support.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:539)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:382)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
## Current Behavior

~~~
~~~

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: cucumber-java:4.0.0 , cucumber-junit:4.0.0 and cucumber-core:4.0.0
* Operating System and version: ubuntu 14.04 LTS
* Link to your project:

**Comment by mpkorstanje** [comment]
To the best of my somewhat knowledge you'll have to use an instrumentation test as provided by cucumber-android.

https://github.com/cucumber/cucumber-android

I don't know its latest release.
