### ISSUE TITLE
Issues when migrating to Cucumber 3.x.x/4.x.x from cucumber 2.x.x

### ISSUE THREAD

**Issue by cliviu** [cucumber/cucumber-jvm#1478]
## Summary

In cucumber-jvm 2.x.x, I had a step defined like this: 

```java
    @Then("^his country risk factor should be (.*)$")
    public void his_country_risk_factor_should_be(float rating) {
    } 
```
   
When running the tests with Cucumber 3.x.x , I got this error 
```
cucumber.runtime.CucumberException: Failed to invoke acceptancetests.reporting_controls.StepDefinitions.his_country_risk_factor_should_be(float) in ..., caused by java.lang.IllegalArgumentException: argument type mismatch
        at cucumber.runtime.Utils$1.call(Utils.java:29)
        at cucumber.runtime.Timeout.timeout(Timeout.java:16)
        at cucumber.runtime.Utils.invoke(Utils.java:20)
        at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:48)
        at cucumber.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:50)
        at cucumber.runner.TestStep.executeStep(TestStep.java:63)
        at cucumber.runner.TestStep.run(TestStep.java:49)
        at cucumber.runner.PickleStepTestStep.run(PickleStepTestStep.java:43)
        at cucumber.runner.TestCase.run(TestCase.java:44)
        at cucumber.runner.Runner.runPickle(Runner.java:40)
        at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:146)
        at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)
        at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
```

## Expected Behavior

  - existing cucumber-jvm tests will run with no change when upgrading to cucumber-jvm 3.x.x/4.x.x

## Current Behavior

  - exception thrown  when running the old tests with the new cucumber implementation

## Possible Solution

   - the only solution that I have found is to modify the step definition like this :
  
  ```java
 @Then("his country risk factor should be {float}")
    public void his_country_risk_factor_should_be(float rating) {
    } 

```
## Context & Motivation

   The problem is that upgrading to newer cucumber version breaks the existing tests. For some projects, updating a large number of tests can  be a real problem.

**Comment by mpkorstanje** [comment]
Comes to mind that cucumber expressions currently transforms a list of capture groups to objects.

For most cases this is a single string so for all the basic types cucumber expressions could also use the bare bones object mapper with String --> Object, and for multiple String[] -> Object. Assuming there is no expression defined ofc.

This would avoid allot of annoying inconsistencies and would let us extract the locale from the parameter type registery.

**Comment by mpkorstanje** [comment]
And with that in mind an anonymous cucumber expression parameter `{}` that translates to `(.*)` that only uses the type hint would be good too.

**Comment by cliviu** [comment]
Thank you very much for your explanations ! Please let me know in this thread if there is any chance of supporting this backward compatibility in one of the next versions. As I said, there are some projects outthere which are having troubles upgrading a large number of tests. Thanks !

**Comment by mlvandijk** [comment]
Related: https://github.com/cucumber/docs.cucumber.io/issues/142

**Comment by mpkorstanje** [comment]
4.2.0 has been released. Release notes can be found here:

https://github.com/cucumber/website/pull/317
