### ISSUE TITLE
cucumber.runtime.formatter.MissingStepDefinitionError when multiDexEnabled is set to true

### ISSUE THREAD

**Issue by upanshu-yadav** [cucumber/cucumber-jvm#1483]
## Summary
I am using cucumber 4.0.0 with android instrumented tests and it worked fine till now but when I set 
multiDexEnabled to true in my build.gradle I start getting below run time error. I have only enable multidex to true and haven't added other dependencies.

cucumber.runtime.formatter.MissingStepDefinitionError:

@Then("AC :I take another screen shot")
public void ac_I_take_another_screen_shot() {
// Write code here that turns the phrase above into concrete actions
throw new PendingException();
}

at cucumber.runtime.formatter.AndroidInstrumentationReporter.finishTestCase(AndroidInstrumentationReporter.java:213)
at cucumber.runtime.formatter.AndroidInstrumentationReporter$4.receive(AndroidInstrumentationReporter.java:138)
at cucumber.runtime.formatter.AndroidInstrumentationReporter$4.receive(AndroidInstrumentationReporter.java:135)
at cucumber.runner.EventBus.send(EventBus.java:28)
at cucumber.runner.TestCase.run(TestCase.java:58)
at cucumber.runner.Runner.runPickle(Runner.java:44)
at cucumber.runtime.android.CucumberExecutor.execute(CucumberExecutor.java:128)
at cucumber.api.android.CucumberInstrumentationCore.start(CucumberInstrumentationCore.java:88)
at com.steps.Implement.RunCucumberTest.onStart(RunCucumberTest.java:43)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)

My project set up is as below

```
|-src
  |-androidTest
    |-assets
       |-features
    |-java
      |-com
        |-steps
          |-Implement
              -RunCucumberTest
              -Stepdefs
```
here's what is in RunCucumberTest.java:
```java
@CucumberOptions(
                features = "features",
                )
public class RunCucumberTest  extends MonitoringInstrumentation {
}
```

## Current Behavior

~~~
~~~

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:cucumber-java:4.0.0 , cucumber-junit:4.0.0 and cucumber-core:4.0.0
* Operating System and version:ubuntu 14.04 LTS
* Link to your project:

**Comment by mpkorstanje** [comment]
You may have more luck asking in the Android repo.
https://github.com/cucumber/cucumber-android/issues

**Comment by mpkorstanje** [comment]
https://github.com/cucumber/cucumber-android/issues/13
