### ISSUE TITLE
IllegalStateException thrown when parallel running with Guice + @ScenarioScoped annotation

### ISSUE THREAD

**Issue by james-bjss** [cucumber/cucumber-jvm#1485]
## Summary

When using the new parallel feature of cucumber 4 with cucumber-guice and the JUnit runner an ```IllegalStateException``` is thrown. The error was observed when Step classes were annotated with ```@ScenarioScoped```

## Expected Behavior

Scopes should be separate across threads.

## Current Behavior

The following Exception is thrown:
```Feature: Applicant does not provide a day in Date Of Birth fieldjava.lang.IllegalStateException: A scoping block is already in progress
        at cucumber.runtime.java.guice.impl.SequentialScenarioScope.checkState(SequentialScenarioScope.java:64)
        at cucumber.runtime.java.guice.impl.SequentialScenarioScope.enterScope(SequentialScenarioScope.java:52)
        at cucumber.runtime.java.guice.impl.GuiceFactory.start(GuiceFactory.java:34)
        at cucumber.runtime.java.JavaBackend.buildWorld(JavaBackend.java:114)
        at cucumber.runner.Runner.buildBackendWorlds(Runner.java:120)
        at cucumber.runner.Runner.runPickle(Runner.java:38)
        at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:146)
        at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)
        at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
        at cucumber.api.junit.Cucumber.runChild(Cucumber.java:124)
        at cucumber.api.junit.Cucumber.runChild(Cucumber.java:65)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:393)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

## Possible Solution

See: https://github.com/cucumber/cucumber-jvm/pull/1486

## Workaround
When using a custom injector create a new Moducle and Scope instance:

```java
public class YourInjectorSource implements InjectorSource {
    @Override
    public Injector getInjector() {
        return Guice.createInjector(Stage.PRODUCTION, new ScenarioModule(new SequentialScenarioScope()), new YourModule());
    }
}
```

## Steps to Reproduce (for bugs)

1. Setup a Cucumber + Guice project with Scenario Scoped Objects + Steps
2. Run multiple features with the Surefire paralleled settings enabled

## Context & Motivation
Prevents our team from using the new parallel features added in Cucumber 4.x

## Your Environment

Windows 10, Cucumber 4.0.1, Maven Surefire 2.20, Junit Runner

**Comment by james-bjss** [comment]
Have created a PR for this with a potential fix - 
https://github.com/cucumber/cucumber-jvm/pull/1486/commits/82a2e214feb4b777c2f9a0d05ad60f065df84f2c

Please let me know if you think there is a better solution.
