### ISSUE TITLE
DocString stops working when using default JacksonTableTransformer

### ISSUE THREAD

**Issue by aniruddha125** [cucumber/cucumber-jvm#1490]
## Summary

DocString stops working when using default JacksonTableTransformer

## Expected Behavior
Expected that DocString should work when using default JacksonTableTransformer as mentioned [here](https://cucumber.io/blog/2018/09/24/announcing-cucumber-jvm-4-0-0)

## Current Behavior

All the steps with DocString throws exception listed below when I start using the default JacksonTableTransformer as explained [here](https://cucumber.io/blog/2018/09/24/announcing-cucumber-jvm-4-0-0). This works when I don't use the default JacksonTableTransformer.

Cucumber step :- 

Then Assert XML Response

      """

      Some Value

      """
Exception stack trace :- 

```
cucumber.runtime.CucumberException: Could not convert arguments for step [^Assert XML Response$] defined at '*.assertXMLResponse(String) in file:**/target/classes/'.

 

The details are in the stacktrace below. 

 at cucumber.runner.PickleStepDefinitionMatch.couldNotConvertArguments(PickleStepDefinitionMatch.java:69) 

 at cucumber.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:46) 

 at cucumber.runner.TestStep.executeStep(TestStep.java:63) 

 at cucumber.runner.TestStep.run(TestStep.java:49) 

 at cucumber.runner.PickleStepTestStep.run(PickleStepTestStep.java:43) 

 at cucumber.runner.TestCase.run(TestCase.java:44) 

 at cucumber.runner.Runner.runPickle(Runner.java:40) 

 at cucumber.api.testng.TestNGCucumberRunner.runScenario(TestNGCucumberRunner.java:68) 

 at cucumber.api.testng.AbstractTestNGCucumberTests.runScenario(AbstractTestNGCucumberTests.java:22) 

 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 

 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) 

 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 

 at java.lang.reflect.Method.invoke(Method.java:606) 

 at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86) 

 at org.testng.internal.Invoker.invokeMethod(Invoker.java:643) 

 at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820) 

 at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128) 

 at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129) 

 at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112) 

 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) 

 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) 

 at java.lang.Thread.run(Thread.java:745) 

Caused by: io.cucumber.datatable.CucumberDataTableException: Can't convert DataTable to java.lang.String. The table contained more then one item: [] 

 at io.cucumber.datatable.CucumberDataTableException.cantConvertTo(CucumberDataTableException.java:19) 

 at io.cucumber.datatable.DataTableTypeRegistryTableConverter.toSingleton(DataTableTypeRegistryTableConverter.java:113) 

 at io.cucumber.datatable.DataTableTypeRegistryTableConverter.convert(DataTableTypeRegistryTableConverter.java:75) 

 at io.cucumber.datatable.DataTable.convert(DataTable.java:362) 

 at io.cucumber.stepexpression.StepExpressionFactory$4.transform(StepExpressionFactory.java:86) 

 at io.cucumber.stepexpression.DocStringArgument.getValue(DocStringArgument.java:15) 

 at cucumber.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:41) 

 ... 20 more
```
## Steps to Reproduce (for bugs)

Run any cucumber gherkin step with DocString when using default JacksonTableTransformer.

## Context & Motivation

I am currently moving from an older version of Cucumber-jvm to the new Cucumber-jvm v 4. This problem is blocking me  from the move as our tests have a lot of dependencies on both data tables and DocStings.
## Your Environment

* Version used: 4.0.2
* Operating System and version: mac

**Comment by grasshopper7** [comment]
What is the older version of Cucumber-jvm?

**Comment by grasshopper7** [comment]
There is a 'not a nice' hack to get it working with Jackson mappers but allows one to go forward. Change the type of the step definition argument from 'String' to 'List<List<String>>'. You have to dig deep to get to the actual text.

```
@Given("the doc string details are")
public void docstring(List<List<String>> doctext) {
       System.out.println(doctext.get(0).get(0));
}
```
I think multiline docstrings are treated as "one row one column" or "single cell" datatable without any header. Refer [here for a discussion on this](https://github.com/cucumber/cucumber/issues/440).
Right now adding Jackson mappers with TableEntryByTypeTransformer is throwing exceptions for this case. Though if u only add TableCellByTypeTransformer it works as expected.

**Comment by aniruddha125** [comment]
@grasshopper7 the hack worked. Thanks for that. I will look forward to a more permanent fix to this issue though.
