### ISSUE TITLE
datatable is not working in groovy script

### ISSUE THREAD

**Issue by seenimurugans** [cucumber/cucumber-jvm#1563]
## Summary

Datatble is not converting to Map properly if i use groovy script for my step definition. But there is no issue if i use normal groovy/java8 class

I created the sample project in github [github link](https://github.com/seenimurugans/cucumberDatatable )

## Expected Behavior

datatable should automatically convert to Map as per the documentation. Please run the example provided in the github link [link](https://github.com/seenimurugans/cucumberDatatable)

## Current Behavior

~~~
cucumber.runtime.CucumberException: Could not convert arguments for step [^I have the below parameters passed$] defined at 'DataTableStepdefs.groovy:6'.
The details are in the stacktrace below.
        at cucumber.runner.PickleStepDefinitionMatch.couldNotConvertArguments(PickleStepDefinitionMatch.java:69)
        at cucumber.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:46)
        at cucumber.runner.TestStep.executeStep(TestStep.java:63)
        at cucumber.runner.TestStep.run(TestStep.java:49)
        at cucumber.runner.PickleStepTestStep.run(PickleStepTestStep.java:43)
        at cucumber.runner.TestCase.run(TestCase.java:44)
        at cucumber.runner.Runner.runPickle(Runner.java:40)
        at cucumber.runtime.Runtime$1.run(Runtime.java:84)
        at cucumber.runtime.Runtime$SameThreadExecutorService.execute(Runtime.java:220)
        at cucumber.runtime.Runtime.run(Runtime.java:81)
        at cucumber.api.cli.Main.run(Main.java:26)
        at cucumber.api.cli.Main.main(Main.java:8)
Caused by: io.cucumber.datatable.CucumberDataTableException: Can't convert DataTable to Map<java.lang.String, java.lang.String>. There is more then one value per key. Did you mean to transform to Map<java.lang.String, List<java.lang.String>> instead?
        at io.cucumber.datatable.CucumberDataTableException.cantConvertToMap(CucumberDataTableException.java:25)
        at io.cucumber.datatable.CucumberDataTableException.keyValueMismatchException(CucumberDataTableException.java:42)
        at io.cucumber.datatable.DataTableTypeRegistryTableConverter.toMap(DataTableTypeRegistryTableConverter.java:212)
        at io.cucumber.datatable.DataTableTypeRegistryTableConverter.convert(DataTableTypeRegistryTableConverter.java:66)
        at io.cucumber.datatable.DataTable.convert(DataTable.java:362)
        at io.cucumber.stepexpression.StepExpressionFactory$3.transform(StepExpressionFactory.java:73)
        at io.cucumber.stepexpression.DeArgument.getValue(DataTableArgument.java:19)
        at cucumber.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:41)
        ... 10 more

:cucumber FAILED

FAILURE: Build failed with an exception.

~~~

## Steps to Reproduce (for bugs)

I provided the [github link](https://github.com/seenimurugans/cucumberDatatable) with Readme file which explains how to run the project. 

When i run the project i see the exception instead to see the passed test results.

## Context & Motivation

I wanted to use groovy script rather than java class as groovy is far better/matured than Java

## Your Environment

* Version used: 
        cucumberVersion = '4.2.0'
	groovyVersion = '2.5.6'

* Operating System and version: mac
* Link to your project: [Link](https://github.com/seenimurugans/cucumberDatatable)

**Comment by mpkorstanje** [comment]
It is not possible to use generic types in Lambdas. They're lost on compilation. This means that:

```groovy
Given(~/^I have the below parameters passed$/) { Map<String, List<String>> params ->
    println("I have the below parameters passed: $params")
}
```

Becomes

```groovy
Given(~/^I have the below parameters passed$/) { Map params ->
    println("I have the below parameters passed: $params")
}
```

So in [GroovyStepDefinition.getParameterInfos](https://github.com/cucumber/cucumber-jvm-groovy/blob/master/groovy/src/main/java/cucumber/runtime/groovy/GroovyStepDefinition.java#L61) ` body.getParameterTypes()` will return  `[Map.class]`

Currently our lambda step definitions in `cuucmber-java8` have the same problem. The error messaging is a bit nicer though because it uses [`requireNonMapOrListType`](
https://github.com/cucumber/cucumber-jvm/blob/master/java8/src/main/java/cucumber/runtime/java8/Java8StepDefinition.java#L149) to provide an early warning. 

Currently the `cucumber-jvm-groovy` is maintained out of sync with `cucumber-jvm` so you may want to submit a PR to that repo to get it fixed. I'll also move this issue there.

As a work around you can try using the Datatable as parameter. 

```groovy
Given(~/^I have the below parameters passed$/) { DataTable params ->
    println("I have the below parameters passed: $params")
}
```

But I'm not sure if [`DataTable.asMap(String.class,List.class)`](https://github.com/cucumber/cucumber/blob/master/datatable/java/datatable/src/main/java/io/cucumber/datatable/DataTable.java#L231) will work for you.
