### ISSUE TITLE
JUnitFormatter$TestCase throws ArrayIndexOutOfBoundsException in parallel execution

### ISSUE THREAD

**Issue by grasshopper7** [cucumber/cucumber-jvm#1575]
Executing two runners in parallel using JUnit 4.12 and Cucumber 4.2.5 using the following configuration in Maven Failsafe plugin version 3.0.0-M3 or 2.22.1.

```
       <parallel>classesAndMethods</parallel>
       <threadCount>2</threadCount>
       <perCoreThreadCount>true</perCoreThreadCount>
```

Also **throws exception when "all"** is used. If "**methods**" setting is used, exception **does not occur**.

Below is the project structure. FirstRunner executes feature in folder first and creates junit report in junit-cucumber-reports-first folder. The other runner does the the same with second folder features in a separate report folder.

`@CucumberOptions(glue="stepdef", plugin = "junit:target/junit-cucumber-reports-first/cukejunit.xml"} ,features="src/test/resources/feature/first")`

![proj](https://user-images.githubusercontent.com/10829355/53859308-49dfe400-4003-11e9-9e5d-18d863728861.png)

The below exception is thrown intermittently and the junit report for that specific runner is empty. Though the scenarios are executed successfully.

```
runner.FirstRunnerjava.lang.ArrayIndexOutOfBoundsException: 8
	at cucumber.runtime.formatter.TestSourcesModel.getKeywordFromSource(TestSourcesModel.java:124)
	at cucumber.runtime.formatter.JUnitFormatter$TestCase.getKeywordFromSource(JUnitFormatter.java:286)
	at cucumber.runtime.formatter.JUnitFormatter$TestCase.addStepAndResultListing(JUnitFormatter.java:276)
	at cucumber.runtime.formatter.JUnitFormatter$TestCase.addTestCaseElement(JUnitFormatter.java:231)
	at cucumber.runtime.formatter.JUnitFormatter.handleTestCaseFinished(JUnitFormatter.java:133)
	at cucumber.runtime.formatter.JUnitFormatter.access$300(JUnitFormatter.java:40)
	at cucumber.runtime.formatter.JUnitFormatter$4.receive(JUnitFormatter.java:69)
	at cucumber.runtime.formatter.JUnitFormatter$4.receive(JUnitFormatter.java:66)
	at cucumber.runner.AbstractEventPublisher.send(AbstractEventPublisher.java:45)
	at cucumber.runner.AbstractEventPublisher.sendAll(AbstractEventPublisher.java:52)
	at cucumber.runner.CanonicalOrderEventPublisher.handle(CanonicalOrderEventPublisher.java:18)
	at cucumber.runtime.formatter.Plugins$1.receive(Plugins.java:55)
	at cucumber.runner.AbstractEventPublisher.send(AbstractEventPublisher.java:38)
	at cucumber.runner.AbstractEventBus.send(AbstractEventBus.java:9)
	at cucumber.runner.TimeServiceEventBus.send(TimeServiceEventBus.java:3)
	at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:132)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:405)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
scenarios1.feature in first folder and scenarios4.feature in second folder are the same and as below.

```
Feature: Scenario1 Types

  Scenario: Scenario1 Description
    Given this is given step
    When this is when step
    Then this is then step

  Scenario Outline: Outline1 Description
    Given this is <num> given step
    When this is <num> when step
    Then this is <num> then step

    Examples: 
      | num    |
      | FIRST  |
      | SECOND |
```
scenarios2.feature, scenarios3.feature, scenarios5.feature and scenarios6.feature are same and as below.

```
Feature: Scenario2 Types

  Scenario: Scenario2 Description
    Given this is given step
    When this is when step
    Then this is then step
```

The `final List<PickleStepTestStep> steps = new ArrayList<PickleStepTestStep>();` in `TestCase` class seems to be shared across threads.
This may be an issue with `TestNGFormatter` as the `cucumber.runtime.formatter.TestSourcesModel.getKeywordFromSource` is also called in it. Though have not tried it out.

**Comment by mpkorstanje** [comment]
Both `TestNGFormatter` and `JUnitFormatter` use static fields internally to track the current state of the test. When parallel execution was introduced we accounted for this by storing all events until the end of the test run. This however doesn't work when there two tests running concurrently.

Doesn't look like the static fields are too hard to refactor out though.

**Comment by mpkorstanje** [comment]
@grasshopper7 would you mind trying to build  #1576 and see if you can still reproduce the problem?

**Comment by grasshopper7** [comment]
@mpkorstanje Works with JUnit.

**Comment by mpkorstanje** [comment]
Cheers. New release coming up.
