### ISSUE TITLE
AmbiguousStepDefinitionsException when using my variable types

### ISSUE THREAD

**Issue by VitalyShalaev** [cucumber/cucumber-jvm#1595]
Summary

I have the following different steps:

@Then("чекбокс {el} не выбран")
    public void checkboxIsNotSelected(SelenideElement el) {
        el.parent().$("input").shouldNotBe(selected);
    }
@Then("чекбокс {el} выбран")
    public void checkboxIsSelected(SelenideElement el) {
        el.parent().$("input").shouldBe(selected);
    }

Defining my type of variables:

public class TypeRegistryConfiguration implements TypeRegistryConfigurer {

    @Override
    public Locale locale() {
        return Locale.ENGLISH;
    }
    @Override
    public void configureTypeRegistry(TypeRegistry typeRegistry) {
        typeRegistry.defineParameterType(new ParameterType<>(
                "el",
                ".*",
                SelenideElement.class,
                ReflectedElementsRegistry.get()::resolve));
    }

And I'm trying to use:
Тогда чекбокс Сравнить не выбран
Тогда чекбокс Сравнить выбран

Witch is leading to:

ucumber.runner.AmbiguousStepDefinitionsException: "чекбокс Сравнить не выбран" matches more than one step definition:
  "чекбокс {el} выбран" in BaseSteps.checkboxIsSelected(SelenideElement)
  "чекбокс {el} не выбран" in BaseSteps.checkboxIsNotSelected(SelenideElement)

	at cucumber.runner.Glue.stepDefinitionMatch(Glue.java:92)
	at cucumber.runner.Runner.addTestStepsForPickleSteps(Runner.java:64)
	at cucumber.runner.Runner.createTestCaseForPickle(Runner.java:54)
	at cucumber.runner.Runner.runPickle(Runner.java:39)
	at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:146)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:73)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:122)
	at cucumber.api.junit.Cucumber.runChild(Cucumber.java:64)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at cucumber.api.junit.Cucumber$1.evaluate(Cucumber.java:131)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)

cucumber.runtime.junit.UndefinedThrowable: The step "иконка Хедер>Сравнение активна" is undefined

cucumber.runtime.junit.UndefinedThrowable: The step "иконка Хедер>Сравнение активна" is undefined

Why is cucumber considering this as AmbiguousStepDefinitionsException?Although the steps are distinguished by the word "не".

Any ideas on what I'm doing wrong here?

Thanks

**Comment by VitalyShalaev** [comment]
Environment settings:
cucumber.version 4.2.6
junit 4.12

**Comment by mpkorstanje** [comment]
Your parameter type `el` is using `.*` as a pattern. This will happily consume the ` не` and thus match both step definitions. I would recommend using a more specific regex.
