### ISSUE TITLE
java.lang.ClassCastException: class gherkin.ast.Feature cannot be cast to class gherkin.ast.ScenarioDefinition

### ISSUE THREAD

**Issue by kutzi** [cucumber/cucumber-jvm#1627]
My Cucumber tests running with --threads=2 fail after test run with this error

 ```
ERROR SerenityMain - Exception in Cucumber runtime

[2019-05-10T11:18:22.880Z] java.lang.ClassCastException: class gherkin.ast.Feature cannot be cast to class gherkin.ast.ScenarioDefinition (gherkin.ast.Feature and gherkin.ast.ScenarioDefinition are in unnamed module of loader 'app')

[2019-05-10T11:18:22.880Z] 	at cucumber.runtime.formatter.TestSourcesModel.getScenarioDefinition(TestSourcesModel.java:46)

[2019-05-10T11:18:22.880Z] 	at cucumber.runtime.formatter.TestSourcesModel.getScenarioDefinition(TestSourcesModel.java:96)

[2019-05-10T11:18:22.880Z] 	at cucumber.runtime.formatter.PrettyFormatter.printScenarioDefinition(PrettyFormatter.java:323)

[2019-05-10T11:18:22.880Z] 	at cucumber.runtime.formatter.PrettyFormatter.handleTestStepStarted(PrettyFormatter.java:138)

[2019-05-10T11:18:22.880Z] 	at cucumber.runtime.formatter.PrettyFormatter.access$200(PrettyFormatter.java:33)

[2019-05-10T11:18:22.880Z] 	at cucumber.runtime.formatter.PrettyFormatter$5.receive(PrettyFormatter.java:73)

[2019-05-10T11:18:22.880Z] 	at cucumber.runtime.formatter.PrettyFormatter$5.receive(PrettyFormatter.java:70)

[2019-05-10T11:18:22.880Z] 	at cucumber.runner.AbstractEventPublisher.send(AbstractEventPublisher.java:45)

[2019-05-10T11:18:22.880Z] 	at cucumber.runner.AbstractEventPublisher.sendAll(AbstractEventPublisher.java:52)

[2019-05-10T11:18:22.880Z] 	at cucumber.runner.CanonicalOrderEventPublisher.handle(CanonicalOrderEventPublisher.java:18)

[2019-05-10T11:18:22.880Z] 	at cucumber.runtime.formatter.Plugins$1.receive(Plugins.java:55)

[2019-05-10T11:18:22.880Z] 	at cucumber.runner.AbstractEventPublisher.send(AbstractEventPublisher.java:38)

[2019-05-10T11:18:22.880Z] 	at cucumber.runner.AbstractEventBus.send(AbstractEventBus.java:9)

[2019-05-10T11:18:22.880Z] 	at cucumber.runner.TimeServiceEventBus.send(TimeServiceEventBus.java:3)

[2019-05-10T11:18:22.880Z] 	at cucumber.runtime.Runtime.run(Runtime.java:98)

[2019-05-10T11:18:22.880Z] 	at cucumber.runtime.Runtime$run.call(Unknown Source)

[2019-05-10T11:18:22.880Z] 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)

[2019-05-10T11:18:22.880Z] 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)

[2019-05-10T11:18:22.880Z] 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:119)

[2019-05-10T11:18:22.880Z] 	at SerenityMain.doRun(SerenityMain.groovy:194)

[2019-05-10T11:18:22.880Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[2019-05-10T11:18:22.880Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

[2019-05-10T11:18:22.880Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[2019-05-10T11:18:22.880Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)

[2019-05-10T11:18:22.880Z] 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)

[2019-05-10T11:18:22.880Z] 	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrapNoCoerce.invoke(StaticMetaMethodSite.java:149)

[2019-05-10T11:18:22.880Z] 	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(StaticMetaMethodSite.java:100)

[2019-05-10T11:18:22.880Z] 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)

[2019-05-10T11:18:22.880Z] 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:196)

[2019-05-10T11:18:22.880Z] 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:216)

[2019-05-10T11:18:22.880Z] 	at SerenityMain$_run_closure1.doCall(SerenityMain.groovy:140)

[2019-05-10T11:18:22.880Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[2019-05-10T11:18:22.880Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

[2019-05-10T11:18:22.880Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[2019-05-10T11:18:22.880Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)

[2019-05-10T11:18:22.880Z] 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)

[2019-05-10T11:18:22.880Z] 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)

[2019-05-10T11:18:22.880Z] 	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)

[2019-05-10T11:18:22.880Z] 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)

[2019-05-10T11:18:22.880Z] 	at groovy.lang.Closure.call(Closure.java:405)

[2019-05-10T11:18:22.880Z] 	at groovy.lang.Closure.call(Closure.java:421)

[2019-05-10T11:18:22.880Z] 	at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2102)

[2019-05-10T11:18:22.880Z] 	at org.codehaus.groovy.runtime.dgm$181.invoke(Unknown Source)

[2019-05-10T11:18:22.880Z] 	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:244)

[2019-05-10T11:18:22.880Z] 	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53)

[2019-05-10T11:18:22.880Z] 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)

[2019-05-10T11:18:22.880Z] 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)

[2019-05-10T11:18:22.880Z] 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)

[2019-05-10T11:18:22.880Z] 	at SerenityMain.run(SerenityMain.groovy:90)

[2019-05-10T11:18:22.880Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

[2019-05-10T11:18:22.880Z] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

[2019-05-10T11:18:22.880Z] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

[2019-05-10T11:18:22.880Z] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)

[2019-05-10T11:18:22.880Z] 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)

[2019-05-10T11:18:22.880Z] 	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite$StaticMetaMethodSiteNoUnwrapNoCoerce.invoke(StaticMetaMethodSite.java:149)

[2019-05-10T11:18:22.880Z] 	at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.callStatic(StaticMetaMethodSite.java:100)

[2019-05-10T11:18:22.880Z] 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallStatic(CallSiteArray.java:55)

[2019-05-10T11:18:22.880Z] 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:196)

[2019-05-10T11:18:22.880Z] 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callStatic(AbstractCallSite.java:216)

[2019-05-10T11:18:22.880Z] 	at SerenityMain.main(SerenityMain.groovy:43)
```

**Comment by kutzi** [comment]
In a different test run, I saw a NPE at the exact same line:
```java.lang.NullPointerException

[2019-05-10T11:15:56.697Z] 	at cucumber.runtime.formatter.TestSourcesModel.getScenarioDefinition(TestSourcesModel.java:46)

[2019-05-10T11:15:56.697Z] 	at cucumber.runtime.formatter.TestSourcesModel.getScenarioDefinition(TestSourcesModel.java:96)

[2019-05-10T11:15:56.697Z] 	at cucumber.runtime.formatter.PrettyFormatter.printScenarioDefinition(PrettyFormatter.java:323)

[2019-05-10T11:15:56.697Z] 	at cucumber.runtime.formatter.PrettyFormatter.handleTestStepStarted(PrettyFormatter.java:138)

[2019-05-10T11:15:56.697Z] 	at cucumber.runtime.formatter.PrettyFormatter.access$200(PrettyFormatter.java:33)

[2019-05-10T11:15:56.697Z] 	at cucumber.runtime.formatter.PrettyFormatter$5.receive(PrettyFormatter.java:73)

[2019-05-10T11:15:56.697Z] 	at cucumber.runtime.formatter.PrettyFormatter$5.receive(PrettyFormatter.java:70)

[2019-05-10T11:15:56.697Z] 	at cucumber.runner.AbstractEventPublisher.send(AbstractEventPublisher.java:45)

[2019-05-10T11:15:56.697Z] 	at cucumber.runner.AbstractEventPublisher.sendAll(AbstractEventPublisher.java:52)

[2019-05-10T11:15:56.697Z] 	at cucumber.runner.CanonicalOrderEventPublisher.handle(CanonicalOrderEventPublisher.java:18)

[2019-05-10T11:15:56.697Z] 	at cucumber.runtime.formatter.Plugins$1.receive(Plugins.java:55)

[2019-05-10T11:15:56.697Z] 	at cucumber.runner.AbstractEventPublisher.send(AbstractEventPublisher.java:38)

[2019-05-10T11:15:56.697Z] 	at cucumber.runner.AbstractEventBus.send(AbstractEventBus.java:9)

[2019-05-10T11:15:56.697Z] 	at cucumber.runner.TimeServiceEventBus.send(TimeServiceEventBus.java:3)
```

**Comment by mpkorstanje** [comment]
I thought this was fixed a while ago with: https://github.com/cucumber/cucumber-jvm/commit/03f6cfac58ab338025d12fd64cb228bb86002ef9 in v4.0.2. But since the stack is passing through: 

```
cucumber.runner.CanonicalOrderEventPublisher.handle(CanonicalOrderEventPublisher.java:18)
```

this appears to be a separate issue. It would appear that events are in an order that is not expected by the `TestSourcesModel`. Can you reproduce this locally?

If so you can put this break point in:

![image](https://user-images.githubusercontent.com/6946919/57528593-0a02e900-7333-11e9-97ef-343422a14431.png)

And then use that break point to enable the any exceptions break point

![image](https://user-images.githubusercontent.com/6946919/57528613-1a1ac880-7333-11e9-8b5d-f0bb1779e521.png)

Once the exception is trigged I would need to know the contents of `CanonicalOrderEventPublisher.queue`.

**Comment by mpkorstanje** [comment]
Btw. Any chance this is related to #1629? If the run fails, the events definitely are not in an order expected yb Cucumber.

**Comment by kutzi** [comment]
Cannot reproduce it locally - as in an IDE.
Yes, this is may be related to #1629

**Comment by mpkorstanje** [comment]
Lets hope so. If not, there isn't much I can do until there is a reproducer.

**Comment by mlvandijk** [comment]
I notice you're running with Serenity. Which version of Cucumber are you using?

**Comment by mpkorstanje** [comment]
@kutzi have you been able to reproduce this with a snapshot build of #1629?

**Comment by mpkorstanje** [comment]
I've just made a new release. Please feel free to reopen if the issue still occurs.
