### ISSUE TITLE
Error parsing feature file from jar when there is a space in path

### ISSUE THREAD

**Issue by tommywo** [cucumber/cucumber-jvm#1632]
## Summary
Error parsing feature file from jar when there is a space in path

## Expected Behavior
File is parsed

## Current Behavior

```
Exception in thread "main" java.lang.IllegalArgumentException: Illegal character in opaque part at index 17: 
classpath:Example path/Feature.feature
	at java.net.URI.create(URI.java:852)
	at cucumber.runtime.io.ZipResource.getPath(ZipResource.java:22)
	at cucumber.runtime.model.FeatureParser.parseResource(FeatureParser.java:30)
	at cucumber.runtime.model.FeatureBuilder.parse(FeatureBuilder.java:25)
	at cucumber.runtime.model.FeatureLoader.loadFromFeaturePath(FeatureLoader.java:36)
	at cucumber.runtime.model.FeatureLoader.load(FeatureLoader.java:23)
	at cucumber.runtime.FeaturePathFeatureSupplier.get(FeaturePathFeatureSupplier.java:33)
	at cucumber.runtime.Runtime.run(Runtime.java:67)
	at cucumber.api.cli.Main.run(Main.java:26)
	at cucumber.api.cli.Main.main(Main.java:8)
```
## Possible Solution
 URI encode the path or just replace spaces with %20

**Comment by mpkorstanje** [comment]
I'm not sure, are spaces allowed in the class path?

**Comment by mpkorstanje** [comment]
Or instead of using `Uri.parse` we could use `new URI("classpath", "path with space", null)` which will escape the URI to `classpath:path%20with%20space`.
