### ISSUE TITLE
Cucumber forces Integer type on a 

### ISSUE THREAD

**Issue by yktoo** [cucumber/cucumber-jvm#1702]
#  Summary

The compatibility with previous version(s) is broken.

A step definition that uses `(\d+)` capture group forces the method have an `Integer` (or `int`) argument. Previously a `String` would do fine.

Example code:
```java
@When("^I type (\\d+) into input field$")
public void register(String value) {
...
```

## Expected Behavior

The typed value is converted into a `String`, just like it was previously (tested with info.cukes.cucumber-java v1.2.5)

## Current Behavior

An exception is thrown:
```
cucumber.runtime.CucumberException: Failed to invoke nl.ns.cucumber.LoketdienstSteps.register(String) in file:[...path...], caused by java.lang.IllegalArgumentException: argument type mismatch
	at cucumber.runtime.Utils$1.call(Utils.java:29)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:20)
	at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:57)
	at cucumber.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:50)
	at cucumber.runner.TestStep.executeStep(TestStep.java:65)
	at cucumber.runner.TestStep.run(TestStep.java:50)
	at cucumber.runner.PickleStepTestStep.run(PickleStepTestStep.java:43)
	at cucumber.runner.TestCase.run(TestCase.java:46)
	at cucumber.runner.Runner.runPickle(Runner.java:50)
	at cucumber.runtime.Runtime$1.run(Runtime.java:104)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at cucumber.runtime.Runtime$SameThreadExecutorService.execute(Runtime.java:258)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at cucumber.runtime.Runtime.run(Runtime.java:101)
	at io.cucumber.core.cli.Main.run(Main.java:43)
	at io.cucumber.core.cli.Main.main(Main.java:14)
Caused by: java.lang.IllegalArgumentException: argument type mismatch
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:26)
	... 17 more

```

## Context & Motivation

This is particularly bad since it would try to convert whatever is given, for example, providing `2222222222` (which is too big for an Integer) results in:

```
cucumber.runtime.CucumberException: Could not convert arguments for step [...] defined at '...'.
The details are in the stacktrace below.
	at cucumber.runner.PickleStepDefinitionMatch.couldNotConvertArguments(PickleStepDefinitionMatch.java:69)
	at cucumber.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:46)
	at cucumber.runner.TestStep.executeStep(TestStep.java:65)
	at cucumber.runner.TestStep.run(TestStep.java:50)
	at cucumber.runner.PickleStepTestStep.run(PickleStepTestStep.java:43)
	at cucumber.runner.TestCase.run(TestCase.java:46)
	at cucumber.runner.Runner.runPickle(Runner.java:50)
	at cucumber.runtime.Runtime$1.run(Runtime.java:104)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at cucumber.runtime.Runtime$SameThreadExecutorService.execute(Runtime.java:258)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at cucumber.runtime.Runtime.run(Runtime.java:101)
	at io.cucumber.core.cli.Main.run(Main.java:43)
	at io.cucumber.core.cli.Main.main(Main.java:14)
Caused by: io.cucumber.cucumberexpressions.CucumberExpressionException: ParameterType {int} failed to transform [2222222222] to class java.lang.Integer
	at io.cucumber.cucumberexpressions.ParameterType.transform(ParameterType.java:190)
	at io.cucumber.cucumberexpressions.Argument.getValue(Argument.java:64)
	at io.cucumber.stepexpression.ExpressionArgument.getValue(ExpressionArgument.java:15)
	at cucumber.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:41)
	... 13 more
Caused by: java.lang.NumberFormatException: For input string: "2222222222"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:583)
	at java.lang.Integer.valueOf(Integer.java:740)
	at java.lang.Integer.decode(Integer.java:1197)
	at io.cucumber.cucumberexpressions.BuiltInParameterTransformer.transform(BuiltInParameterTransformer.java:51)
	at io.cucumber.cucumberexpressions.ParameterTypeRegistry$5.transform(ParameterTypeRegistry.java:70)
	at io.cucumber.cucumberexpressions.ParameterTypeRegistry$5.transform(ParameterTypeRegistry.java:67)
	at io.cucumber.cucumberexpressions.ParameterType$TransformerAdaptor.transform(ParameterType.java:215)
	at io.cucumber.cucumberexpressions.ParameterType.transform(ParameterType.java:186)
	... 16 more
```

## Your Environment

* Cucumber 4.6.0
* Java 8

**Comment by mlvandijk** [comment]
Not sure this is a bug or a feature. "\d, \D: ANY ONE digit/non-digit character. Digits are [0-9]" so it imho it really should be a digit (int) and not a String. 

Also note there have been some breaking changes on major versions. Please check the migration guides [here](https://cucumber.io/docs/guides/upgrading/#migration-guides).

**Comment by yktoo** [comment]
> imho it really should be a digit (int) and not a String.

Alright, but how do you handle the input like the `2222222222` above, which doesn't fit into an Integer?

**Comment by aslakhellesoy** [comment]
@yktoo how does this work?

```java
@When("^I type (\\d+) into input field$")
public void register(BigInteger value) {
```

**Comment by mpkorstanje** [comment]
@aslakhellesoy in the `ParameterTypeRegistry` the `BigDecimal` parameter has set the `useForRegexMatch` to `false` because it's the same pattern for integer. For Java I think we might have to parse everything to number and use the method parameter type to work out which type of number.

Prior to v3 we used to throw everything at XStream and most of the time we'd get something usable back. Cucumber expressions does have all those smart type conversions build in.

@yktoo

Can't try this out but if you use the Cucumber Expression instead it should be at bit easier:

```
@When("I type {word} into input field")
```

But since you're entering strings you may well do

```
@When("I type {string} into input field")
```

which will match `I type "22222" into the input filed" and typographically marks the bounds of the input.

**Comment by yktoo** [comment]
@mpkorstanje  That is indeed my workaround to use `{string}` and Cucumber Expression for the time being. This lacks, however, the input validation bit.

I have two other humble thoughts on the matter:
1. It must be possible to coerce any type into a `String` (simply using `toString()`) disregarding the capture group pattern. I can't really see why it's forbidden.
2. The way of inferring the Integer type from `\d+` is a bit controversial and I don't really understand the rationale behind it. For instance, `([\d]+)` (which is essentially equivalent) works just fine supplying a `String` argument.

**Comment by mpkorstanje** [comment]
>  I don't really understand the rationale behind it. 

Mostly because of an imperfect migration.

Cucumber used XStream to handle all the type conversions. We had to stop using XStream because it fails to work modern Java versions. The next best replacement was then serendipitously created `cucumber-expression` library. However the library was mostly designed for to solve problems encountered by cucumber implementations in weakly typed languages. Ruby, Javascript, ect only had to deal with `Number` rather then `Integer`, `Long`, `BigInteger`, ect and these assumptions were carried over in the java implementation.

Now a while ago we did add `typeHints` to the `CucumberExpression` and `RegularExpression` implementation. Currently it is only used by the anonymous parameter type but I think it can be used allow for a bit more lenient argument conversion of numbers/strings.

**Comment by aslakhellesoy** [comment]
I think this will work:

```java
@When("I type {bigint} into input field")
public void register(java.math.BigInteger value) {
```

My motivation for creating the Cucumber-Expressions library was to provide a simpler alternative to RegExp which many people seem to struggle with. It then made sense to move the RegExp logic into that library so we have a consistent way to transform capture groups (or cukexp output parameters) to other types.

Another motivation was to introduce the concept of parameter types. I think `{currency}` conveys more info than `[A-Z]{3}`, and the fact that snippets will suggest known types also improves user experience.

So for me, improved UX was the primary motivation and it coincied with the need to get rid of XStream.

Because `\d+` is used so frequently I thought the user experience would be better if it were automatically converted to an `int` in the dynamic language implementations of the library (Ruby, JavaScript).

While we've done our best to keep the RegExp support backwards compatible, there are some edge cases where the behaviour has changed or is buggy.

This will be a fun one to fix!
