### ISSUE TITLE
CustomPicoFactory Not getting picked after upgrading to io.cucumber versions 4.7.2

### ISSUE THREAD

**Issue by nikhilnicks** [cucumber/cucumber-jvm#1807]
Tried above mentioned solution. **Cucumber runner is not picking CustomPicoFactory**
I am not using DynamicBrowserManager at this moment because I am writing BDD for REST API's

```
public class CustomPicoFactory implements ObjectFactory {
    private PicoFactory delegate = new PicoFactory();

    public CustomPicoFactory() {
       addClass(SomeImplementation.class)
    }

    @Override
    public void start() {
        delegate.start();
    }

    @Override
    public void stop() {
        delegate.stop();
    }

    @Override
    public boolean addClass(Class<?> aClass) {
        return delegate.addClass(aClass);
    }

    @Override
    public <T> T getInstance(Class<T> aClass) {
        return delegate.getInstance(aClass);
    }
}
```
Even added entry of CustomPicoFactory to cucumber.properties
No error while running feature files
Logs
```
INFO: Loading ObjectFactory via service loader: io.cucumber.picocontainer.PicoFactory
```
Cucumber Version = 4.7.2

**Comment by mpkorstanje** [comment]
`ObjectFactories` are loaded via SPI. Do you have a `META-INF/services/io.cucumber.core.backend.ObjectFactory` available on your class path with the FQN of `CustomPicoFactory` in it?

> Even added entry of CustomPicoFactory to cucumber.properties

Please include the exact information.

**Comment by nikhilnicks** [comment]
What do you mean by FQN?

`Do you have a META-INF/services/io.cucumber.core.backend.ObjectFactory?`
Kindly see below image
If you see the below image it shows 
<img width="387" alt="Screen Shot 2019-10-17 at 10 46 43 AM" src="https://user-images.githubusercontent.com/5394859/67033889-7dbbd580-f0cb-11e9-9e39-94b2e4007560.png">

Where to add CustomPicoFactory?

**Comment by toepi** [comment]
FQN = Full Quallified Name

Given your packages is com.example
and your custom Objectfactory has CustomPicoFactory as classname
then the fan is com.example.CustomPicoFactory

The shown service-descriptor is for the default picofactory. You need your own `io.cucumber.core.backend.ObjectFactory` in your jar.

**Comment by nikhilnicks** [comment]
Where to add CustomPicoFactory with FQN ?
Tried adding to cucumber.properties but does not work

`io.cucumber.core.backend.ObjectFactory=.com.example.CustomPicoFactory`

**Comment by toepi** [comment]
inside your class path put under `META-INF/services/` a file with name `io.cucumber.core.backend.ObjectFactory` with only contains your fqn of your custom factory.

**Comment by LearningPur** [comment]
After upgrading pico-container version 5.0.0-RC1 from 1.2.5 i have started getting error message and desperately need help as our current production code is failing due to this migration. 

Any help asap would be appreciated.

**_Maven pom.xml change_** 

**Upgraded from this** 
 

**To this**
        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-picocontainer</artifactId>
            <version>5.0.0-RC1</version>
            <scope>test</scope>
        </dependency>

**_I am creating an instance of page class during runtime using these 4 list of classes_** 

**_Basepage.java_**

public class BasePage  {

    public static HomePage goToHomePage(Scenario scenario, String UserEmailID) {

        Selenide.refresh();
        if (WebDriverRunner.url().equalsIgnoreCase("https://www.footlocker.com/")) {
       }
        return page(HomePage.class);
    }
}

**BaseSteps.java**

import io.cucumber.java8.En;
import org.picocontainer.annotations.Inject;

public class BaseSteps implements En {

    @Inject
    private PageContainer pageContainer;

    protected void update(BasePage newPage) {
        pageContainer.updatePage(newPage);
    }

    protected BasePage page() {
        return pageContainer.getPage();
    }
}

**_PageContainer.java_**

public class PageContainer {

    private BasePage currentPage;

    public void updatePage(BasePage newPage) {
        currentPage = newPage;
    }

    public BasePage getPage() {
        return currentPage;
    }
}

**_PicoDependencyInjector.java_**

import io.cucumber.core.backend.ObjectFactory;
import io.cucumber.picocontainer.PicoFactory;

public class PicoDependencyInjector implements ObjectFactory {

    private PicoFactory delegate = new PicoFactory();

    public PicoDependencyInjector() {
        addClass(PageContainer.class);
    }


    @Override
    public void start() {
        delegate.start();
    }

    @Override
    public void stop() {
        delegate.stop();
    }

    @Override
    public boolean addClass(Class<?> aClass) {
        return delegate.addClass(aClass);
    }

    @Override
    public <T> T getInstance(Class<T> aClass) {
        return delegate.getInstance(aClass);
    }
}

**_cucumber.properties_**

io.cucumber.core.backend.ObjectFactory = com.footlocker.core.PicoDependencyInjector

_**Error i am getting is**_ 

org.picocontainer.injectors.AbstractInjector$UnsatisfiableDependenciesException: com.footlocker.steps.RegisterMultiUserSteps has unsatisfied dependency for fields [com.footlocker.core.PageContainer.pageContainer] from org.picocontainer.DefaultPicoContainer@661972b0:5<|

	at org.picocontainer.injectors.AbstractFieldInjector.unsatisfiedDependencies(AbstractFieldInjector.java:30)
	at org.picocontainer.injectors.IterativeInjector.getMatchingParameterListForSetters(IterativeInjector.java:104)
	at org.picocontainer.injectors.IterativeInjector.access$000(IterativeInjector.java:33)
	at org.picocontainer.injectors.IterativeInjector$2.run(IterativeInjector.java:153)
	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
	at org.picocontainer.injectors.IterativeInjector.getComponentInstance(IterativeInjector.java:160)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
	at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
	at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
	at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:678)
	at io.cucumber.picocontainer.PicoFactory.getInstance(PicoFactory.java:47)
	at io.cucumber.java8.Java8Backend.buildWorld(Java8Backend.java:62)
	at io.cucumber.core.runner.Runner.buildBackendWorlds(Runner.java:165)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:61)
	at io.cucumber.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:149)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:83)
	at io.cucumber.junit.FeatureRunner.runChild(FeatureRunner.java:24)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at io.cucumber.junit.Cucumber.runChild(Cucumber.java:174)
	at io.cucumber.junit.Cucumber.runChild(Cucumber.java:82)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at io.cucumber.junit.Cucumber$RunCucumber.evaluate(Cucumber.java:208)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
