### ISSUE TITLE
Picocontainer trying to inject the constructor of Selenium custom WebElement class but failed

### ISSUE THREAD

**Issue by ansonliaomelco** [cucumber/cucumber-jvm#1815]
Hi, 
I am new to the Cucumber Picocontainer.
I am using cucumber picocontainer version `4.3.1` with Selenium to test my website, I am using the selenium extension library `htmlelements-java` (https://github.com/yandex-qatools/htmlelements) for handling the page object.

In my testing script no code of Picocontainer except the dependency of build.grade of Gradle.

I created a new WebElement named `Label` by the HtmlElement library wrapper, and the code snippet as below:

```java
public class Label extends TypifiedElement {

    /**
     * Specifies wrapped {@link WebElement}.
     *
     * @param wrappedElement {@code WebElement} to wrap.
     */
    protected Label(WebElement wrappedElement) {
        super(wrappedElement);
    }

}
```

And then I created a page object such as below:

```java
public class GooglePage {
    private WebDriver driver;

    @FindBy(id = "bookingSuccessDescription")
    @Name("Booking Message")
    public Label label;

    public GooglePage() {
        System.setProperty("webdriver.chrome.driver", "/path/to/chromedriver");
        WebDriver driver = new ChromeDriver();
        PageFactory.initElements(new HtmlElementDecorator(new HtmlElementLocatorFactory(driver)), this);
    }

    ...
}
```

and create some tests:

```java
public class DemoTest {

    @Test
    public void f1() {
        GooglePage = new GooglePage();
        ...
    }
}
```

When I run the test, and I got the error from Picocontainer:

```shell
ru.yandex.qatools.htmlelements.exceptions.HtmlElementsException: java.lang.NoSuchMethodException: No such accessible constructor on object: melco.common.Label
	at ru.yandex.qatools.htmlelements.loader.HtmlElementLoader.createTypifiedElement(HtmlElementLoader.java:134)
	at ru.yandex.qatools.htmlelements.loader.decorator.HtmlElementDecorator.decorateTypifiedElement(HtmlElementDecorator.java:82)
	at ru.yandex.qatools.htmlelements.loader.decorator.HtmlElementDecorator.decorate(HtmlElementDecorator.java:55)
	at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:113)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
	at xxx.xxx.GooglePage.<init>(GooglePage.java:20)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.picocontainer.injectors.AbstractInjector.newInstance(AbstractInjector.java:145)
	at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:342)
	at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
	at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
	at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
	at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
	at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
	at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
	at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:678)
	at cucumber.runtime.java.picocontainer.PicoFactory.getInstance(PicoFactory.java:40)
	at cucumber.runtime.java.JavaStepDefinition.execute(JavaStepDefinition.java:57)
	at cucumber.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:50)
	at cucumber.runner.TestStep.executeStep(TestStep.java:65)
	at cucumber.runner.TestStep.run(TestStep.java:50)
	at cucumber.runner.PickleStepTestStep.run(PickleStepTestStep.java:43)
	at cucumber.runner.TestCase.run(TestCase.java:46)
	at cucumber.runner.Runner.runPickle(Runner.java:49)
	at cucumber.runtime.Runtime$1.run(Runtime.java:82)
	at cucumber.runtime.Runtime$SameThreadExecutorService.execute(Runtime.java:217)
	at cucumber.runtime.Runtime.run(Runtime.java:79)
	at cucumber.api.cli.Main.run(Main.java:26)
	at cucumber.api.cli.Main.main(Main.java:8)
```

I am not sure the issue in deep, it looks like Picocontainer is attempting to inject `the constructor of Label.java` but failed, could you kindly provide some solution about this?

Thanks.

**Comment by mpkorstanje** [comment]
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We use GitHub issues to track bugs and feature requests exclusively.

And this part of the code tell me the problem is in your code:

```
ru.yandex.qatools.htmlelements.exceptions.HtmlElementsException: java.lang.NoSuchMethodException: No such accessible constructor on object: melco.common.Label
	at ru.yandex.qatools.htmlelements.loader.HtmlElementLoader.createTypifiedElement(HtmlElementLoader.java:134)
	at ru.yandex.qatools.htmlelements.loader.decorator.HtmlElementDecorator.decorateTypifiedElement(HtmlElementDecorator.java:82)
	at ru.yandex.qatools.htmlelements.loader.decorator.HtmlElementDecorator.decorate(HtmlElementDecorator.java:55)
	at org.openqa.selenium.support.PageFactory.proxyFields(PageFactory.java:113)
	at org.openqa.selenium.support.PageFactory.initElements(PageFactory.java:105)
	at xxx.xxx.GooglePage.<init>(GooglePage.java:20)
```
