### ISSUE TITLE
NullPointer exception while registering custom data table converter

### ISSUE THREAD

**Issue by fslev** [cucumber/cucumber-jvm#1864]
## Summary

NullPointer exception while registering custom data table converter

## Current Behavior
Register the following table converter:
```java
    @DataTableType
    public List convertDataTable(DataTable dataTable) {
        return new ArrayList();
    }
``` 
Define the following step:
```java
    @Given("table {}=")
    public void setCustomDataTable(String name, List value) {
        log.debug("Param {} = {}", name, value);
    }
```
Create the following scenario:
```gherkin
Scenario: Compare empty data tables
    Given table empty_table=
      | test |
      |      |
```
Run the scenario:
```
Step failed
io.cucumber.core.exception.CucumberException: Could not convert arguments for step [table {}=] defined at 'com.cucumber.utils.context.stepdefs.ParamSteps.setCustomDataTable(java.lang.String,java.util.Map)'.
The details are in the stacktrace below.
	at io.cucumber.core.runner.PickleStepDefinitionMatch.couldNotConvertArguments(PickleStepDefinitionMatch.java:108)
	at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:52)
	at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:64)
	at io.cucumber.core.runner.TestStep.run(TestStep.java:49)
	at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:46)
	at io.cucumber.core.runner.TestCase.run(TestCase.java:51)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:66)
	at io.cucumber.core.runtime.Runtime.lambda$null$2(Runtime.java:100)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at io.cucumber.core.runtime.Runtime$SameThreadExecutorService.execute(Runtime.java:243)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
	at io.cucumber.core.runtime.Runtime.lambda$run$3(Runtime.java:100)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.SliceOps$1$1.accept(SliceOps.java:199)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1631)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.cucumber.core.runtime.Runtime.run(Runtime.java:101)
	at io.cucumber.core.cli.Main.run(Main.java:73)
	at io.cucumber.core.cli.Main.main(Main.java:31)
Caused by: io.cucumber.datatable.CucumberDataTableException: 'java.util.List' could not transform
      | test |
      |      |

	at io.cucumber.datatable.DataTableType.transform(DataTableType.java:124)
	at io.cucumber.datatable.DataTableTypeRegistryTableConverter.toListOrNull(DataTableTypeRegistryTableConverter.java:150)
	at io.cucumber.datatable.DataTableTypeRegistryTableConverter.convertEntryKeys(DataTableTypeRegistryTableConverter.java:262)
	at io.cucumber.datatable.DataTableTypeRegistryTableConverter.toMap(DataTableTypeRegistryTableConverter.java:216)
	at io.cucumber.datatable.DataTableTypeRegistryTableConverter.convert(DataTableTypeRegistryTableConverter.java:73)
	at io.cucumber.datatable.DataTable.convert(DataTable.java:357)
	at io.cucumber.core.stepexpression.StepExpressionFactory.lambda$createExpression$4(StepExpressionFactory.java:63)
	at io.cucumber.core.stepexpression.DataTableArgument.getValue(DataTableArgument.java:19)
	at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:47)
	... 24 more
Caused by: java.lang.NullPointerException
	at io.cucumber.java.AbstractDatatableElementTransformerDefinition.replaceEmptyPatternsWithEmptyString
```

**Comment by mpkorstanje** [comment]
Heya, 

I can't reproduce this using the information you've provided and the stack trace got cut off a the critical part

```
Caused by: java.lang.NullPointerException
	at io.cucumber.java.AbstractDatatableElementTransformerDefinition.replaceEmptyPatternsWithEmptyString
```

There should be some line numbers here and perhaps a few more bits of stack frame.

**Comment by mpkorstanje** [comment]
Ah found it.
```
    @DataTableType(replaceWithEmptyString = "[empty]")
```

The `replaceWithEmptyString` was actually relevant.

**Comment by fslev** [comment]
Actually I tangled a little the description.

There are 2 cases in which the NPE happens:

1.) With 'replaceWithEmptyString'
```java
    @DataTableType(replaceWithEmptyString = {"[blank]"})
    public List convertDataTable(DataTable tableEntry) {
        return new ArrayList();
    }

    @Given("table {}=")
    public void setCustomDataTable(String name, List value) {
        log.debug("Param {} = {}", name, value);
    }
```

2.) Without 'replaceWithEmptyString'
```java
    @DataTableType
    public List convertDataTable(Map<String,String> tableEntry) {
        return new ArrayList();
    }

    @Given("table {}=")
    public void setCustomDataTable(String name, List<Map> value) {
        log.debug("Param {} = {}", name, value);
    }
```

**Comment by mpkorstanje** [comment]
`Datatable.asMaps()` has a key collision when null keys are used. Not actually an NPE but based on same assumption as the table entry NPE.

**Comment by fslev** [comment]
Hi,
Issue is not entirely fixed.
Only 1st scenario described from above is fixed.
However, in the 2nd scenario, where
```java
@DataTableType
    public Map convertDataTable(Map<String,String> tableEntry) {
        return new HashMap();
    }

    @Given("table {}=")
    public void setCustomDataTable(String name, List<Map> value) {
        log.debug("Param {} = {}", name, value);
    }
```
now I get a different error:
```
Step failed
io.cucumber.core.exception.CucumberException: Could not convert arguments for step [table {}=] defined at 'com.cucumber.utils.context.stepdefs.ParamSteps.setCustomDataTable(java.lang.String,java.util.List<java.util.Map<java.lang.String, java.lang.String>>)'.
The details are in the stacktrace below.
	at io.cucumber.core.runner.PickleStepDefinitionMatch.couldNotConvertArguments(PickleStepDefinitionMatch.java:108)
	at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:52)
	at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:64)
	at io.cucumber.core.runner.TestStep.run(TestStep.java:49)
	at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:46)
	at io.cucumber.core.runner.TestCase.run(TestCase.java:51)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:66)
	at io.cucumber.core.runtime.Runtime.lambda$run$2(Runtime.java:100)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at io.cucumber.core.runtime.Runtime$SameThreadExecutorService.execute(Runtime.java:243)
	at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:118)
	at io.cucumber.core.runtime.Runtime.lambda$run$3(Runtime.java:100)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.stream.SliceOps$1$1.accept(SliceOps.java:199)
	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1631)
	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:127)
	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:502)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:488)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at io.cucumber.core.runtime.Runtime.run(Runtime.java:101)
	at io.cucumber.core.cli.Main.run(Main.java:73)
	at io.cucumber.core.cli.Main.main(Main.java:31)
Caused by: io.cucumber.datatable.CucumberDataTableException: 'java.util.List<java.util.Map<java.lang.String, java.lang.String>>' could not transform
      | firstName | lastName |
      | #[a]      | [blank]  |
      | sam       | .*       |
      |           | ~[name]  |

	at io.cucumber.datatable.DataTableType.transform(DataTableType.java:124)
	at io.cucumber.datatable.DataTableTypeRegistryTableConverter.convert(DataTableTypeRegistryTableConverter.java:64)
	at io.cucumber.datatable.DataTable.convert(DataTable.java:360)
	at io.cucumber.core.stepexpression.StepExpressionFactory.lambda$createExpression$4(StepExpressionFactory.java:63)
	at io.cucumber.core.stepexpression.DataTableArgument.getValue(DataTableArgument.java:19)
	at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:47)
	... 24 more
Caused by: io.cucumber.core.backend.CucumberInvocationTargetException
	at io.cucumber.java.Invoker.invoke(Invoker.java:34)
	at io.cucumber.java.JavaDataTableTypeDefinition.execute(JavaDataTableTypeDefinition.java:108)
	at io.cucumber.java.JavaDataTableTypeDefinition.lambda$createDataTableType$2(JavaDataTableTypeDefinition.java:88)
	at io.cucumber.datatable.DataTableType$TableEntryTransformerAdaptor.transform(DataTableType.java:234)
	at io.cucumber.datatable.DataTableType$TableEntryTransformerAdaptor.transform(DataTableType.java:216)
	at io.cucumber.datatable.DataTableType.transform(DataTableType.java:121)
	... 29 more

```
Theoretically, in my scenario:
```gherkin
Scenario: Compare empty data tables
    Given table empty_table=
      | test |
      |      |
```
there shouldn't be any null key, since "test" is the key and null is the value.

Or, am I doing something wrong here ?

Regards

**Comment by mpkorstanje** [comment]
> Or, am I doing something wrong here ?
> cucumber version used: 5.1.0

I would think so. I can't reproduce the problem. 

The relevant bit of code:

```java
        if (Map.class.equals(parameterType)) {
            return new DataTableType(
                returnType,
                (Map<String, String> entry) -> execute(replaceEmptyPatternsWithEmptyString(entry))
            );
        }
```

And this bit of the stack trace suggests you've already gone passed `replaceEmptyPatternsWithEmptyString` and are now calling into the `setCustomDataTable` method. 

```
Caused by: io.cucumber.core.backend.CucumberInvocationTargetException
	at io.cucumber.java.Invoker.invoke(Invoker.java:34)
	at io.cucumber.java.JavaDataTableTypeDefinition.execute(JavaDataTableTypeDefinition.java:108)
	at io.cucumber.java.JavaDataTableTypeDefinition.lambda$createDataTableType$2(JavaDataTableTypeDefinition.java:88)
	at io.cucumber.datatable.DataTableType$TableEntryTransformerAdaptor.transform(DataTableType.java:234)
	at io.cucumber.datatable.DataTableType$TableEntryTransformerAdaptor.transform(DataTableType.java:216)
	at io.cucumber.datatable.DataTableType.transform(DataTableType.java:121)
	... 29 more
```

**Comment by mpkorstanje** [comment]
This does reproduce the exact problem and which leads me to believe that we're swallowing part of the stack trace somewhere. But it also indicates that the problem is in `convertDataTable` 

```
    @DataTableType
    public Map convertDataTable(Map<String,String> tableEntry) {
        throw new NullPointerException();
    }
```

**Comment by fslev** [comment]
Actually, indeed I was doing something wrong.
Inside my project I had some business code that was executing, and somewhere it threw a null pointer exception.
Indeed, relevant stacktrace of my code was somehow swallowed.
However, this issue is entirely fixed.

Thanks for the replies.
