### ISSUE TITLE
'UnknownFormatConversionException' inside TeamCityPlugin while writing special characters such as: '%'

### ISSUE THREAD

**Issue by fslev** [cucumber/cucumber-jvm#1881]
Steps to reproduce:

```java
scenario.write("%")
```
Actual:
```
java.util.UnknownFormatConversionException: Conversion = '%'
	at java.base/java.util.Formatter.checkText(Formatter.java:2732)
	at java.base/java.util.Formatter.parse(Formatter.java:2718)
	at java.base/java.util.Formatter.format(Formatter.java:2655)
	at java.base/java.util.Formatter.format(Formatter.java:2609)
	at java.base/java.lang.String.format(String.java:2897)
	at io.cucumber.core.plugin.TeamCityPlugin.formatCommand(TeamCityPlugin.java:367)
	at io.cucumber.core.plugin.TeamCityPlugin.print(TeamCityPlugin.java:358)
	at io.cucumber.core.plugin.TeamCityPlugin.handleWriteEvent(TeamCityPlugin.java:354)
	at io.cucumber.core.eventbus.AbstractEventPublisher.send(AbstractEventPublisher.java:45)
	at io.cucumber.core.eventbus.AbstractEventBus.send(AbstractEventBus.java:9)
	at io.cucumber.core.runner.TestCaseState.write(TestCaseState.java:67)
	at io.cucumber.java.Scenario.write(Scenario.java:48)
```

**Comment by mpkorstanje** [comment]
Cheers!
