### ISSUE TITLE
Rerun formatter returns paths with `.` in the middle instead of `/`

### ISSUE THREAD

**Issue by tommywo** [cucumber/cucumber-jvm#1892]
**Describe the bug**
Rerun formatter returns paths with `.` in the middle instead of `/`
for example 
```
classpath:com/stepstone/selenium/cucumber/AutomateTeam.Sanity/TestowyFeature.feature:4
```
and when we try to rerun this file it ends with an error:
```
[Utils] [ERROR] [Error] java.lang.IllegalArgumentException: Feature not found: classpath:com/stepstone/selenium/cucumber/AutomateTeam.Sanity/TestowyFeature.feature
	at io.cucumber.core.runtime.FeaturePathFeatureSupplier.loadFeatures(FeaturePathFeatureSupplier.java:64)
	at io.cucumber.core.runtime.FeaturePathFeatureSupplier.get(FeaturePathFeatureSupplier.java:46)
	at io.cucumber.testng.TestNGCucumberRunner.getFeatures(TestNGCucumberRunner.java:157)
	at io.cucumber.testng.TestNGCucumberRunner.provideScenarios(TestNGCucumberRunner.java:135)
	at io.cucumber.testng.AbstractTestNGCucumberTests.scenarios(AbstractTestNGCucumberTests.java:43)
```

changing the dot to slash fixes rerun file

**Your Environment**
 - cucumber-java v5.2.0

**Comment by mpkorstanje** [comment]
What is the directory structure? If you're on OSX or Lunix you can run `tree` to print the directory structure

```
$:~/cucumber-java-skeleton/src/test/resources$ tree
.
└── io
    └── cucumber
        └── skeleton
            └── belly.feature
```

**Comment by tommywo** [comment]
```
.
├── com
│   └── stepstone
│       └── selenium
│           └── cucumber
│               ├── AutomateTeam
│               │   ├── Sanity
│               │   │   └── TestowyFeature.feature
```

**Comment by mpkorstanje** [comment]
What did you provide for the glue? Of if you're not providing it explicitly, what is the package of your runner class?

**Comment by tommywo** [comment]
I've provided `com.stepstone.selenium.cucumber.steps` as glue.

Steps to reproduce:
```bash
git clone  https://github.com/tommywo/cucumber-java-skeleton issue-1892
cd issue-1892
mvn -Dtest=io.cucumber.skeleton.RunCucumberTest test
cat target/cucumber-report/rerun.txt
mvn -Dtest=io.cucumber.skeleton.ReRunCucumberTest test
```

**Comment by mpkorstanje** [comment]
Thanks!
