### ISSUE TITLE
cucumber-spring 5.7.0 and spring-kafka - Test does not fail or stop on `DuplicateStepDefinitionException`

### ISSUE THREAD

**Issue by cless91** [cucumber/cucumber-jvm#1982]
**Describe the bug**
When duplicated step, the test does not stop or fail.

**To Reproduce**
1. maybe for an following update if screenshots not enough

**Expected behavior**
expected the test run to just fail, and the jvm / process to just be shut down

**Context & Motivation**

I am using cucumber to perform some sort of component test on some backend service using Kafka.

**Screenshots**
cannot copy-paste nor upload a screenshot for some reason ...
`Something went really wrong, and we can’t process that file. Try again`

**Your Environment**
 - Versions used : 5.7.0
 - Operating System and version : debian 9
 - Build tool : IntelliJ
 - spring-kafka : 2.3.8.RELEASE
 - springboot: 2.2.7.RELEASE

**Additional context**

**Comment by cless91** [comment]
```
09:19:38.579 [org.springframework.kafka.KafkaListenerEndpointContainer#2-0-C-1] INFO  o.a.k.c.c.i.AbstractCoordinator - [Consumer clientId=consumer-1, groupId=fr-cardeventnotifier-consumer] (Re-)joining group
09:19:38.605 [main] INFO  o.s.t.c.s.AbstractContextLoader - Could not detect default resource locations for test class [fr.ing.payment.cardeventnotifier.tests.SpringCucumberContextConfiguration]: no resource found for suffixes {-context.xml, Context.groovy}.
09:19:38.621 [main] INFO  o.s.b.t.c.SpringBootTestContextBootstrapper - Loaded default TestExecutionListener class names from location [META-INF/spring.factories]: [org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener, org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener, org.springframework.boot.test.autoconfigure.restdocs.RestDocsTestExecutionListener, org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener, org.springframework.boot.test.autoconfigure.web.servlet.MockMvcPrintOnlyOnFailureTestExecutionListener, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverTestExecutionListener, org.springframework.test.context.web.ServletTestExecutionListener, org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener, org.springframework.test.context.support.DependencyInjectionTestExecutionListener, org.springframework.test.context.support.DirtiesContextTestExecutionListener, org.springframework.test.context.transaction.TransactionalTestExecutionListener, org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener, org.springframework.test.context.event.EventPublishingTestExecutionListener]
09:19:38.621 [main] INFO  o.s.b.t.c.SpringBootTestContextBootstrapper - Using TestExecutionListeners: [org.springframework.test.context.web.ServletTestExecutionListener@2965dd88, org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener@3221588e, org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener@51141f64, org.springframework.boot.test.autoconfigure.SpringBootDependencyInjectionTestExecutionListener@32c0fecc, org.springframework.test.context.support.DirtiesContextTestExecutionListener@35ceec81, org.springframework.test.context.transaction.TransactionalTestExecutionListener@d13379e, org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener@7c8df667, org.springframework.test.context.event.EventPublishingTestExecutionListener@498e41a4, org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener@be616f0, org.springframework.boot.test.autoconfigure.restdocs.RestDocsTestExecutionListener@1f5d7fd5, org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener@cf08c97, org.springframework.boot.test.autoconfigure.web.servlet.MockMvcPrintOnlyOnFailureTestExecutionListener@37c87fcc, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverTestExecutionListener@ca2be53]
09:19:38.630 [main] INFO  o.s.t.c.s.AbstractContextLoader - Could not detect default resource locations for test class [fr.ing.payment.cardeventnotifier.tests.SpringCucumberContextConfiguration]: no resource found for suffixes {-context.xml, Context.groovy}.
09:19:38.635 [main] INFO  o.s.b.t.c.SpringBootTestContextBootstrapper - Loaded default TestExecutionListener class names from location [META-INF/spring.factories]: [org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener, org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener, org.springframework.boot.test.autoconfigure.restdocs.RestDocsTestExecutionListener, org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener, org.springframework.boot.test.autoconfigure.web.servlet.MockMvcPrintOnlyOnFailureTestExecutionListener, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverTestExecutionListener, org.springframework.test.context.web.ServletTestExecutionListener, org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener, org.springframework.test.context.support.DependencyInjectionTestExecutionListener, org.springframework.test.context.support.DirtiesContextTestExecutionListener, org.springframework.test.context.transaction.TransactionalTestExecutionListener, org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener, org.springframework.test.context.event.EventPublishingTestExecutionListener]
09:19:38.635 [main] INFO  o.s.b.t.c.SpringBootTestContextBootstrapper - Using TestExecutionListeners: [org.springframework.test.context.web.ServletTestExecutionListener@42b43a6, org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener@1d622556, org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener@4b9f7edc, org.springframework.boot.test.autoconfigure.SpringBootDependencyInjectionTestExecutionListener@70ee1963, org.springframework.test.context.support.DirtiesContextTestExecutionListener@2e0652ab, org.springframework.test.context.transaction.TransactionalTestExecutionListener@22c29aa8, org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener@129b69b2, org.springframework.test.context.event.EventPublishingTestExecutionListener@12be4f83, org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener@eb1d475, org.springframework.boot.test.autoconfigure.restdocs.RestDocsTestExecutionListener@389008d1, org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener@718f3088, org.springframework.boot.test.autoconfigure.web.servlet.MockMvcPrintOnlyOnFailureTestExecutionListener@11adab6d, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverTestExecutionListener@11bfd751]
09:19:38.643 [main] INFO  o.s.t.c.s.AbstractContextLoader - Could not detect default resource locations for test class [fr.ing.payment.cardeventnotifier.tests.SpringCucumberContextConfiguration]: no resource found for suffixes {-context.xml, Context.groovy}.
09:19:38.649 [main] INFO  o.s.b.t.c.SpringBootTestContextBootstrapper - Loaded default TestExecutionListener class names from location [META-INF/spring.factories]: [org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener, org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener, org.springframework.boot.test.autoconfigure.restdocs.RestDocsTestExecutionListener, org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener, org.springframework.boot.test.autoconfigure.web.servlet.MockMvcPrintOnlyOnFailureTestExecutionListener, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverTestExecutionListener, org.springframework.test.context.web.ServletTestExecutionListener, org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener, org.springframework.test.context.support.DependencyInjectionTestExecutionListener, org.springframework.test.context.support.DirtiesContextTestExecutionListener, org.springframework.test.context.transaction.TransactionalTestExecutionListener, org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener, org.springframework.test.context.event.EventPublishingTestExecutionListener]
09:19:38.649 [main] INFO  o.s.b.t.c.SpringBootTestContextBootstrapper - Using TestExecutionListeners: [org.springframework.test.context.web.ServletTestExecutionListener@2152fde5, org.springframework.test.context.support.DirtiesContextBeforeModesTestExecutionListener@5d58dc61, org.springframework.boot.test.mock.mockito.MockitoTestExecutionListener@32328dc4, org.springframework.boot.test.autoconfigure.SpringBootDependencyInjectionTestExecutionListener@17df689e, org.springframework.test.context.support.DirtiesContextTestExecutionListener@21540255, org.springframework.test.context.transaction.TransactionalTestExecutionListener@3a7469ca, org.springframework.test.context.jdbc.SqlScriptsTestExecutionListener@1c8e8fed, org.springframework.test.context.event.EventPublishingTestExecutionListener@70f98f7a, org.springframework.boot.test.mock.mockito.ResetMocksTestExecutionListener@713e7d9a, org.springframework.boot.test.autoconfigure.restdocs.RestDocsTestExecutionListener@681d704e, org.springframework.boot.test.autoconfigure.web.client.MockRestServiceServerResetTestExecutionListener@846b47, org.springframework.boot.test.autoconfigure.web.servlet.MockMvcPrintOnlyOnFailureTestExecutionListener@3c3ab672, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverTestExecutionListener@3e6acec2]
09:19:38.657 [main] ERROR i.c.c.r.Runtime - Exception while executing pickle
java.util.concurrent.ExecutionException: io.cucumber.core.runner.DuplicateStepDefinitionException: Duplicate step definitions in fr.ing.payment.cardeventnotifier.tests.applepay.endofprovisioning.ApplePayEndOfProvisioningCucumberSteps.theSMSHasBeenSentToOrangeWithStatusOrAndCauseOrAndThePhoneNumberOfTheRecipientIsCorrect(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) and fr.ing.payment.cardeventnotifier.tests.applepay.activationmethods.ApplePayActivationMethodsCucumberSteps.theSMSHasBeenSentToOrangeWithStatusOrAndCauseOrAndThePhoneNumberOfTheRecipientIsCorrect(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at io.cucumber.core.runtime.Runtime.run(Runtime.java:108)
	at io.cucumber.core.cli.Main.run(Main.java:75)
	at io.cucumber.core.cli.Main.main(Main.java:31)
Caused by: io.cucumber.core.runner.DuplicateStepDefinitionException: Duplicate step definitions in fr.ing.payment.cardeventnotifier.tests.applepay.endofprovisioning.ApplePayEndOfProvisioningCucumberSteps.theSMSHasBeenSentToOrangeWithStatusOrAndCauseOrAndThePhoneNumberOfTheRecipientIsCorrect(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) and fr.ing.payment.cardeventnotifier.tests.applepay.activationmethods.ApplePayActivationMethodsCucumberSteps.theSMSHasBeenSentToOrangeWithStatusOrAndCauseOrAndThePhoneNumberOfTheRecipientIsCorrect(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)
	at io.cucumber.core.runner.CachingGlue.lambda$prepareGlue$4(CachingGlue.java:218)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at io.cucumber.core.runner.CachingGlue.prepareGlue(CachingGlue.java:214)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:64)
	at io.cucumber.core.runtime.Runtime.lambda$run$2(Runtime.java:100)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at io.cucumber.core.runtime.Runtime$SameThreadExecutorService.execute(Runtime.java:243)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at io.cucumber.core.runtime.Runtime.lambda$run$3(Runtime.java:100)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.SliceOps$1$1.accept(SliceOps.java:204)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.cucumber.core.runtime.Runtime.run(Runtime.java:101)
	... 2 common frames omitted
09:19:38.658 [main] ERROR i.c.c.r.Runtime - Exception while executing pickle
java.util.concurrent.ExecutionException: io.cucumber.core.runner.DuplicateStepDefinitionException: Duplicate step definitions in fr.ing.payment.cardeventnotifier.tests.applepay.endofprovisioning.ApplePayEndOfProvisioningCucumberSteps.theSMSHasBeenSentToOrangeWithStatusOrAndCauseOrAndThePhoneNumberOfTheRecipientIsCorrect(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) and fr.ing.payment.cardeventnotifier.tests.applepay.activationmethods.ApplePayActivationMethodsCucumberSteps.theSMSHasBeenSentToOrangeWithStatusOrAndCauseOrAndThePhoneNumberOfTheRecipientIsCorrect(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at io.cucumber.core.runtime.Runtime.run(Runtime.java:108)
	at io.cucumber.core.cli.Main.run(Main.java:75)
	at io.cucumber.core.cli.Main.main(Main.java:31)
Caused by: io.cucumber.core.runner.DuplicateStepDefinitionException: Duplicate step definitions in fr.ing.payment.cardeventnotifier.tests.applepay.endofprovisioning.ApplePayEndOfProvisioningCucumberSteps.theSMSHasBeenSentToOrangeWithStatusOrAndCauseOrAndThePhoneNumberOfTheRecipientIsCorrect(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) and fr.ing.payment.cardeventnotifier.tests.applepay.activationmethods.ApplePayActivationMethodsCucumberSteps.theSMSHasBeenSentToOrangeWithStatusOrAndCauseOrAndThePhoneNumberOfTheRecipientIsCorrect(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)
	at io.cucumber.core.runner.CachingGlue.lambda$prepareGlue$4(CachingGlue.java:218)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at io.cucumber.core.runner.CachingGlue.prepareGlue(CachingGlue.java:214)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:64)
	at io.cucumber.core.runtime.Runtime.lambda$run$2(Runtime.java:100)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at io.cucumber.core.runtime.Runtime$SameThreadExecutorService.execute(Runtime.java:243)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at io.cucumber.core.runtime.Runtime.lambda$run$3(Runtime.java:100)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.SliceOps$1$1.accept(SliceOps.java:204)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.cucumber.core.runtime.Runtime.run(Runtime.java:101)
	... 2 common frames omitted
09:19:38.661 [main] ERROR i.c.c.r.Runtime - Exception while executing pickle
java.util.concurrent.ExecutionException: io.cucumber.core.runner.DuplicateStepDefinitionException: Duplicate step definitions in fr.ing.payment.cardeventnotifier.tests.applepay.endofprovisioning.ApplePayEndOfProvisioningCucumberSteps.theSMSHasBeenSentToOrangeWithStatusOrAndCauseOrAndThePhoneNumberOfTheRecipientIsCorrect(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) and fr.ing.payment.cardeventnotifier.tests.applepay.activationmethods.ApplePayActivationMethodsCucumberSteps.theSMSHasBeenSentToOrangeWithStatusOrAndCauseOrAndThePhoneNumberOfTheRecipientIsCorrect(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at io.cucumber.core.runtime.Runtime.run(Runtime.java:108)
	at io.cucumber.core.cli.Main.run(Main.java:75)
	at io.cucumber.core.cli.Main.main(Main.java:31)
Caused by: io.cucumber.core.runner.DuplicateStepDefinitionException: Duplicate step definitions in fr.ing.payment.cardeventnotifier.tests.applepay.endofprovisioning.ApplePayEndOfProvisioningCucumberSteps.theSMSHasBeenSentToOrangeWithStatusOrAndCauseOrAndThePhoneNumberOfTheRecipientIsCorrect(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) and fr.ing.payment.cardeventnotifier.tests.applepay.activationmethods.ApplePayActivationMethodsCucumberSteps.theSMSHasBeenSentToOrangeWithStatusOrAndCauseOrAndThePhoneNumberOfTheRecipientIsCorrect(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)
	at io.cucumber.core.runner.CachingGlue.lambda$prepareGlue$4(CachingGlue.java:218)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at io.cucumber.core.runner.CachingGlue.prepareGlue(CachingGlue.java:214)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:64)
	at io.cucumber.core.runtime.Runtime.lambda$run$2(Runtime.java:100)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at io.cucumber.core.runtime.Runtime$SameThreadExecutorService.execute(Runtime.java:243)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at io.cucumber.core.runtime.Runtime.lambda$run$3(Runtime.java:100)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.SliceOps$1$1.accept(SliceOps.java:204)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.cucumber.core.runtime.Runtime.run(Runtime.java:101)
	... 2 common frames omitted
09:19:38.661 [main] ERROR i.c.c.r.Runtime - Exception while executing pickle
java.util.concurrent.ExecutionException: io.cucumber.core.runner.DuplicateStepDefinitionException: Duplicate step definitions in fr.ing.payment.cardeventnotifier.tests.applepay.endofprovisioning.ApplePayEndOfProvisioningCucumberSteps.theSMSHasBeenSentToOrangeWithStatusOrAndCauseOrAndThePhoneNumberOfTheRecipientIsCorrect(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) and fr.ing.payment.cardeventnotifier.tests.applepay.activationmethods.ApplePayActivationMethodsCucumberSteps.theSMSHasBeenSentToOrangeWithStatusOrAndCauseOrAndThePhoneNumberOfTheRecipientIsCorrect(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at io.cucumber.core.runtime.Runtime.run(Runtime.java:108)
	at io.cucumber.core.cli.Main.run(Main.java:75)
	at io.cucumber.core.cli.Main.main(Main.java:31)
Caused by: io.cucumber.core.runner.DuplicateStepDefinitionException: Duplicate step definitions in fr.ing.payment.cardeventnotifier.tests.applepay.endofprovisioning.ApplePayEndOfProvisioningCucumberSteps.theSMSHasBeenSentToOrangeWithStatusOrAndCauseOrAndThePhoneNumberOfTheRecipientIsCorrect(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) and fr.ing.payment.cardeventnotifier.tests.applepay.activationmethods.ApplePayActivationMethodsCucumberSteps.theSMSHasBeenSentToOrangeWithStatusOrAndCauseOrAndThePhoneNumberOfTheRecipientIsCorrect(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)
	at io.cucumber.core.runner.CachingGlue.lambda$prepareGlue$4(CachingGlue.java:218)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at io.cucumber.core.runner.CachingGlue.prepareGlue(CachingGlue.java:214)
	at io.cucumber.core.runner.Runner.runPickle(Runner.java:64)
	at io.cucumber.core.runtime.Runtime.lambda$run$2(Runtime.java:100)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at io.cucumber.core.runtime.Runtime$SameThreadExecutorService.execute(Runtime.java:243)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at io.cucumber.core.runtime.Runtime.lambda$run$3(Runtime.java:100)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.SliceOps$1$1.accept(SliceOps.java:204)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at io.cucumber.core.runtime.Runtime.run(Runtime.java:101)
	... 2 common frames omitted
Exception in thread "main" io.cucumber.core.exception.CompositeCucumberException: There were 4 exceptions:
  io.cucumber.core.runner.DuplicateStepDefinitionException(Duplicate step definitions in fr.ing.payment.cardeventnotifier.tests.applepay.endofprovisioning.ApplePayEndOfProvisioningCucumberSteps.theSMSHasBeenSentToOrangeWithStatusOrAndCauseOrAndThePhoneNumberOfTheRecipientIsCorrect(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) and fr.ing.payment.cardeventnotifier.tests.applepay.activationmethods.ApplePayActivationMethodsCucumberSteps.theSMSHasBeenSentToOrangeWithStatusOrAndCauseOrAndThePhoneNumberOfTheRecipientIsCorrect(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String))
  io.cucumber.core.runner.DuplicateStepDefinitionException(Duplicate step definitions in fr.ing.payment.cardeventnotifier.tests.applepay.endofprovisioning.ApplePayEndOfProvisioningCucumberSteps.theSMSHasBeenSentToOrangeWithStatusOrAndCauseOrAndThePhoneNumberOfTheRecipientIsCorrect(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) and fr.ing.payment.cardeventnotifier.tests.applepay.activationmethods.ApplePayActivationMethodsCucumberSteps.theSMSHasBeenSentToOrangeWithStatusOrAndCauseOrAndThePhoneNumberOfTheRecipientIsCorrect(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String))
  io.cucumber.core.runner.DuplicateStepDefinitionException(Duplicate step definitions in fr.ing.payment.cardeventnotifier.tests.applepay.endofprovisioning.ApplePayEndOfProvisioningCucumberSteps.theSMSHasBeenSentToOrangeWithStatusOrAndCauseOrAndThePhoneNumberOfTheRecipientIsCorrect(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) and fr.ing.payment.cardeventnotifier.tests.applepay.activationmethods.ApplePayActivationMethodsCucumberSteps.theSMSHasBeenSentToOrangeWithStatusOrAndCauseOrAndThePhoneNumberOfTheRecipientIsCorrect(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String))
  io.cucumber.core.runner.DuplicateStepDefinitionException(Duplicate step definitions in fr.ing.payment.cardeventnotifier.tests.applepay.endofprovisioning.ApplePayEndOfProvisioningCucumberSteps.theSMSHasBeenSentToOrangeWithStatusOrAndCauseOrAndThePhoneNumberOfTheRecipientIsCorrect(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String) and fr.ing.payment.cardeventnotifier.tests.applepay.activationmethods.ApplePayActivationMethodsCucumberSteps.theSMSHasBeenSentToOrangeWithStatusOrAndCauseOrAndThePhoneNumberOfTheRecipientIsCorrect(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String))
	at io.cucumber.core.runtime.Runtime.run(Runtime.java:120)
	at io.cucumber.core.cli.Main.run(Main.java:75)
	at io.cucumber.core.cli.Main.main(Main.java:31)
09:19:39.307 [org.springframework.kafka.KafkaListenerEndpointContainer#2-0-C-1] INFO  o.a.k.c.c.i.AbstractCoordinator - [Consumer clientId=consumer-1, groupId=fr-cardeventnotifier-consumer] Successfully joined group with generation 15
09:19:39.307 [org.springframework.kafka.KafkaListenerEndpointContainer#0-0-C-1] INFO  o.a.k.c.c.i.AbstractCoordinator - [Consumer clientId=consumer-3, groupId=fr-cardeventnotifier-consumer] Successfully joined group with generation 15
09:19:39.307 [org.springframework.kafka.KafkaListenerEndpointContainer#3-0-C-1] INFO  o.a.k.c.c.i.AbstractCoordinator - [Consumer clientId=consumer-2, groupId=fr-cardeventnotifier-consumer] Successfully joined group with generation 15
09:19:39.311 [org.springframework.kafka.KafkaListenerEndpointContainer#3-0-C-1] INFO  o.a.k.c.c.i.ConsumerCoordinator - [Consumer clientId=consumer-2, groupId=fr-cardeventnotifier-consumer] Setting newly assigned partitions: 
09:19:39.315 [org.springframework.kafka.KafkaListenerEndpointContainer#3-0-C-1] INFO  o.s.k.l.KafkaMessageListenerContainer - fr-cardeventnotifier-consumer: partitions assigned: []
09:19:39.317 [org.springframework.kafka.KafkaListenerEndpointContainer#0-0-C-1] INFO  o.a.k.c.c.i.ConsumerCoordinator - [Consumer clientId=consumer-3, groupId=fr-cardeventnotifier-consumer] Setting newly assigned partitions: fr-customer-history-update-0
09:19:39.317 [org.springframework.kafka.KafkaListenerEndpointContainer#2-0-C-1] INFO  o.a.k.c.c.i.ConsumerCoordinator - [Consumer clientId=consumer-1, groupId=fr-cardeventnotifier-consumer] Setting newly assigned partitions: fr-cardeventnotifier-status-historise-topic-0
09:19:39.321 [org.springframework.kafka.KafkaListenerEndpointContainer#1-0-C-1] INFO  o.a.k.c.c.i.AbstractCoordinator - [Consumer clientId=consumer-4, groupId=fr-cardeventnotifier-consumer] Successfully joined group with generation 15
09:19:39.326 [org.springframework.kafka.KafkaListenerEndpointContainer#1-0-C-1] INFO  o.a.k.c.c.i.ConsumerCoordinator - [Consumer clientId=consumer-4, groupId=fr-cardeventnotifier-consumer] Setting newly assigned partitions: ingfrpaymentnotificationeventtopic-0
09:19:39.355 [org.springframework.kafka.KafkaListenerEndpointContainer#2-0-C-1] INFO  o.a.k.c.c.i.ConsumerCoordinator - [Consumer clientId=consumer-1, groupId=fr-cardeventnotifier-consumer] Setting offset for partition fr-cardeventnotifier-status-historise-topic-0 to the committed offset FetchPosition{offset=0, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=localhost:9092 (id: 1 rack: null), epoch=0}}
09:19:39.360 [org.springframework.kafka.KafkaListenerEndpointContainer#0-0-C-1] INFO  o.a.k.c.c.i.ConsumerCoordinator - [Consumer clientId=consumer-3, groupId=fr-cardeventnotifier-consumer] Setting offset for partition fr-customer-history-update-0 to the committed offset FetchPosition{offset=0, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=localhost:9092 (id: 1 rack: null), epoch=0}}
09:19:39.364 [org.springframework.kafka.KafkaListenerEndpointContainer#1-0-C-1] INFO  o.a.k.c.c.i.ConsumerCoordinator - [Consumer clientId=consumer-4, groupId=fr-cardeventnotifier-consumer] Setting offset for partition ingfrpaymentnotificationeventtopic-0 to the committed offset FetchPosition{offset=0, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=localhost:9092 (id: 1 rack: null), epoch=0}}
09:19:39.371 [org.springframework.kafka.KafkaListenerEndpointContainer#1-0-C-1] INFO  o.s.k.l.KafkaMessageListenerContainer - fr-cardeventnotifier-consumer: partitions assigned: [ingfrpaymentnotificationeventtopic-0]
09:19:39.372 [org.springframework.kafka.KafkaListenerEndpointContainer#0-0-C-1] INFO  o.s.k.l.KafkaMessageListenerContainer - fr-cardeventnotifier-consumer: partitions assigned: [fr-customer-history-update-0]
09:19:39.381 [org.springframework.kafka.KafkaListenerEndpointContainer#2-0-C-1] INFO  o.s.k.l.KafkaMessageListenerContainer - fr-cardeventnotifier-consumer: partitions assigned: [fr-cardeventnotifier-status-historise-topic-0]
```

**Comment by mpkorstanje** [comment]
>  When duplicated step, the test does not stop or fail.

I'm seeing that an exception is thrown on the `main` thread that should normally stop the test. Could you provide a minimal reproducer in the form of a github repo?

```
Exception in thread "main" io.cucumber.core.exception.CompositeCucumberException: .....
	at io.cucumber.core.runtime.Runtime.run(Runtime.java:120)
	at io.cucumber.core.cli.Main.run(Main.java:75)
	at io.cucumber.core.cli.Main.main(Main.java:31)
```

**Comment by mpkorstanje** [comment]
Please feel free to reopen this with a minimal reproducer in the form of a github repo.
