### ISSUE TITLE
CustomPicoFactory loading returns errorr  "io.cucumber.core.exception.CucumberException: Could not find object factory 'FQN'"

### ISSUE THREAD

**Issue by mderevyankoaqa** [cucumber/cucumber-jvm#2132]
**Description**
It seems the that Custom PicoFactory has been registered in SPI and right things are in property file, but I'm getting the exepation like this

```
 io.cucumber.core.exception.CucumberException: Could not find object factory github.cucumber.tests.CustomPicoFactory.
    Cucumber uses SPI to discover object factory implementations.
    Has the class been registered with SPI and is it available on the classpath?
        at io.cucumber.core.runtime.ObjectFactoryServiceLoader.loadSelectedObjectFactory(ObjectFactoryServiceLoader.java:79)
        at io.cucumber.core.runtime.ObjectFactoryServiceLoader.loadObjectFactory(ObjectFactoryServiceLoader.java:49)
        at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
```

**To Reproduce**
Use the following artifacts and execute

The CustomPicoFactory class
```

package github.cucumber.tests;


import github.cucumber.tests.controllers.*;
import io.cucumber.core.backend.ObjectFactory;
import io.cucumber.picocontainer.PicoFactory;

public class CustomPicoFactory implements ObjectFactory {

    private final PicoFactory delegate = new PicoFactory();

    public CustomPicoFactory() {

             switch (Device.getDevice()) {
                case CHROME:
                    addClass(ChromeController.class);
                    break;
                case FIREFOX:
                    addClass(FirefoxController.class);
                    break;
            }

    }

    @Override
    public void start() {
        delegate.start();
    }

    @Override
    public void stop() {
        delegate.stop();
    }

    @Override
    public boolean addClass(Class<?> aClass) {
        return delegate.addClass(aClass);
    }

    @Override
    public <T> T getInstance(Class<T> aClass) {
        return delegate.getInstance(aClass);
    }
}
```

The properties file
![image](https://user-images.githubusercontent.com/58083002/94294594-b82f2300-ff68-11ea-977b-389f59c597fb.png)

**SPI registration**
![image](https://user-images.githubusercontent.com/58083002/94294717-e3b20d80-ff68-11ea-83d7-a9a93fc66b29.png)

![image](https://user-images.githubusercontent.com/58083002/94294810-0ba17100-ff69-11ea-93df-68a20c7d66b3.png)

Environment
```

apply plugin: 'java'
apply plugin: 'io.qameta.allure'

sourceCompatibility = 11


ext {
    cucumberVersion = '6.7.0'
    webDriverVersion = '3.141.59'
    
}

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath "io.qameta.allure:allure-gradle:2.8.1"
    }
}

allure {
    version = '2.8.1'
    autoconfigure = true
    aspectjweaver = true
    clean = true
    allureJavaVersion = '2.13.5'

    reportDir = file(allureReportDir)
}

dependencies {
    implementation 'org.jetbrains:annotations:19.0.0'
    testImplementation 'io.cucumber:cucumber-java:' + cucumberVersion
    testImplementation 'io.cucumber:cucumber-junit:' + cucumberVersion
    testImplementation 'io.cucumber:cucumber-picocontainer:' + cucumberVersion
    testImplementation "org.assertj:assertj-core:3.11.1"
    testImplementation 'io.qameta.allure:allure-cucumber4-jvm:2.13.5'
    testImplementation 'org.slf4j:slf4j-jdk14:1.6.1'
    testImplementation 'org.seleniumhq.selenium:selenium-java:' + webDriverVersion

}

repositories {
    mavenCentral()
}

```

I'm new in Java, spent a few days on this. Could you please help me, maybe I missed something?
Many thanks.

**Comment by mpkorstanje** [comment]
> It seems the that Custom PicoFactory has been registered in SPI and right things are in property file

Given that you are receiving the error message the opposite would seem to be the case. I would suggest that you carefully check the details of your implementation. And since you are new with Java you may want to follow a tutorial on SPI first so that you can test your assumptions with fewer components involved. https://docs.oracle.com/javase/tutorial/ext/basics/spi.html

For future reference please use the [support forums](https://community.smartbear.com/t5/Cucumber-Open/bd-p/CucumberOS)  for questions and discussions. We use GitHub issues to track bugs and feature requests exclusively.
