### ISSUE TITLE
Cucumber fails to run when the project path contains spaces.

### ISSUE THREAD

**Issue by rkraneis** [cucumber/cucumber-jvm#2196]
**Describe the bug**
Cucumber fails to run when the project path contains spaces.

**Expected behavior**
Cucumber should convert the space containing path correctly to a URI.

**Your Environment**
 - Cucumber Versions tested: 6.0.0 and 6.9.1 (core + java8)
 - Operating System and version: Amazon Linux (Jenkins Build Server), reproduced on dev machine
 - Build tool: Apache Maven 3.6.3
 - Test runner: Junit Platform Engine + Junit Vintage

**Additional context**
```
java.lang.IllegalArgumentException: java.net.URISyntaxException: Illegal character in path at index 65: file:/home/ec2-user/jenkins/workspace/failing-projectname/Nightly Build/<redacted>
	at io.cucumber.core.resource.ClasspathSupport.getUrisForResource(ClasspathSupport.java:62)
	at io.cucumber.core.resource.ResourceScanner.scanForClasspathResource(ResourceScanner.java:113)
	at io.cucumber.core.resource.ResourceScanner.scanForResourcesUri(ResourceScanner.java:131)
	at io.cucumber.core.runtime.FeaturePathFeatureSupplier.loadFeatures(FeaturePathFeatureSupplier.java:62)
	at io.cucumber.core.runtime.FeaturePathFeatureSupplier.get(FeaturePathFeatureSupplier.java:45)
	at io.cucumber.junit.Cucumber.<init>(Cucumber.java:157)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.vintage.engine.discovery.DefensiveAllDefaultPossibilitiesBuilder$DefensiveAnnotatedBuilder.buildRunner(DefensiveAllDefaultPossibilitiesBuilder.java:114)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.vintage.engine.discovery.DefensiveAllDefaultPossibilitiesBuilder.runnerForClass(DefensiveAllDefaultPossibilitiesBuilder.java:57)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.vintage.engine.discovery.ClassSelectorResolver.resolveTestClass(ClassSelectorResolver.java:66)
	at org.junit.vintage.engine.discovery.ClassSelectorResolver.resolve(ClassSelectorResolver.java:47)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.lambda$resolve$2(EngineDiscoveryRequestResolution.java:134)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1361)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:185)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolve(EngineDiscoveryRequestResolution.java:125)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.resolveCompletely(EngineDiscoveryRequestResolution.java:91)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolution.run(EngineDiscoveryRequestResolution.java:82)
	at org.junit.platform.engine.support.discovery.EngineDiscoveryRequestResolver.resolve(EngineDiscoveryRequestResolver.java:113)
	at org.junit.vintage.engine.discovery.VintageDiscoverer.discover(VintageDiscoverer.java:44)
	at org.junit.vintage.engine.VintageTestEngine.discover(VintageTestEngine.java:63)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverEngineRoot(DefaultLauncher.java:181)
	at org.junit.platform.launcher.core.DefaultLauncher.discoverRoot(DefaultLauncher.java:168)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:206)
	at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:161)
	at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:84)
	at org.apache.maven.plugin.surefire.InPluginVMSurefireStarter.runSuitesInProcess(InPluginVMSurefireStarter.java:87)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1166)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1011)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:857)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: java.net.URISyntaxException: Illegal character in path at index 65: file:/home/ec2-user/jenkins/workspace/failing-projectname/Nightly Build/<redacted>
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URL.toURI(URL.java:964)
	at io.cucumber.core.resource.ClasspathSupport.getUrisForResource(ClasspathSupport.java:58)
	... 73 more
```
This problem was fixed in the past (#1874) but seems to have regressed at least since 6.0.0.

**Comment by rkraneis** [comment]
Actually, cucumber 5.1.1 also fails to run:
```
java.lang.IllegalArgumentException: java.net.URISyntaxException: Illegal character in path at index 33: file:/home/rene/Projects/business automation/<redacted>
	at io.cucumber.core.resource.ClasspathSupport.getUrisForResource(ClasspathSupport.java:57)
	at io.cucumber.core.resource.ResourceScanner.scanForClasspathResource(ResourceScanner.java:64)
	at io.cucumber.core.resource.ResourceScanner.scanForResourcesUri(ResourceScanner.java:83)
	at io.cucumber.core.runtime.FeaturePathFeatureSupplier.loadFeatures(FeaturePathFeatureSupplier.java:62)
	at io.cucumber.core.runtime.FeaturePathFeatureSupplier.get(FeaturePathFeatureSupplier.java:46)
	at io.cucumber.junit.Cucumber.<init>(Cucumber.java:156)
        <remaining stack trace same as above>
Caused by: java.net.URISyntaxException: Illegal character in path at index 33: file:/home/rene/Projects/business automation/<redacted>
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URL.toURI(URL.java:964)
	at io.cucumber.core.resource.ClasspathSupport.getUrisForResource(ClasspathSupport.java:53)
	... 73 more
```
(tested with JDK 8 and 11)

**Comment by mpkorstanje** [comment]
I'm afraid there is some information missing to reproduce this problem, what does your `@CucumberOptions` look like?

**Comment by rkraneis** [comment]
```
@RunWith(Cucumber.class)
@CucumberOptions(
    monochrome = true,
    plugin = {
      "progress",
      "json:target/cucumber-report/cucumber.json",
      "html:target/cucumber-report/cucumber.html"
    },
    tags = "not @wip",
    stepNotifications = true)
```

**Comment by rkraneis** [comment]
Using a symlink for testing doesn't trigger the problem as the path get's normalized.

**Comment by rkraneis** [comment]
I'll try to set up an MVE to eliminate variables.

**Comment by mpkorstanje** [comment]
What is your classpath root?

**Comment by rkraneis** [comment]
We are running these features with failsafe, it must have something to do with how we do that. Moving the tests to surefire makes cucumber work in this case. I also checked out the skeleton project in the mean time, both surefire and failsafe work fine.

**Comment by rkraneis** [comment]
> What is your classpath root?

What do you mean with that?

**Comment by rkraneis** [comment]
OK, I boiled it down to `<forkCount>0</forkCount>` and was able to reproduce it in the skeleton project.

**Comment by mpkorstanje** [comment]
I'm afraid I still can't reproduce the problem.

The code in question:

```
    static List<URI> getUrisForResource(ClassLoader classLoader, String resourceName) {
        try {
            Enumeration<URL> resources = classLoader.getResources(resourceName);
            List<URI> uris = new ArrayList<>();
            while (resources.hasMoreElements()) {
                URL resource = resources.nextElement();
                uris.add(resource.toURI());
            }
            return uris;
        } catch (Exception e) {
            throw new IllegalArgumentException(e);
        }
    }
``` 
When using a project with spaces in the path these spaces are converted to `%20` by the Class Loader.

```
URL resource = file:/home/mpkorstanje/Projects/cucumber/cucumber%20java%20skeleton/target/test-classes/io/cucumber/skeleton
```

What is the output of your `mvn --version`?

**Comment by mpkorstanje** [comment]
> (i.e. ./mvnw clean test -DforkCount=0 in the unaltered skeleton project)

Ah. That helps. Now I can reproduce it.

**Comment by rkraneis** [comment]
Sorry for the long wind; I guess I could have started with an MVE to get to point a bit earlier :/

**Comment by mpkorstanje** [comment]
it might be worth reading this epistle before continuing. It meanders a bit between surefire and failsafe but the principle is the same for both.

https://maven.apache.org/plugins-archives/maven-failsafe-plugin-2.12.4/examples/class-loading.html

Surefire normally boots tests by executing a specifically crafted jar file. This jar file contains a manifest which references a correct URI.

```
Class-Path:
<ommited>
file:/home/mpkorstanje/Projects/cucumber/cucumber%20java%20skeleton/target/test-classes/
<ommited>
```

When disabling fork mode you'll run tests with `class org.apache.maven.surefire.booter.IsolatedClassLoader` which does not:

```
classLoader = {IsolatedClassLoader@4231} "IsolatedClassLoader{roleName='test'}"
 parent = {Launcher$AppClassLoader@732} 
 urls = {HashSet@4235}  size = 22
  1 = {URL@4252} "file:/home/mpkorstanje/Projects/cucumber/cucumber java skeleton/target/classes/"
```

Fixing this is a bit more complicated then simply replacing the spaces with `%20` because we don't know what the class loader might provide. For now you should consider using either paths without spaces or using a forked jvm.

**Comment by mpkorstanje** [comment]
I think that ultimately the problem lies in the way Surefire constructs the classpath when running tests in process.

The class path is constructed using the absolute path of all source olders in the project:

https://github.com/apache/maven-surefire/blob/master/maven-surefire-common/src/main/java/org/apache/maven/plugin/surefire/TestClassPath.java#L65

```
classpath.add( testClassesDirectory.getAbsolutePath() );
```        

From this class path a `ClassLoader` is created:

https://github.com/apache/maven-surefire/blob/master/surefire-booter/src/main/java/org/apache/maven/surefire/booter/Classpath.java#L149

This class loader converts the paths of the source folders into urls using:

```
classLoader.addURL( new File( classPathElement ).toURL() );
```

Which does not escape the whitespace. This is a bug that can not be fixed.

As mentioned in https://bugs.openjdk.java.net/browse/JDK-6227069 this should be:

```
new File( classPathElement ).toUri().toURL() 
```

You should consider creating a bug report with surefire. Took keep it minimal I would suggest creating a reproducer with a JUnit 4 test that only uses:

```
classLoader.getResources(resourceName).nextElement().toURI()
```

**Comment by rkraneis** [comment]
Thank you very much for looking into this. I'll see if there's already something going on on surefire's side.

**Comment by rkraneis** [comment]
Just for reference if someone else stumbles across this problem: https://issues.apache.org/jira/browse/SUREFIRE-1869.
