### ISSUE TITLE
Better error message when SSL exception occurs during publishing

### ISSUE THREAD

**Issue by aslakhellesoy** [cucumber/cucumber-jvm#2307]
A user has reported the following stack trace when publishing reports:

```
Exception in thread "main" java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

at io.cucumber.core.plugin.MessageFormatter.writeMessage(MessageFormatter.java:36)

at io.cucumber.core.eventbus.AbstractEventPublisher.send(AbstractEventPublisher.java:51)

at io.cucumber.core.eventbus.AbstractEventBus.send(AbstractEventBus.java:12)

at io.cucumber.core.runtime.CucumberExecutionContext.emitTestRunFinished(CucumberExecutionContext.java:102)

at io.cucumber.core.runtime.CucumberExecutionContext.finishTestRun(CucumberExecutionContext.java:74)

at io.cucumber.core.runtime.Runtime.run(Runtime.java:101)

at io.cucumber.core.cli.Main.run(Main.java:92)

at io.cucumber.core.cli.Main.main(Main.java:34)

Caused by: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:131)

at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:369)

at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:312)

at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:307)

at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1357)

at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(CertificateMessage.java:1232)

at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(CertificateMessage.java:1175)

at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:396)

at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:480)

at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:458)

at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:199)

at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:171)

at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1497)

at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1403)

at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:441)

at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:412)

at java.base/sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:574)

at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:183)

at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1419)

at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1390)

at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:220)

at io.cucumber.core.plugin.UrlOutputStream.sendRequest(UrlOutputStream.java:90)

at io.cucumber.core.plugin.UrlOutputStream.sendRequest(UrlOutputStream.java:86)

at io.cucumber.core.plugin.UrlOutputStream.close(UrlOutputStream.java:63)

at java.base/sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:353)

at java.base/sun.nio.cs.StreamEncoder.close(StreamEncoder.java:168)

at java.base/java.io.OutputStreamWriter.close(OutputStreamWriter.java:252)

at io.cucumber.core.plugin.MessageFormatter.writeMessage(MessageFormatter.java:33)

... 7 more

Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:439)

at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:306)

at java.base/sun.security.validator.Validator.validate(Validator.java:264)

at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:231)

at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)

at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1341)

... 30 more

Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:141)

at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:126)

at java.base/java.security.cert.CertPathBuilder.build(CertPathBuilder.java:297)

at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:434)
```

They also told me that they are testing a beta site behind VPN and firewall, and it doesn't have a valid SSL cert.

My hypothesis is that they have defined some `javax.net.ssl.*` system properties in order to be able to access that beta site, and as a side effect of that, broken their ability to establish SSL connections anywhere else (such as Cucumber Reports).

My proposal is to print the values of all `javax.net.ssl.*` system properties when this exception occurs, so that this is easier to diagnose.

**Comment by mpkorstanje** [comment]
The error itself is pretty clear. It means that the trust store used by the JVM does not have a certificate for the target host.

So either the trust store is really old (it happens), or the trust store was replaced with one containing only the self signed certificate. Finally there is also the remote possibility that they are mitm their own connection and the host is not the host the jvm expects it to be.

What is actually the case should be known and discoverable by the people with the problem. They control the JVM and their own eco system.

So as with any other problem that is purely caused by a users specific needs and setup I don't see a reason to add any complexity to Cucumber to facilitate debugging this.

Though what could be more clear is the inclusion of the target host in the exception rather the a plain runtime exception. E.g. "Cucumber couldn't upload a report to host-name".

**Comment by laeubi** [comment]
> diagnose

The usual ways to diagnose SSL problems is described here: https://docs.oracle.com/javase/7/docs/technotes/guides/security/jsse/ReadDebug.html
