### ISSUE TITLE
Couldn't create a file output stream for 'build/test-results/junit.xml'.

### ISSUE THREAD

**Issue by epragtbeamtree** [cucumber/cucumber-jvm#2396]
Hi @mpkorstanje , after upgrading Cucumber from 6.3.0 to 6.11.0, I started getting the following error when running the tests:

```
Exception in thread "main" java.lang.IllegalArgumentException: Couldn't create a file output stream for 'build/test-results/junit.xml'.
Make sure the the file isn't a directory.

Note: This usually happens when plugins write to colliding paths.
For example: 'json:target/cucumber/report.json, html:target/cucumber'
You can fix this by making the paths do no collide.
For example: 'json:target/cucumber/report.json, html:target/cucumber/report.html'
The details are in the stack trace below:
	at io.cucumber.core.plugin.PluginFactory.createFileOutputStream(PluginFactory.java:240)
	at io.cucumber.core.plugin.PluginFactory.openStream(PluginFactory.java:199)
	at io.cucumber.core.plugin.PluginFactory.convert(PluginFactory.java:166)
	at io.cucumber.core.plugin.PluginFactory.instantiate(PluginFactory.java:99)
	at io.cucumber.core.plugin.PluginFactory.create(PluginFactory.java:63)
	at io.cucumber.core.plugin.Plugins.createPlugins(Plugins.java:32)
	at io.cucumber.core.plugin.Plugins.<init>(Plugins.java:25)
	at io.cucumber.core.runtime.Runtime$Builder.build(Runtime.java:171)
	at io.cucumber.core.cli.Main.run(Main.java:90)
	at io.cucumber.core.cli.Main.main(Main.java:34)
Caused by: java.io.FileNotFoundException: build/test-results/junit.xml (Not a directory)
	at java.io.FileOutputStream.open0(Native Method)
Caused by: java.io.FileNotFoundException: build/test-results/junit.xml (Not a directory)

	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
	at io.cucumber.core.plugin.PluginFactory.createFileOutputStream(PluginFactory.java:237)
	... 9 more
```

I'm on Mac, but our build machines are Windows machines, and both have the same issue. I can reliably reproduce it:

<img width="871" alt="image" src="https://user-images.githubusercontent.com/91307175/136122140-5b8479b0-109a-459d-abf2-f2c2f3b439ff.png">

I've checked the file it's trying to read (/Users/erikpragt/projects/pks/rippledown/userneeds/build/run/build/test-results/junit.xml), but that file doesn't exist (yet)

This is coming from our Cucumber arguments:

```
val argsForCuke = listOf("--strict",
                   "--plugin", "junit:build/test-results/junit.xml",
                   "--tags", "@${requirement}",
                   "--glue", "steps", "/${projectDir.path}/src/test/resources/gherkin")
```

If I change the above to this:

```
val argsForCuke = listOf("--strict",
                   "--plugin", "junit:build/junit.xml",
                   "--tags", "@${requirement}",
                   "--glue", "steps", "/${projectDir.path}/src/test/resources/gherkin")
```

Then the test passes, so it seems that something doesn't work well with directory creation.

I did some more debugging, and at that line, if I do:

```
file.getAbsoluteFile()         // /Users/erikpragt/projects/pks/rippledown/userneeds/build/run/build/test-results/junit.xml
file.getParentFile()             // build/test-results
file.getParentFile().isFile() // the result is true
file.getParentFile().isDirectory() // the result is false
```

So, it seems that something creates this `test-results` part as a file, instead of a directory.

However, when I check the directory using my terminal, I see this:

```
➜  build git:(PRD-4095_Upgrade_Cucumber_6.3_to_latest_version) ✗ ls -al
total 0
drwxr-xr-x   3 erikpragt  staff   96  6 Oct 11:20 .
drwxr-xr-x  15 erikpragt  staff  480  6 Oct 11:12 ..
drwxr-xr-x   2 erikpragt  staff   64  6 Oct 11:20 test-results
➜  build git:(PRD-4095_Upgrade_Cucumber_6.3_to_latest_version) ✗ pwd
/Users/erikpragt/projects/pks/rippledown/userneeds/build/run/build
```

So, it seems test-results is directory after all?

This seems to be very similar to #2108 , but that issue is closed, and no matter what I try, I can't seem to resolve this with directories.

I'm on Oracle Java 1.8_301 if that helps.

Anything I can do to help debugging this issue?

**Comment by mpkorstanje** [comment]
```
/Users/erikpragt/projects/pks/rippledown/userneeds/build/run/build/test-results/junit.xml)
```
This path contains the build dir twice. That looks odd. But I can't tell at a glance if it is related.

Could you reproduce this with a minimal GitHub repo?

You can use the https://github.com/cucumber/cucumber-java-skeleton to start.

**Comment by mpkorstanje** [comment]
```
file.getParentFile()             // build/test-results
```

This isn't what I'd expect either. Looks like the / is part of the file name.

**Comment by epragtbeamtree** [comment]
Hi @mpkorstanje , I've managed to reproduce it. I can only reproduce it in a multimodule project, it seems to be working fine when it's a single module project. Execute the `cucumberWip` task to reproduce it.

You can find the repository here: https://github.com/epragtbeamtree/cucumber-report-bug

**Comment by epragtbeamtree** [comment]
Btw, I also tried executing the same code with Java 11 instead of Java 8, but there seems to be no difference.

**Comment by epragtbeamtree** [comment]
I think the issue is happening because the code thinks that "junit.xml" is supposed to be a directory. If I replace the 

`new FileOutputStream(file)` by `new FileOutputStream(new File(file.getParentFile().getAbsoluteFile(), file.getName()))`, the code seems to work.
