### ISSUE TITLE
[Kotlin] @BeforeAll and @AfterAll throws exceptions when used in kotlin

### ISSUE THREAD

**Issue by ocherniavskyi-lohika-tix** [cucumber/cucumber-jvm#2428]
**Describe the bug**
 @BeforeAll and @AfterAll throws exceptions when used in kotlin

**To Reproduce**
```
class MyStepDefinitions  {

    companion object {

        @JvmStatic
        @BeforeAll
        fun beforeAll() {
            println("before all")
        }

        @JvmStatic
        @AfterAll
        fun afterAll() {
            println("after all")
        }
    }

    //some steps declaration
```

Throws exception:
```

Before All/After All failed
io.cucumber.core.exception.CompositeCucumberException: There were 2 exceptions. The details are in the stacktrace below.
	at io.cucumber.core.runtime.RethrowingThrowableCollector.getThrowable(RethrowingThrowableCollector.java:57)
	at io.cucumber.core.runtime.CucumberExecutionContext.getThrowable(CucumberExecutionContext.java:81)
	at io.cucumber.core.runtime.CucumberExecutionContext.finishTestRun(CucumberExecutionContext.java:76)
	at io.cucumber.core.runtime.Runtime.execute(Runtime.java:94)
	at io.cucumber.core.runtime.Runtime.run(Runtime.java:85)
	at io.cucumber.core.cli.Main.run(Main.java:87)
	at io.cucumber.core.cli.Main.main(Main.java:30)
	Suppressed: io.cucumber.java.InvalidMethodSignatureException: A method annotated with BeforeAll or AfterAll must have one of these signatures:
 * public static void before_or_after_all()
at void com.lohika.cucumber.MyStepDefinitionsMethod$Companion.beforeAll()


		at io.cucumber.java.InvalidMethodSignatureException$InvalidMethodSignatureExceptionBuilder.build(InvalidMethodSignatureException.java:52)
		at io.cucumber.java.JavaStaticHookDefinition.createInvalidSignatureException(JavaStaticHookDefinition.java:44)
		at io.cucumber.java.JavaStaticHookDefinition.requireValidMethod(JavaStaticHookDefinition.java:28)
		at io.cucumber.java.JavaStaticHookDefinition.<init>(JavaStaticHookDefinition.java:17)
		at io.cucumber.java.GlueAdaptor.addDefinition(GlueAdaptor.java:30)
		at io.cucumber.java.JavaBackend.lambda$loadGlue$1(JavaBackend.java:42)
		at io.cucumber.java.MethodScanner.scan(MethodScanner.java:67)
		at io.cucumber.java.MethodScanner.scan(MethodScanner.java:58)
		at io.cucumber.java.MethodScanner.scan(MethodScanner.java:33)
		at io.cucumber.java.JavaBackend.lambda$loadGlue$2(JavaBackend.java:40)
		at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
		at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
		at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
		at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
		at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
		at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
		at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
		at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
		at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
		at io.cucumber.java.JavaBackend.loadGlue(JavaBackend.java:40)
		at io.cucumber.core.runner.Runner.<init>(Runner.java:56)
		at io.cucumber.core.runtime.SingletonRunnerSupplier.createRunner(SingletonRunnerSupplier.java:44)
		at io.cucumber.core.runtime.SingletonRunnerSupplier.get(SingletonRunnerSupplier.java:35)
		at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:35)
		at io.cucumber.core.runtime.CucumberExecutionContext.getRunner(CucumberExecutionContext.java:114)
		at io.cucumber.core.runtime.CucumberExecutionContext.runBeforeAllHooks(CucumberExecutionContext.java:65)
		at io.cucumber.core.runtime.Runtime.lambda$run$0(Runtime.java:81)
		at io.cucumber.core.runtime.Runtime.execute(Runtime.java:94)
		at io.cucumber.core.runtime.Runtime.run(Runtime.java:80)
		... 2 more
	Suppressed: io.cucumber.java.InvalidMethodSignatureException: A method annotated with BeforeAll or AfterAll must have one of these signatures:
 * public static void before_or_after_all()
at void com.lohika.cucumber.MyStepDefinitionsMethod$Companion.beforeAll()


		at io.cucumber.java.InvalidMethodSignatureException$InvalidMethodSignatureExceptionBuilder.build(InvalidMethodSignatureException.java:52)
		at io.cucumber.java.JavaStaticHookDefinition.createInvalidSignatureException(JavaStaticHookDefinition.java:44)
		at io.cucumber.java.JavaStaticHookDefinition.requireValidMethod(JavaStaticHookDefinition.java:28)
		at io.cucumber.java.JavaStaticHookDefinition.<init>(JavaStaticHookDefinition.java:17)
		at io.cucumber.java.GlueAdaptor.addDefinition(GlueAdaptor.java:30)
		at io.cucumber.java.JavaBackend.lambda$loadGlue$1(JavaBackend.java:42)
		at io.cucumber.java.MethodScanner.scan(MethodScanner.java:67)
		at io.cucumber.java.MethodScanner.scan(MethodScanner.java:58)
		at io.cucumber.java.MethodScanner.scan(MethodScanner.java:33)
		at io.cucumber.java.JavaBackend.lambda$loadGlue$2(JavaBackend.java:40)
		at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
		at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
		at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
		at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:274)
		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
		at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
		at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
		at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
		at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
		at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
		at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
		at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
		at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
		at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
		at io.cucumber.java.JavaBackend.loadGlue(JavaBackend.java:40)
		at io.cucumber.core.runner.Runner.<init>(Runner.java:56)
		at io.cucumber.core.runtime.SingletonRunnerSupplier.createRunner(SingletonRunnerSupplier.java:44)
		at io.cucumber.core.runtime.SingletonRunnerSupplier.get(SingletonRunnerSupplier.java:35)
		at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:35)
		at io.cucumber.core.runtime.CucumberExecutionContext.getRunner(CucumberExecutionContext.java:114)
		at io.cucumber.core.runtime.CucumberExecutionContext.runAfterAllHooks(CucumberExecutionContext.java:70)
		at io.cucumber.core.runtime.Runtime.execute(Runtime.java:94)
		at io.cucumber.core.runtime.Runtime.run(Runtime.java:84)
		... 2 more
```

**Your Environment**
 - Versions used 7.1.0

**Comment by mpkorstanje** [comment]
You have to use [package level functions](https://kotlinlang.org/docs/java-to-kotlin-interop.html#package-level-functions). For example:

```kotlin
package io.cucumber.example

import io.cucumber.java.AfterAll
import io.cucumber.java.BeforeAll

@BeforeAll
fun beforeAll() {
    println("before all")
}

@AfterAll
fun afterAll() {
    println("after all")
}
```

When using a companion object, Kotlin will create an class `MyStepDefinitionsMethod$Companion` which has non-static methods. [The `@JvmStatic` annotation does not prevent this, it only adds the static methods to `MyStepDefinitionsMethod`](https://kotlinlang.org/docs/java-to-kotlin-interop.html#static-methods).As a result Cucumber will detect both the static method ons `MyStepDefinitions` as well as the non-static methods on `MyStepDefinitions$Companion` and complain about the second one.

**Comment by ocherniavskyi-lohika-tix** [comment]
@mpkorstanje thanks a lot, could you be added to docs?

**Comment by mpkorstanje** [comment]
They're kept here, feel free to send a pull request.

https://github.com/cucumber/docs
