### ISSUE TITLE
Remove DeltaSpike

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-jvm#2650]
### 👓 What did you see?

When building `cucumber-jvm` with Java 17 using `mvn clean install`:

```
Exception 0 :
org.jboss.weld.exceptions.WeldException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @62bd2070
        at org.jboss.weld.bean.proxy.ProxyFactory.getProxyClass(ProxyFactory.java:294)
        at org.jboss.weld.bean.proxy.ProxyFactory.create(ProxyFactory.java:248)
```

Upgrading Weld to the latest supported by `deltaspike-cdictrl-api` results in:

```
Nov 27, 2022 7:04:28 PM org.jboss.weld.bootstrap.WeldStartup <clinit>
INFO: WELD-000900: 3.1.3 (Final)

java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @704d6e83

	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297)
	at java.base/java.lang.reflect.Method.checkCanSetAccessible(Method.java:199)
	at java.base/java.lang.reflect.Method.setAccessible(Method.java:193)
	at org.jboss.weld.util.bytecode.ClassFileUtils$1.run(ClassFileUtils.java:88)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at org.jboss.weld.util.bytecode.ClassFileUtils.makeClassLoaderMethodsAccessible(ClassFileUtils.java:64)
```	

### 📚 Any additional context?

This is currently blocking the use of Java 17 to build the project which is required for https://github.com/cucumber/cucumber-jvm/pull/2644.

**Comment by mpkorstanje** [comment]
@toepi you once contributed this implementation in https://github.com/cucumber/cucumber-jvm/pull/1616. Can you confirm that there currently is no viable way to use DeltaSpike on Java 17?

**Comment by mpkorstanje** [comment]
Decided to deprecate Delta Spike.

**Comment by mpkorstanje** [comment]
Looks like it can be made to work.
