### ISSUE TITLE
Mocking a Supplier<>-Bean

### ISSUE THREAD

**Issue by MrGung** [cucumber/cucumber-jvm#2656]
### 👓 What did you see?

I would like a Bean that is defined like so

    @Bean("idGenerator")
    public Supplier<UUID> idGenerator() {
      return () -> UUID.randomUUID();
    }

and injected with

    @Autowired
    @SpyBean
    @Qualifier("NotificationIdGeneratorFunction")
    private Supplier<UUID> notificationIdGenerator;

to be mocked/spied by

    doReturn(UUID.fromString(string)).when(idGeneratorInstance).get();

But I get an error indicating, that that Bean cannot be mocked.

Here is the stacktrace I am getting:

    Before All/After All failed
    io.cucumber.core.exception.CompositeCucumberException: There were 15 exceptions. The details are in the stacktrace below.
    	at io.cucumber.core.runtime.RethrowingThrowableCollector.getThrowable(RethrowingThrowableCollector.java:57)
    	at io.cucumber.core.runtime.CucumberExecutionContext.getThrowable(CucumberExecutionContext.java:102)
    	at io.cucumber.core.runtime.CucumberExecutionContext.finishTestRun(CucumberExecutionContext.java:97)
    	at io.cucumber.core.runtime.Runtime.execute(Runtime.java:96)
    	at io.cucumber.core.runtime.Runtime.run(Runtime.java:87)
    	at io.cucumber.core.cli.Main.run(Main.java:87)
    	at io.cucumber.core.cli.Main.main(Main.java:30)
    	Suppressed: java.lang.IllegalStateException: Failed to load ApplicationContext
    		at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:98)
    		at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:124)
    		at io.cucumber.spring.TestContextAdaptor.<init>(TestContextAdaptor.java:32)
    		at io.cucumber.spring.SpringFactory.start(SpringFactory.java:120)
    		at io.cucumber.core.runner.Runner.buildBackendWorlds(Runner.java:134)
    [...]
    	Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name [...]: Unsatisfied dependency expressed through constructor parameter 5: Initialization of bean failed; 
        nested exception is org.mockito.exceptions.base.MockitoException: 
    Cannot mock/spy class BackendApplicationConfiguration$$Lambda$1713/0x00000008018fd980
    Mockito cannot mock/spy because :
     - VM does not support modification of given type
    		at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
    		at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)

### ✅ What did you expect to see?

The supplier being mocked, especially something like 

`doReturn(UUID.fromString(string)).when(idGeneratorInstance).get();`

should work.

### 📦 Which tool/library version are you using?

cucumber-bom 7.9.0; mockito 4.5.1; junit 5.8.2

### 🔬 How could we reproduce it?

Sorry, cannot provide a repo currently.

### 📚 Any additional context?

----
 
*This text was originally generated from a [template](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/about-issue-and-pull-request-templates), then edited by hand. [You can modify the template here.](https://github.com/cucumber/.github/edit/main/.github/ISSUE_TEMPLATE/bug_report.md)*

**Comment by sashokbg** [comment]
Hello, @MrGung, are you using junit 5 ? It might be related to #2654.
It seems fields annotated with @MockBean and @SpyBean annotations are not injected. There is a PR opened that addresses this issue, could you please check it out and try to see if it fixes your problem ?

https://github.com/cucumber/cucumber-jvm/pull/2655

To test it checkout my branch, do 

        mvn clean install -pl :cucumber-spring,:cucumber-bom -am" 

and then in your pom.xml 

        <dependency>
            <groupId>io.cucumber</groupId>
            <artifactId>cucumber-spring</artifactId>
            <version>7.10.0-SNAPSHOT</version>
        </dependency>

**Comment by sashokbg** [comment]
As a temporary solution what you can do is just use plain old spring and create a produced method that returns a Mockito.spy() or Mockito.mock() instance.

... In your test spring config

```
@Bean
public MyClass mySpy() {
  return Mockito.spy(new mySpy())
}
```

... In your test class

`@Autowired   // <-- not that we use classic spring and no mockito annotations`
MyClass mySpy;

**Comment by MrGung** [comment]
Since we are using `@SpyBean` successfully on several other dependencies - it does not seem to be a general problem. I do remember we switched from `MockBean` to `SpyBean` because they wouldn't get mocked several weeks ago, though.

I will try 7.10.0-SNAPSHOT and report back.

**Comment by MrGung** [comment]
Seems I cannot access the snapshot (corporate firewall). I'll try the workaround.

**Comment by mpkorstanje** [comment]
We don't publish snapshots. You will have to build locally.
