### ISSUE TITLE
[JUnit] exception swallowed while running cucumber

### ISSUE THREAD

**Issue by ank1006** [cucumber/cucumber-jvm#2694]
I keep running into following exceptions while executing cucumber test runner file as Junit-
java.lang.NoClassDefFoundError: org/junit/runner/manipulation/Filter
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.loadTestLoaderClass(RemoteTestRunner.java:380)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.createRawTestLoader(RemoteTestRunner.java:370)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.createLoader(RemoteTestRunner.java:365)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.defaultInit(RemoteTestRunner.java:309)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.init(RemoteTestRunner.java:224)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:208)
Caused by: java.lang.ClassNotFoundException: org.junit.runner.manipulation.Filter
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 8 more

Referenced Libraries-
![image](https://user-images.githubusercontent.com/47805449/221069061-f2e1737c-3b72-4d6a-be5c-c6e3edf83e7d.png)

**Comment by mpkorstanje** [comment]
Interesting. Looks like Cucumber got an exception before `testRunStarted` got called. 

Could you put some breakpoints here https://github.com/cucumber/cucumber-jvm/blob/main/cucumber-junit/src/main/java/io/cucumber/junit/Cucumber.java#L227 and follow the execution with a debugger?

**Comment by mpkorstanje** [comment]
I do see that you are using `cucumber-jvm-deps.jar` as a dependency. This suggests you are either manually managing your dependencies or including transitive depencies in your dependency management tool.

So in all likely hood the exception before `testRunStarted` is related to missing depencies.

Consider using Maven or Gradle and if you are remove the transitive depencies. You can find a minimal working example here: https://github.com/cucumber/cucumber-java-skeleton

I'll leave this issue open as a reminder to remove the `try-finally` so future exceptions won't be swallowed.
