### ISSUE TITLE
Unit test PluginFactoryTest fails on Windows due to incorrect teardown

### ISSUE THREAD

**Issue by jkronegg** [cucumber/cucumber-jvm#2700]
### 👓 What did you see?

When I run tests from `PluginFactoryTest` (in `cucumber-core`) on Windows 11/Java 17, the following tests fails:

- cant_create_plugin_when_parent_directory_is_a_file()
- instantiates_junit_plugin_with_file_arg()

In both case, the error is:

  ```
java.io.IOException: Failed to delete temp directory C:\Users\xxx\AppData\Local\Temp\junit14942009852397833759. The following paths could not be deleted (see suppressed exceptions for details): , target, target\cucumber
	    at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.createIOExceptionWithAttachedFailures(TempDirectory.java:350)
	    at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.close(TempDirectory.java:251)
	    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	    at org.junit.jupiter.engine.execution.ExtensionValuesStore.lambda$closeAllStoredCloseableValues$3(ExtensionValuesStore.java:68)
	    at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	    at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	    at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	    at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
            ...
	    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$cleanUp$10(NodeTestTask.java:167)
	    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	    at org.junit.platform.engine.support.hierarchical.NodeTestTask.cleanUp(NodeTestTask.java:167)
	    at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:98)
	    at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	    at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	    at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	    at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	    at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	    at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	    at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	    at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	    at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	    at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	    at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	    at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	    at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	    at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	    at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	    at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	    at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	    at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	    at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	    at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	    at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	    at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	    at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	    at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
	    at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	    at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	    at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	    at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	    at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
	    Suppressed: java.nio.file.DirectoryNotEmptyException: C:\Users\xxx\AppData\Local\Temp\junit14942009852397833759
		    at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:272)
		    at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
		    at java.base/java.nio.file.Files.delete(Files.java:1152)
		    at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.deleteAndContinue(TempDirectory.java:293)
		    at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.postVisitDirectory(TempDirectory.java:288)
		    at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.postVisitDirectory(TempDirectory.java:264)
		    at java.base/java.nio.file.Files.walkFileTree(Files.java:2828)
		    at java.base/java.nio.file.Files.walkFileTree(Files.java:2882)
		    at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.deleteAllFilesAndDirectories(TempDirectory.java:264)
		    at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.close(TempDirectory.java:249)
		    ... 64 more
	    Suppressed: java.nio.file.DirectoryNotEmptyException: C:\Users\xxx\AppData\Local\Temp\junit14942009852397833759\target
		    at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:272)
		    at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
		    at java.base/java.nio.file.Files.delete(Files.java:1152)
		    at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.deleteAndContinue(TempDirectory.java:293)
		    at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.postVisitDirectory(TempDirectory.java:288)
		    at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.postVisitDirectory(TempDirectory.java:264)
		    at java.base/java.nio.file.Files.walkFileTree(Files.java:2828)
		    at java.base/java.nio.file.Files.walkFileTree(Files.java:2882)
		    at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.deleteAllFilesAndDirectories(TempDirectory.java:264)
		    at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.close(TempDirectory.java:249)
		    ... 64 more
	    Suppressed: java.nio.file.DirectoryNotEmptyException: C:\Users\xxx\AppData\Local\Temp\junit14942009852397833759\target\cucumber
		    at java.base/sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:272)
		    at java.base/sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:105)
		    at java.base/java.nio.file.Files.delete(Files.java:1152)
		    at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.deleteAndContinue(TempDirectory.java:293)
		    at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.postVisitDirectory(TempDirectory.java:288)
		    at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath$1.postVisitDirectory(TempDirectory.java:264)
		    at java.base/java.nio.file.Files.walkFileTree(Files.java:2828)
		    at java.base/java.nio.file.Files.walkFileTree(Files.java:2882)
		    at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.deleteAllFilesAndDirectories(TempDirectory.java:264)
		    at org.junit.jupiter.engine.extension.TempDirectory$CloseablePath.close(TempDirectory.java:249)
		    ... 64 more
```

The root cause is that the file cannot be deleted because it was not closed:

    java.nio.file.FileSystemException: C:\Users\xxx\AppData\Local\Temp\junit14942009852397833759\target\cucumber\reports: The process cannot access the file because it is being used by another process

I suspect this is because the `@AfterEach` is not properly implemented for plugins that manage `Envelope`: the `FakeTestRunEventsPublisher` is able to register handler for `TestRunStarted`, `TestRunFinished`, but not handler of `Envelope`. Thus, the `InputStream` which is opened in the plugin constructor may stay open (e.g. `JUnitFormatter`).

### ✅ What did you expect to see?

The tests are expected to run without errors on Windows (I suspect that they run properly on Unix systems).

### 📦 Which tool/library version are you using?

`7.11.2-SNAPSHOT` (main branch from 09.03.2023)

### 🔬 How could we reproduce it?

1. Get the latest `cucumber-jvm` repo on `main` branch on Windows
2. Run the `PluginFactoryTest` tests
3. see the two tests in error.

### 📚 Any additional context?

None

**Comment by mpkorstanje** [comment]
Cheers!
