### ISSUE TITLE
ConnectionFailedException

### ISSUE THREAD

**Issue by ashwinth28** [cucumber/cucumber-jvm#2717]
**Requesting for Help to Resolve**
### ![Screenshot (4)](https://user-images.githubusercontent.com/125036948/228451781-e1ca9010-9b96-4f36-bb28-da56d5c6a66c.png)
31morg.openqa.selenium.remote.http.ConnectionFailedException: Unable to establish websocket connection to http://localhost:61621/devtools/browser/d41e9d02-aed5-4ca0-9a0e-e5ae438bc2d1
Build info: version: '4.5.0', revision: 'fe167b119a'
System info: os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '17.0.5'
Driver info: driver.version: ChromeDriver
	at org.openqa.selenium.remote.http.netty.NettyWebSocket.<init>(NettyWebSocket.java:102)
	at org.openqa.selenium.remote.http.netty.NettyWebSocket.lambda$create$3(NettyWebSocket.java:128)
	at org.openqa.selenium.remote.http.netty.NettyClient.openSocket(NettyClient.java:107)
	at org.openqa.selenium.devtools.Connection.<init>(Connection.java:77)
	at org.openqa.selenium.chromium.ChromiumDriver.lambda$new$2(ChromiumDriver.java:116)
	at java.base/java.util.Optional.map(Optional.java:260)
	at org.openqa.selenium.chromium.ChromiumDriver.<init>(ChromiumDriver.java:114)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:81)
	at org.openqa.selenium.chrome.ChromeDriver.<init>(ChromeDriver.java:49)
	at org.steps.LoginSteps.user_on_the_login_page(LoginSteps.java:30)
	at ✽.User on the login page(file:src/test/resources/Feature/Facebook.feature:25)

**Comment by mlvandijk** [comment]
Hi @ashwinth28,
Please use the [support](https://cucumber.io/support) forums for questions and discussions. We'll be happy to help you there. We use GitHub issues to track bugs and contributions exclusively.

**Comment by mpkorstanje** [comment]
And to add a little bit to that. The problem you're having isn't with Cucumber but rather with Selenium. You may have more luck asking there.

**Comment by ashwinth28** [comment]
Thank you Mr.@mpkorstanje 🙂
