### ISSUE TITLE
Cucumber TestRunner » NoClassDefFound javax/lang/model/SourceVersion

### ISSUE THREAD

**Issue by JonnyDaBullet** [cucumber/cucumber-jvm#2791]
Hello.

I trying to executing test on Intellij 2022.2.5 using Maven with Cucumber 7.0.0 but its giving an error. I don't understand why. My java jdk version is java 18.0.2.1 2022-08-18

```
 io.cucumber.core.exception.CompositeCucumberException: There were 2 exceptions. The details are in the stacktrace below.
    at io.cucumber.core.runtime.RethrowingThrowableCollector.getThrowable(RethrowingThrowableCollector.java:57)
    at io.cucumber.core.runtime.CucumberExecutionContext.getThrowable(CucumberExecutionContext.java:81)
    at io.cucumber.core.runtime.CucumberExecutionContext.finishTestRun(CucumberExecutionContext.java:76)
    at io.cucumber.junit.Cucumber$FinishTestRun.evaluate(Cucumber.java:250)
    at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
    at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
    at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
    at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
    at java.base/java.lang.reflect.Method.invoke(Method.java:577)
    at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray2(ReflectionUtils.java:202)
    at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:158)
    at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:81)
    at org.apache.maven.plugin.surefire.InPluginVMSurefireStarter.runSuitesInProcess(InPluginVMSurefireStarter.java:84)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1060)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:907)
    at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:785)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
    at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
    at java.base/java.lang.reflect.Method.invoke(Method.java:577)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
    at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
    Suppressed: java.lang.NoClassDefFoundError: javax/lang/model/SourceVersion
        at io.cucumber.core.resource.ClasspathSupport.requireValidPackageName(ClasspathSupport.java:41)
        at io.cucumber.core.resource.ClasspathScanner.scanForClassesInPackage(ClasspathScanner.java:49)
        at io.cucumber.core.resource.ClasspathScanner.scanForClassesInPackage(ClasspathScanner.java:115)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at io.cucumber.java.JavaBackend.loadGlue(JavaBackend.java:40)
        at io.cucumber.core.runner.Runner.<init>(Runner.java:56)
        at io.cucumber.core.runtime.ThreadLocalRunnerSupplier.createRunner(ThreadLocalRunnerSupplier.java:47)
        at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
        at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
        at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
        at io.cucumber.core.runtime.ThreadLocalRunnerSupplier.get(ThreadLocalRunnerSupplier.java:40)
        at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:35)
        at io.cucumber.core.runtime.CucumberExecutionContext.getRunner(CucumberExecutionContext.java:114)
        at io.cucumber.core.runtime.CucumberExecutionContext.runBeforeAllHooks(CucumberExecutionContext.java:65)
        at io.cucumber.junit.Cucumber$RunBeforeAllHooks.evaluate(Cucumber.java:265)
        at io.cucumber.junit.Cucumber$RunAfterAllHooks.evaluate(Cucumber.java:281)
        at io.cucumber.junit.Cucumber$StartTestRun.evaluate(Cucumber.java:233)
        at io.cucumber.junit.Cucumber$FinishTestRun.evaluate(Cucumber.java:248)
        ... 38 more
    **Caused by: java.lang.ClassNotFoundException: javax.lang.model.SourceVersion**
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        at org.apache.maven.surefire.booter.IsolatedClassLoader.loadClass(IsolatedClassLoader.java:98)
        ... 65 more
    Suppressed: java.lang.NoClassDefFoundError: javax/lang/model/SourceVersion
        at io.cucumber.core.resource.ClasspathSupport.requireValidPackageName(ClasspathSupport.java:41)
        at io.cucumber.core.resource.ClasspathScanner.scanForClassesInPackage(ClasspathScanner.java:49)
        at io.cucumber.core.resource.ClasspathScanner.scanForClassesInPackage(ClasspathScanner.java:115)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
        at io.cucumber.java.JavaBackend.loadGlue(JavaBackend.java:40)
        at io.cucumber.core.runner.Runner.<init>(Runner.java:56)
        at io.cucumber.core.runtime.ThreadLocalRunnerSupplier.createRunner(ThreadLocalRunnerSupplier.java:47)
        at java.base/java.lang.ThreadLocal$SuppliedThreadLocal.initialValue(ThreadLocal.java:305)
        at java.base/java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:195)
        at java.base/java.lang.ThreadLocal.get(ThreadLocal.java:172)
        at io.cucumber.core.runtime.ThreadLocalRunnerSupplier.get(ThreadLocalRunnerSupplier.java:40)
        at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:35)
        at io.cucumber.core.runtime.CucumberExecutionContext.getRunner(CucumberExecutionContext.java:114)
        at io.cucumber.core.runtime.CucumberExecutionContext.runAfterAllHooks(CucumberExecutionContext.java:70)
        at io.cucumber.junit.Cucumber$RunAfterAllHooks.evaluate(Cucumber.java:283)
        at io.cucumber.junit.Cucumber$StartTestRun.evaluate(Cucumber.java:233)
        at io.cucumber.junit.Cucumber$FinishTestRun.evaluate(Cucumber.java:248)`
```
I already change versions do some updating on pom.xml but i dont't understand why this is my dependencies versions:

```
<properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <cucumber.version>7.0.0</cucumber.version>
        <selenium-java.version>4.12.0</selenium-java.version>
        <commons-io.version>2.13.0</commons-io.version>
        <junit.version>4.13.2</junit.version>
        <log4j.version>1.2.17</log4j.version>
        <log4j-core.version>2.20.0</log4j-core.version>
        <log4j-api.version>2.20.0</log4j-api.version>
        <slf4j-reload4j.version>2.0.7</slf4j-reload4j.version>
        <slf4j-api.version>2.0.7</slf4j-api.version>
        <json-simple.version>1.1.1</json-simple.version>
        <json-lib.version>2.4</json-lib.version>
        <rest-assured.version>2.9.0</rest-assured.version>
        <groovy-all.version>2.3.5</groovy-all.version>
        <javaee-web-api.version>6.0</javaee-web-api.version>
        <unirest-java.version>1.4.9</unirest-java.version>
        <jtwig-core.version>5.87.0.RELEASE</jtwig-core.version>
        <httpclient.version>4.5.14</httpclient.version>
        <httpasyncclient.version>4.0.2</httpasyncclient.version>
        <httpmime.version>4.3.6</httpmime.version>
        <json.version>20230618</json.version>
        <jackson-core.version>2.10.0.pr1</jackson-core.version>
        <jackson-databind.version>2.10.0.pr1</jackson-databind.version>
        <asciidoctorj-pdf.version>1.5.0-alpha.16</asciidoctorj-pdf.version>
        <gson.version>2.8.5</gson.version>
        <google-guava.version>32.0.1-jre</google-guava.version>
        <poi-ooxml.version>4.1.2</poi-ooxml.version>
        <pdfbox.version>2.0.29</pdfbox.version>
        <opencsv.version>5.5.2</opencsv.version>
        <properties-maven-plugin.version>1.2.0</properties-maven-plugin.version>
        <maven-compiler-plugin.version>3.11.0</maven-compiler-plugin.version>
        <maven-surefire-plugin.version>2.20</maven-surefire-plugin.version>
        <maven-failsafe-plugin.version>3.1.2</maven-failsafe-plugin.version>
        <maven-resources-plugin.version>3.3.1</maven-resources-plugin.version>
        <maven-cucumber-reporting.version>2.8.0</maven-cucumber-reporting.version>
        <cukedoctor-maven-plugin.version>3.9.0</cukedoctor-maven-plugin.version>
        <jruby-complete.version>9.2.7.0</jruby-complete.version>
    </properties>
```
Thank you for your help really. Best regards.

**Comment by mpkorstanje** [comment]
Best I can tell you is to start over with the `cucumber-java-skeleton` and then build up step by step until you can reproduce your problem in a more controlled scenario.

https://github.com/cucumber/cucumber-java-skeleton/

That said, since the class that couldn't be found is part of the JDK, it might also be worth trying a different JDK with an LTS version.
