### ISSUE TITLE
@DataTableType is not picked up by Cucumber

### ISSUE THREAD

**Issue by Pancor** [cucumber/cucumber-jvm#2802]
### 👓 What did you see?

I'm having trouble with using `@DataTableType` for converting a `String`.  Defined `@DataTableTyple` like this:
```java
@DataTableType
public Permission permissionDataTableType(String permission) {
    return Permission.of(permission);
}
```
is never called before step to transform `String` to `Permission`.  Cucumbers seams not to pick up this `@DataTableType` and tries to convert `String` to `Permission` by itself with throwing an error:

<details>

<summary>Error log</summary>

```java
When user receives PERMISSION_ONE       # com.pancordev.Steps.user_receives(com.pancordev.Permission)
    io.cucumber.core.exception.CucumberException: Could not convert arguments for step [^user receives (.*)$] defined at 'com.pancordev.Steps.user_receives(com.pancordev.Permission)'.
      at io.cucumber.core.runner.PickleStepDefinitionMatch.couldNotConvertArguments(PickleStepDefinitionMatch.java:112)
      at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:56)
      at io.cucumber.core.runner.ExecutionMode$1.execute(ExecutionMode.java:10)
      at io.cucumber.core.runner.TestStep.executeStep(TestStep.java:84)
      at io.cucumber.core.runner.TestStep.run(TestStep.java:56)
      at io.cucumber.core.runner.PickleStepTestStep.run(PickleStepTestStep.java:51)
      at io.cucumber.core.runner.TestCase.run(TestCase.java:84)
      at io.cucumber.core.runner.Runner.runPickle(Runner.java:75)
      at io.cucumber.core.runtime.Runtime.lambda$executePickle$6(Runtime.java:107)
      at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runTestCase$5(CucumberExecutionContext.java:137)
      at io.cucumber.core.runtime.RethrowingThrowableCollector.executeAndThrow(RethrowingThrowableCollector.java:23)
      at io.cucumber.core.runtime.CucumberExecutionContext.runTestCase(CucumberExecutionContext.java:137)
      at io.cucumber.core.runtime.Runtime.lambda$executePickle$7(Runtime.java:107)
      at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
      at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
      at io.cucumber.core.runtime.Runtime$SameThreadExecutorService.execute(Runtime.java:235)
      at java.base/java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:123)
      at io.cucumber.core.runtime.Runtime.lambda$runFeatures$3(Runtime.java:89)
      at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
      at java.base/java.util.stream.SliceOps$1$1.accept(SliceOps.java:200)
      at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
      at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
      at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
      at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
      at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
      at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
      at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
      at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
      at io.cucumber.core.runtime.Runtime.runFeatures(Runtime.java:90)
      at io.cucumber.core.runtime.Runtime.lambda$run$0(Runtime.java:78)
      at io.cucumber.core.runtime.CucumberExecutionContext.lambda$runFeatures$6(CucumberExecutionContext.java:148)
      at io.cucumber.core.runtime.CucumberExecutionContext.execute(CucumberExecutionContext.java:163)
      at io.cucumber.core.runtime.CucumberExecutionContext.runFeatures(CucumberExecutionContext.java:146)
      at io.cucumber.core.runtime.Runtime.run(Runtime.java:78)
      at io.cucumber.core.cli.Main.run(Main.java:87)
      at io.cucumber.core.cli.Main.main(Main.java:30)
Caused by: io.cucumber.cucumberexpressions.CucumberExpressionException: ParameterType {anonymous} failed to transform [PERMISSION_ONE] to interface com.pancordev.Permission
      at io.cucumber.cucumberexpressions.ParameterType.transform(ParameterType.java:264)
      at io.cucumber.cucumberexpressions.Argument.getValue(Argument.java:42)
      at io.cucumber.core.stepexpression.ExpressionArgument.getValue(ExpressionArgument.java:17)
      at io.cucumber.core.runner.PickleStepDefinitionMatch.runStep(PickleStepDefinitionMatch.java:47)
      ... 34 more
Caused by: java.lang.IllegalArgumentException: Can't transform 'PERMISSION_ONE' to interface com.pancordev.Permission
BuiltInParameterTransformer only supports a limited number of class types
Consider using a different object mapper or register a parameter type for interface com.pancordev.Permission
      at io.cucumber.cucumberexpressions.BuiltInParameterTransformer.createIllegalArgumentException(BuiltInParameterTransformer.java:120)
      at io.cucumber.cucumberexpressions.BuiltInParameterTransformer.doTransform(BuiltInParameterTransformer.java:99)
      at io.cucumber.cucumberexpressions.BuiltInParameterTransformer.transform(BuiltInParameterTransformer.java:22)
      at io.cucumber.cucumberexpressions.RegularExpression.lambda$match$0(RegularExpression.java:66)
      at io.cucumber.cucumberexpressions.ParameterType$TransformerAdaptor.transform(ParameterType.java:299)
      at io.cucumber.cucumberexpressions.ParameterType.transform(ParameterType.java:259)
      ... 37 more
```

</details>

### ✅ What did you expect to see?

I expect that Cucumber can pick up `@DataTableType` and properly use it to convert `String` to custom interface `Permission`.

### 📦 Which tool/library version are you using?

- cucumber-java:7:14:0
- cucumber-junit:7:14:0
- java 11.0.18

### 🔬 How could we reproduce it?

I prepared a project [here](https://github.com/Pancor/cucumber-datatypetable) where You can reproduce the problem. Just clone it and then use `./gradlew cucumberCli` to run tests. 

Scenario `Test @DataTableType annotation` is failing because it is using `@DataTableType`.

### 📚 Any additional context?

Currently for a workaround I see that I can use `@ParameterType` to accomplish the same result:
```java
@ParameterType(".*")
public Permission permission(String permission) {
    return Permission.of(permission);
}
```
but it would be preferable for me to also use `@DataTableType`.

**Comment by mpkorstanje** [comment]
You don't appear to be using a data table. Is that intentional?

**Comment by Pancor** [comment]
Yup, I'm assuming that I can use `@DataTableType` with just a `String` in `*.feature` files. Or am I missing something from docs and I'm not supposed to do that?

**Comment by mpkorstanje** [comment]
That's correct.

They're fundamentally different systems. Parameter types have a name and pattern, data tables types don't. So using one for the other won't work.

But you can annotate a single method multiple times.
