### ISSUE TITLE
cucumber junit5 engine + gradle doesn't support tests rerun

### ISSUE THREAD

**Issue by emaks** [cucumber/cucumber-jvm#2805]
I use cucumber with gradle and run tests with next configuration in build.gradle
```
dependencies {
    implementation group: 'io.cucumber', name: 'cucumber-junit-platform-engine', version: '7.14.0'
    ...
}
tasks {
    test {
        systemProperties(System.getProperties().sort())
        useJUnitPlatform {
            includeEngines("cucumber")
        }
        systemProperty("cucumber.plugin", "json:build/site/cucumber-report.json, rerun:build/site/failed_scenarios.txt")
        systemProperty("cucumber.features", System.getProperty("folder", "src/test/resources/features"))
        systemProperty("cucumber.glue", "...")
        ...
    }
}
```
Everting work fine when I just run tests. But if I get "build/site/failed_scenarios.txt" file with failed tests and try to rerun only failed tests with
`systemProperty("cucumber.features", "@build/site/failed_scenarios.txt")`
I get an error
```
org.gradle.api.internal.tasks.testing.TestSuiteExecutionException: Could not complete execution for Gradle Test Executor 7.
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:64)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
Caused by: org.junit.platform.commons.JUnitException: TestEngine with ID 'cucumber' failed to discover tests
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:160)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverSafely(EngineDiscoveryOrchestrator.java:134)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:80)
	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:110)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:119)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:94)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:89)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:62)
	... 18 more
Caused by: java.lang.IllegalArgumentException: path must exist: D:\tests\@build\site\failed_scenarios.txt
	at io.cucumber.core.resource.PathScanner.findResourcesForPath(PathScanner.java:49)
	at io.cucumber.core.resource.PathScanner.findResourcesForUri(PathScanner.java:31)
	at io.cucumber.core.resource.ResourceScanner.findResourcesForUri(ResourceScanner.java:61)
	at io.cucumber.core.resource.ResourceScanner.scanForResourcesUri(ResourceScanner.java:134)
	at io.cucumber.junit.platform.engine.FeatureResolver.resolveUri(FeatureResolver.java:231)
	at io.cucumber.junit.platform.engine.FeatureResolver.resolveFeatureWithLines(FeatureResolver.java:246)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at io.cucumber.junit.platform.engine.DiscoverySelectorResolver.resolve(DiscoverySelectorResolver.java:71)
	at io.cucumber.junit.platform.engine.DiscoverySelectorResolver.resolveSelectors(DiscoverySelectorResolver.java:48)
	at io.cucumber.junit.platform.engine.CucumberTestEngine.discover(CucumberTestEngine.java:43)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:152)
	... 28 more

```

with junit4 I used 
```
task serenityRerun(type: JavaExec) {
    dependsOn(testClasses)
    systemProperties(System.getProperties().sort())
    classpath = sourceSets["test"].runtimeClasspath
    mainClass = 'net.serenitybdd.cucumber.cli.Main'
    args = [
        '--glue', '...',
        '--plugin', '...',
        '@build/site/failed_scenarios.txt'
    ]
}
```

**Comment by emaks** [comment]
is there any way to rerun failed tests with junit5?

**Comment by mpkorstanje** [comment]
To rerun failed scenarios please review https://github.com/cucumber/cucumber-jvm/tree/main/cucumber-junit-platform-engine#rerunning-failed-scenarios.

**Comment by mpkorstanje** [comment]
While it would be possible to implement a JUnit Engine that executes `rerun.txt` files, the JUnit 5 Platform does not support ordering test engines. So there is no guarantee that such a `cucumber-rerun` engine will be invoked after the `cucumber` engine.

Additionally JUnit 5 somewhat implicitly expects that test execution does not change the tests that could be discovered. While it may be possible with the current state of Surefire and Gradle to ignore that, it could cause all sorts of janky behavior. More than I'm willing to accommodate for.

If this is a major impediment to you, I reckon that you or your company can either petition Gradle and/or Surefire for better JUnit 5 support or materially contribute in either way.

**Comment by mpkorstanje** [comment]
And the ordering problem could be solved by having multiple surefire executions. One for the run and a second for the rerun. Each targeting different suites.

**Comment by NicoIodice** [comment]
Just passing by see if there are any advances on this issue. 
Isn't still there a solution for this problem where junit reports are not stored for all reruns on a simplier way?

**Comment by mpkorstanje** [comment]
No, unfortunately the best way to rerun tests and preserve reports written by Cucumber is still to use the JUnit Platform Launcher with different configurations for the run and rerun.

As you are interested in seeing this resolved, would you be interested in contributing a solution?

**Comment by jonn-set** [comment]
> > That does leave the test engine ordering problem.
> 
> And the ordering problem could be solved by having multiple surefire executions. One for the run and a second for the rerun. Each targeting different suites. Still janky, but better than nothing.

I have this config, where the first run is run as part of `integration-test` phase and re-run in `post-integration-test`, I still see `TestEngine with ID 'junit-platform-suite' failed to discover tests.` I have separate Runner java files, one running everything and 2nd one only targeting the rerun file. Is this the same you suggesting here or am I doing something wrong here?

Thanks.

My plugin block looks like this:

```
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.2</version>
                <executions>
                    <execution>
                        <id>default-test</id>
                        <configuration>
                            <skip>true</skip>
                        </configuration>
                    </execution>
                    <execution>
                        <id>first-run</id>
                        <phase>integration-test</phase>
                        <goals>
                            <goal>test</goal>
                        </goals>
                        <configuration>
                            <includes>
                                <include>**/RunCukesAPITest.java</include>
                            </includes>
                            <excludes>
                                <exclude>**/RunCukesAPIRetest.java</exclude>
                            </excludes>
                            <skip>${skip.first-run}</skip>
                            <testFailureIgnore>true</testFailureIgnore>
                            <rerunFailingTestsCount>0</rerunFailingTestsCount>
                        </configuration>
                    </execution>
                    <execution>
                        <id>re-run</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>test</goal>
                        </goals>
                        <configuration>
                            <skip>${skip.re-run}</skip>
                            <includes>
                                <include>**/RunCukesAPIRetest.java</include>
                            </includes>
                            <excludes>
                                <exclude>**/RunCukesAPITest.java</exclude>
                            </excludes>
                            <testFailureIgnore>false</testFailureIgnore>
                            <rerunFailingTestsCount>0</rerunFailingTestsCount>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

**Comment by mpkorstanje** [comment]
Well suppose that you have a JUnit suite that selects the `rerun.txt`. 

```java
@Suite
@IncludeEngines("cucumber")
@SelectFile("path/to/rerun.txt")
@ConfigurationParameter(key = GLUE_PROPERTY_NAME, value = "com.example")
public class ReRunCucumberTest {
}
```

Then that will result in a file selector being resolved here:

https://github.com/cucumber/cucumber-jvm/blob/25dbfe5fa92575104480c8e1f0a114b98f8222fe/cucumber-junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/FeatureResolver.java#L132

You'd have to check if the file is a feature file or a rerun file. And in case of the latter parse it with `RerunPath`. The collection of `FeatureWithLines` can be transformed into `FeatureWithLinesSelector` and handed back to JUnit for further discovery.

Presumably you'll also want directories to work, so another `FileContainerSelectorResolver` would be needed here that works for `.txt` files.

https://github.com/cucumber/cucumber-jvm/blob/25dbfe5fa92575104480c8e1f0a114b98f8222fe/cucumber-junit-platform-engine/src/main/java/io/cucumber/junit/platform/engine/DiscoverySelectorResolver.java#L14-L16

Finally tests should be added to `CucumberTestEngineTest`.

**Comment by jonn-set** [comment]
Feels like a lot of effort :) but will try it out when I get time. Thanks

**Comment by mpkorstanje** [comment]
Great! Let me know if you run into any problems.

**Comment by chik145** [comment]
Hi @mpkorstanje 
any update on this issue ? we recently migrated our selenium project from unit 4. 
this feature is very much required to us. any support on this issue fix will be appreciated.

Thanks
