### ISSUE TITLE
7.20.0 regression: TestEngine with ID 'cucumber' failed to discover tests

### ISSUE THREAD

**Issue by murdos** [cucumber/cucumber-jvm#2930]
### 👓 What did you see?

Build of PR opened by renovate with new Cucumber version is failing: https://github.com/jhipster/jhipster-lite/pull/11057:
>  Error:  Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.5.0:test (default-test) on project jhlite: 
Error:  
Error:  Please refer to /home/runner/work/jhipster-lite/jhipster-lite/target/surefire-reports for the individual test results.
Error:  Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
Error: [ERROR] There was an error in the forked process
Error:  TestEngine with ID 'cucumber' failed to discover tests
Error:  org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
Error:  TestEngine with ID 'cucumber' failed to discover tests
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:628)
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:285)
Error:  	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:250)
Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1337)
Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1137)
Error:  	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:971)
Error:  	at com.gradle.maven.cache.extension.d.c.a(SourceFile:27)

### ✅ What did you expect to see?

Build running fine, as it was with 7.19.0

### 📦 Which tool/library version are you using?

cucumber-junit-platform-engine
cucumber-spring
maven-failsafe-plugin
gradle-develocity

### 📚 Any additional context?

Our cucumbers tests are executed with maven-failsafe-plugin, but here the error happens with the execution of maven-surefire-plugin

**Comment by mpkorstanje** [comment]
```shell
$ cat jhipster/jhipster-lite/target/surefire-reports/2024-10-05T16-15-25_011-jvmRun1.dump
# Created at 2024-10-05T16:15:26.116
org.junit.platform.commons.JUnitException: TestEngine with ID 'cucumber' failed to discover tests
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:160)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverSafely(EngineDiscoveryOrchestrator.java:132)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:78)
	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:99)
	at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:77)
	at org.junit.platform.launcher.core.DelegatingLauncher.discover(DelegatingLauncher.java:42)
	at org.apache.maven.surefire.junitplatform.LazyLauncher.discover(LazyLauncher.java:50)
	at org.apache.maven.surefire.junitplatform.TestPlanScannerFilter.accept(TestPlanScannerFilter.java:52)
	at org.apache.maven.surefire.api.util.DefaultScanResult.applyFilter(DefaultScanResult.java:87)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.scanClasspath(JUnitPlatformProvider.java:142)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:122)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
Caused by: java.util.ServiceConfigurationError: io.cucumber.core.eventbus.UuidGenerator: Provider io.cucumber.core.eventbus.IncrementingUuidGenerator could not be instantiated
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:586)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:813)
	at java.base/java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:729)
	at java.base/java.util.ServiceLoader$3.next(ServiceLoader.java:1403)
	at io.cucumber.core.runtime.UuidGeneratorServiceLoader.loadSingleUuidGeneratorOrDefault(UuidGeneratorServiceLoader.java:60)
	at io.cucumber.core.runtime.UuidGeneratorServiceLoader.loadUuidGenerator(UuidGeneratorServiceLoader.java:46)
	at io.cucumber.junit.platform.engine.FeatureResolver.createFeatureParser(FeatureResolver.java:69)
	at io.cucumber.junit.platform.engine.FeatureResolver.<init>(FeatureResolver.java:59)
	at io.cucumber.junit.platform.engine.FeatureResolver.create(FeatureResolver.java:78)
	at io.cucumber.junit.platform.engine.DiscoverySelectorResolver.resolve(DiscoverySelectorResolver.java:67)
	at io.cucumber.junit.platform.engine.DiscoverySelectorResolver.resolveSelectors(DiscoverySelectorResolver.java:53)
	at io.cucumber.junit.platform.engine.CucumberTestEngine.discover(CucumberTestEngine.java:47)
	at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:152)
	... 15 more
Caused by: io.cucumber.core.exception.CucumberException: Out of IncrementingUuidGenerator capacity. Please reuse existing instances or use another UuidGenerator implementation instead.
	at io.cucumber.core.eventbus.IncrementingUuidGenerator.<init>(IncrementingUuidGenerator.java:102)
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at java.base/java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:789)
	... 26 more
```

**Comment by mpkorstanje** [comment]
Cheers. Thanks for reporting this.

**Comment by BalRoger** [comment]
I am just starting with cucumber, after not having used it for a little over a decade.

I'm trying to run the "hellocucumber" [10-minute Tutorial](https://cucumber.io/docs/guides/10-minute-tutorial). After several false starts (need to specify versions on a lot of dependencies not versioned by archetype, etc.), I am still getting this failure, similar to the above:

### What do you expect to see?
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.5.2:test (default-test) on project hellocucumber: 
[ERROR] 
[ERROR] See /Users/b109202/projects/hellocucumber/target/surefire-reports for the individual test results.
[ERROR] See dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] There was an error in the forked process
[ERROR] TestEngine with ID 'cucumber' failed to discover tests
[ERROR] org.apache.maven.surefire.booter.SurefireBooterForkException: There was an error in the forked process
[ERROR] TestEngine with ID 'cucumber' failed to discover tests
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:628)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:285)
[ERROR] 	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:250)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1336)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:1134)
[ERROR] 	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:968)
[ERROR] 	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:328)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:316)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:174)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:75)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:162)
[ERROR] 	at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
[ERROR] 	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:159)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
[ERROR] 	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
[ERROR] 	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
[ERROR] 	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
[ERROR] 	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
[ERROR] 	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:906)
[ERROR] 	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:283)
[ERROR] 	at org.apache.maven.cli.MavenCli.main(MavenCli.java:206)
[ERROR] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:255)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:201)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:361)
[ERROR] 	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:314)
[ERROR] 	at org.codehaus.classworlds.Launcher.main(Launcher.java:41)
```

This is a first time tutorial usage, so if I'm doing something stupid, I'm happy to correct it. But on the off chance it's something more serious, I offer this comment.

### What do you expect to see?
The tutorial tells me I should see a successful maven test run.

### Which tool/library version are you using?

Runtime
- openjdk:17.0.15
- maven:3.9..10

Dependency mgmt:
- cucumber-bom:pom:7.23.0
- org.junit:junit-bom:pom:5.12.2
- org.assertj:assertj-bom:pom:3.27.3

Dependencies:
- cucumber-java:7.9.0
- cucumber-junit-platform-engine:7.9.0
- org.junit.platform:junit-platform-suite:1.9.3
- org.assertj:assertj-core:3.9.1
- org.apache.maven.surefire:surefire-junit-platform:3.5.2

Plugins:
- org.apache.maven.plugins:maven-compiler-plugin:3.12.1
- org.apache.maven.plugins:maven-surefire-plugin:3.5.2

All configured as built from archetype, with the addition/change of version numbers, as needed to build.

### How could we reproduce it?
Run the tutorial with my dependency and plugin settings?

### Any additional context?

```
% cat target/surefire-reports/2025-06-13T08-49-00_902-jvmRun1.dump
# Created at 2025-06-13T08:49:01.215
org.junit.platform.commons.JUnitException: TestEngine with ID 'cucumber' failed to discover tests
        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:165)
        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverSafely(EngineDiscoveryOrchestrator.java:132)
        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:105)
        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discover(EngineDiscoveryOrchestrator.java:78)
        at org.junit.platform.launcher.core.DefaultLauncher.discover(DefaultLauncher.java:99)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:85)
        at org.junit.platform.launcher.core.DelegatingLauncher.execute(DelegatingLauncher.java:47)
        at org.junit.platform.launcher.core.InterceptingLauncher.lambda$execute$1(InterceptingLauncher.java:39)
        at org.junit.platform.launcher.core.ClasspathAlignmentCheckingLauncherInterceptor.intercept(ClasspathAlignmentCheckingLauncherInterceptor.java:25)
        at org.junit.platform.launcher.core.InterceptingLauncher.execute(InterceptingLauncher.java:38)
        at org.junit.platform.launcher.core.DelegatingLauncher.execute(DelegatingLauncher.java:47)
        at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:56)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:184)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:148)
        at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:122)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)
Caused by: org.junit.platform.commons.JUnitException: Failed to transform configuration parameter with key 'cucumber.junit-platform.naming-strategy' and initial value 'surefire'
        at org.junit.platform.engine.ConfigurationParameters.lambda$get$0(ConfigurationParameters.java:129)
        at java.base/java.util.Optional.map(Optional.java:260)
        at org.junit.platform.engine.ConfigurationParameters.get(ConfigurationParameters.java:122)
        at io.cucumber.junit.platform.engine.CucumberEngineOptions.namingStrategy(CucumberEngineOptions.java:167)
        at io.cucumber.junit.platform.engine.FeatureResolver.<init>(FeatureResolver.java:59)
        at io.cucumber.junit.platform.engine.FeatureResolver.create(FeatureResolver.java:66)
        at io.cucumber.junit.platform.engine.DiscoverySelectorResolver.resolve(DiscoverySelectorResolver.java:62)
        at io.cucumber.junit.platform.engine.DiscoverySelectorResolver.resolveSelectors(DiscoverySelectorResolver.java:48)
        at io.cucumber.junit.platform.engine.CucumberTestEngine.discover(CucumberTestEngine.java:43)
        at org.junit.platform.launcher.core.EngineDiscoveryOrchestrator.discoverEngineRoot(EngineDiscoveryOrchestrator.java:152)
        ... 18 more
Caused by: java.lang.IllegalArgumentException: No enum constant io.cucumber.junit.platform.engine.DefaultNamingStrategy.SUREFIRE
        at java.base/java.lang.Enum.valueOf(Enum.java:293)
        at io.cucumber.junit.platform.engine.DefaultNamingStrategy.valueOf(DefaultNamingStrategy.java:8)
        at io.cucumber.junit.platform.engine.DefaultNamingStrategy.getStrategy(DefaultNamingStrategy.java:35)
        at org.junit.platform.engine.ConfigurationParameters.lambda$get$0(ConfigurationParameters.java:124)
        ... 27 more
```

**Comment by jkronegg** [comment]
I'm on my phone, so cannot investigate a lot... but it looks like you have a library conflict: cucumber-java and cucumber-junit-platform-engine should be the same version as cucumber-bom. Usually these libraries should be automatically picked by the cucumber-bom.

**Comment by mpkorstanje** [comment]
> After several false starts (need to specify versions on a lot of dependencies not versioned by archetype, etc.),

I think this is where things go wrong. The archetype includes all versions needed. You shouldn't add more versions and the versions you've added at a glance don't appear to be compatible.

**Comment by jkronegg** [comment]
@BalRoger I followed the [tutorial steps](https://cucumber.io/docs/guides/10-minute-tutorial/):
1. `cd /the_directory_where_you_store_your_projects` (in your case, it would be `/Users/b109202/projects/`)
2. generate the project: `mvn archetype:generate -DarchetypeGroupId=io.cucumber -DarchetypeArtifactId=cucumber-archetype -DarchetypeVersion=7.23.0 -DgroupId=hellocucumber -DartifactId=hellocucumber -Dpackage=hellocucumber -Dversion=1.0.0-SNAPSHOT -DinteractiveMode=false`
3. go to the generated project: `cd hellocucumber`
4. build the project: `mvn clean install`

Then the test runs and the build success:

```
[INFO] Running hellocucumber.RunCucumberTest

Scenario: The example                       # hellocucumber/example.feature:3
  Given an example scenario                 # hellocucumber.StepDefinitions.anExampleScenario()
  When all step definitions are implemented # hellocucumber.StepDefinitions.allStepDefinitionsAreImplemented()
  Then the scenario passes                  # hellocucumber.StepDefinitions.theScenarioPasses()
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.246 s -- in hellocucumber.RunCucumberTest
[INFO] 
[INFO] Results:
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO]
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  5.084 s
[INFO] Finished at: 2025-06-13T23:06:32+02:00
[INFO] ------------------------------------------------------------------------
```

The `mvn test` command also works. Note that I didn't changed the pom dependencies: everything runs well without any change. 
I don't understand why you changed the pom dependencies.
Can you redo the steps above and tell me whether the `mvn clean install` succeeds or fails ?

**Comment by BalRoger** [comment]
@jkronegg , you wrote:
> [@BalRoger](https://github.com/BalRoger) I followed the [tutorial steps](https://cucumber.io/docs/guides/10-minute-tutorial/) ...

Just as a sanity check, I also tried it on my home system. The tutorial up to `mvn test` works perfectly.

I suspect a firewall/proxy issue at work. It would not be the first time I've encountered weird maven behavior for that reason.

@mpkorstanje , you wrote:
> > After several false starts (need to specify versions on a lot of dependencies not versioned by archetype, etc.),
> 
> I think this is where things go wrong. The archetype includes all versions needed. You shouldn't add more versions and the versions you've added at a glance don't appear to be compatible.

I was getting even more severe maven errors before I specified dependency versions. 

----------------

In any case, this is clearly a network-local problem within my company firewall. I will seek out the collected wisdom within my company to move forward.

I apologize for bothering you with this, and thank you both for your prompt responses.
