### ISSUE TITLE
Root cause is not included when using DataTable.asList and friends

### ISSUE THREAD

**Issue by mpkorstanje** [cucumber/cucumber-jvm#2948]
### 👓 What did you see?

While using 

```java
    @DataTableType
    public Ingredient mySystemEntry(Map<String, String> entry) {
        throw new IllegalArgumentException("This message is never shown during test execution");
    }
```

And instead of 

```java
    @When("I mix the following ingredients")
    public void i_wait_hour(List<Ingredient> ingredients) {
        // use ingredients here
    }
```

Using:

```java
	@When("I mix the following ingredients")
	public void i_wait_hour(DataTable dataTable) {
	    List<Ingredient> ingredients = dataTable.asList(Ingredient.class);
	}
```	

Then the stack trace has as a root cause  `CucumberInvocationTargetException` which doesn't show the root cause of the problem.

```
      io.cucumber.datatable.CucumberDataTableException: 'java.util.List<io.cucumber.skeleton.StepDefinitions$Ingredient>' could not transform
| NAME  | QUANTITY | UNITS |
| Flour | 1        | KG    |
| Water | 0.65     | L     |
| Salt  | 0.08     | KG    |

	at io.cucumber.datatable.DataTableType.transform(DataTableType.java:158)
	at io.cucumber.datatable.DataTableTypeRegistryTableConverter.toListOrProblems(DataTableTypeRegistryTableConverter.java:158)
	at io.cucumber.datatable.DataTableTypeRegistryTableConverter.toList(DataTableTypeRegistryTableConverter.java:139)
	at io.cucumber.datatable.DataTable.asList(DataTable.java:199)
	at io.cucumber.skeleton.StepDefinitions.i_wait_hour(StepDefinitions.java:40)
	at ✽.I mix the following ingredients(classpath:io/cucumber/skeleton/belly.feature:6)
Caused by: io.cucumber.core.backend.CucumberInvocationTargetException
	at io.cucumber.java.Invoker.doInvoke(Invoker.java:73)
	at io.cucumber.java.Invoker.invoke(Invoker.java:24)
	
```	

### ✅ What did you expect to see?

Some form of abbreviated stack trace.
```
Scenario: a few cukes                  # io/cucumber/skeleton/belly.feature:3
  Given I have 42 cukes in my belly    # io.cucumber.skeleton.StepDefinitions.I_have_cukes_in_my_belly(int)
  When I mix the following ingredients # io.cucumber.skeleton.StepDefinitions.i_wait_hour(java.util.List<io.cucumber.skeleton.StepDefinitions$Ingredient>)
    | NAME  | QUANTITY | UNITS |
    | Flour | 1        | KG    |
    | Water | 0.65     | L     |
    | Salt  | 0.08     | KG    |
      java.lang.IllegalArgumentException: This message is never shown during test execution
    at io.cucumber.skeleton.StepDefinitions.mySystemEntry(StepDefinitions.java:29)
    at ✽.I mix the following ingredients(classpath:io/cucumber/skeleton/belly.feature:6)
 ```

### 📚 Any additional context?

* https://github.com/jean-michel-gonet/cucumber-java-skeleton
* https://stackoverflow.com/questions/79223480

**Comment by mpkorstanje** [comment]
This can probably be fixed by invoking `removeFrameworkFramesAndAppendStepLocation` recursively.

**Comment by jean-michel-gonet** [comment]
Thanks @mpkorstanje for reporting this bug :)
