### ISSUE TITLE
runtime exception when running a cucumber tests with annotation containing multiple tags

### ISSUE THREAD

**Issue by kphani** [cucumber/cucumber-jvm#383]
@when Trying to run my cucumber test with multiple tags in @cucumber.options annotation, like..

```
                   @RunWith(Cucumber.class)
                   @Cucumber.Options(tags = {"@reg","@temp"})
```

@then I am getting the below exception. But test running fine when run with any single tag like-> tags = {"@reg"}

---

cucumber.runtime.CucumberException: None of the features at [classpath:] matched the filters: [@reg, @temp]
    at cucumber.runtime.model.CucumberFeature.load(CucumberFeature.java:45)
    at cucumber.runtime.RuntimeOptions.cucumberFeatures(RuntimeOptions.java:98)
    at cucumber.junit.Cucumber.<init>(Cucumber.java:61)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
    at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:31)
    at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:24)
    at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:57)
    at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:29)
    at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:57)
    at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:24)
    at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:43)
    at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:195)
    at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:63)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
##     at com.intellij.rt.execution.application.AppMain.main(AppMain.java:120)

Thanks,
Phani Kaliginadi

**Comment by RishabhKumar-qait** [comment]
Thanks aslakhellesoy

**Comment by Jahidul2543** [comment]
Thank you so much  aslakhellesoy,
I had same issue, by this it resolved.

**Comment by srinu-kodi** [comment]
Hi aslakhellesoy,

I am also facing a similar issue as mentioned above. Here are my cucumber profile and my feature file.
When I am running, getting the nullPointerException.

@CucumberOptions(features = {"src/test/java/features"},
        glue = "stepDefs",
        tags = {"@web,@android", "~@ignore"},
        format = {"pretty", "html:target/cucumber"})

Feature:
@web @android @ios
  Scenario: Wordpress Signup scenario
    Given User chooses "Signup" option

Could you help me with this.

**Comment by aslakhellesoy** [comment]
This ticket was closed 5 years ago. Please open a new ticket. Include as much info as you can, at the very least what version you’re using.
