### ISSUE TITLE
first @notused Scenario in feature caused exception

### ISSUE THREAD

**Issue by k4124k** [cucumber/cucumber-jvm#447]
Caught: java.lang.ArrayIndexOutOfBoundsException: -1
java.lang.ArrayIndexOutOfBoundsException: -1
    at gherkin.formatter.JSONFormatter.getFeatureElement(JSONFormatter.java:147)
    at gherkin.formatter.JSONFormatter.addHook(JSONFormatter.java:104)
    at gherkin.formatter.JSONFormatter.before(JSONFormatter.java:95)
    at cucumber.runtime.Utils$1.call(Utils.java:44)
    at cucumber.runtime.Timeout.timeout(Timeout.java:12)
    at cucumber.runtime.Utils.invoke(Utils.java:40)
    at cucumber.runtime.RuntimeOptions$2.invoke(RuntimeOptions.java:138)
    at $Proxy5.before(Unknown Source)
    at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:207)
    at cucumber.runtime.Runtime.runHooks(Runtime.java:187)
    at cucumber.runtime.Runtime.runBeforeHooks(Runtime.java:178)
    at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:32)
    at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:117)
    at cucumber.runtime.Runtime.run(Runtime.java:108)
    at cucumber.runtime.Runtime.run(Runtime.java:96)
    at cucumber.runtime.Runtime$run.call(Unknown Source)

ps:i am using cucumber-jvm 1.1.2-snapshot

change tag from important  to notused  in examples\groovy-calculator\src\test\resources\divesion.feature 
after run featuren by cmd , then the exception will appear

**Comment by mpkorstanje** [comment]
It appears that this has been fixed with the resolution of #476. I can't quite confirm this as there is no proper reproducer but the stack trace is otherwise identical.
