### ISSUE TITLE
StringIndexOutOfBoundsException with missing step-definitions.

### ISSUE THREAD

**Issue by mfellner** [cucumber/cucumber-jvm#575]
When a step-definition is not implemented, a **StringIndexOutOfBoundsException** is thrown.
```java
[INFO] emulator-5554_Nexus4_unknown_sdk :   Running instrumentation tests in cucumber.example.android.cukeulator.test
[INFO] emulator-5554_Nexus4_unknown_sdk :     Run started: cucumber.example.android.cukeulator.test, 25 tests:
[INFO] emulator-5554_Nexus4_unknown_sdk :       Start [1/25]: Feature Calculate a result#Scenario Outline Enter a digit, an operator and another digit
[INFO] emulator-5554_Nexus4_unknown_sdk :       End [1/25]: Feature Calculate a result#Scenario Outline Enter a digit, an operator and another digit
[INFO] emulator-5554_Nexus4_unknown_sdk :       Start [2/25]: Feature Calculate a result#Scenario Outline Enter a digit, an operator and another digit
[INFO] emulator-5554_Nexus4_unknown_sdk :       ERROR:Feature Calculate a result#Scenario Outline Enter a digit, an operator and another digit
[INFO] emulator-5554_Nexus4_unknown_sdk :       Missing step-definition

@Given("^I have a CalculatorActivity$")
public void I_have_a_CalculatorActivity() throws Throwable {
// Express the Regexp above with the code you wish you had
throw new PendingException();
}

for step 'I should see 17.0 on the display'
Exception in thread "Thread-1" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1958)
	at com.jayway.maven.plugins.android.AbstractInstrumentationMojo$AndroidTestRunListener.parseForException(AbstractInstrumentationMojo.java:1011)
	at com.jayway.maven.plugins.android.AbstractInstrumentationMojo$AndroidTestRunListener.testFailed(AbstractInstrumentationMojo.java:875)
	at com.android.ddmlib.testrunner.InstrumentationResultParser.reportResult(InstrumentationResultParser.java:467)
	at com.android.ddmlib.testrunner.InstrumentationResultParser.parseStatusCode(InstrumentationResultParser.java:411)
	at com.android.ddmlib.testrunner.InstrumentationResultParser.parse(InstrumentationResultParser.java:272)
	at com.android.ddmlib.testrunner.InstrumentationResultParser.processNewLines(InstrumentationResultParser.java:243)
	at com.android.ddmlib.MultiLineReceiver.addOutput(MultiLineReceiver.java:99)
	at com.android.ddmlib.AdbHelper.executeRemoteCommand(AdbHelper.java:419)
	at com.android.ddmlib.Device.executeShellCommand(Device.java:444)
	at com.android.ddmlib.testrunner.RemoteAndroidTestRunner.run(RemoteAndroidTestRunner.java:211)
	at com.android.ddmlib.testrunner.RemoteAndroidTestRunner.run(RemoteAndroidTestRunner.java:196)
	at com.jayway.maven.plugins.android.AbstractInstrumentationMojo$1.doWithDevice(AbstractInstrumentationMojo.java:404)
	at com.jayway.maven.plugins.android.ScreenshotServiceWrapper.doWithDevice(ScreenshotServiceWrapper.java:56)
	at com.jayway.maven.plugins.android.AbstractAndroidMojo$2.runDo(AbstractAndroidMojo.java:764)
	at com.jayway.maven.plugins.android.AbstractAndroidMojo$DoThread.run(AbstractAndroidMojo.java:1275)
```
**Update:** the issue only occurs when running the test with Maven, not with Ant.

**Comment by SierraGolf** [comment]
this was fixed and merged many moons ago. in case a step is undefined there will be a cucumber.runtime.android.MissingStepDefinitionError thrown which holds the snippet as message.
