### ISSUE TITLE
gherkin.lexer.LexingError with a feature written in italian

### ISSUE THREAD

**Issue by eemaric** [cucumber/cucumber-jvm#784]
I have got an error with the italian localization of cucumber-jvm.
My feature file starts with  # language: it 
The Feature keyword in my feature file is "Funzionalità:" as required by the gherkin documentation for the italian localization.

cucumber.runtime.CucumberException: Error parsing feature file src/main/resources/001_maschera_accesso_1.feature
        at cucumber.runtime.FeatureBuilder.parse(FeatureBuilder.java:123)
        at cucumber.runtime.model.CucumberFeature.load(CucumberFeature.java:52)
        at cucumber.runtime.model.CucumberFeature.load(CucumberFeature.java:33)
        at cucumber.runtime.RuntimeOptions.cucumberFeatures(RuntimeOptions.java:143)
        at cucumber.api.junit.Cucumber.<init>(Cucumber.java:67)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Unknown Source)
        at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:29)
        at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:21)
        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
        at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
        at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:26)
        at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.<init>(JUnit4TestReference.java:33)
        at org.eclipse.jdt.internal.junit4.runner.JUnit4TestClassReference.<init>(JUnit4TestClassReference.java:25)
        at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:48)
        at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:38)
        at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:444)
        at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
        at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
        at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: gherkin.lexer.LexingError: Lexing error on line 2: 'Funzionalit�: Valorizzazione combo dei comuni

Scenario: Selezione corretta comune
        Dato l'accesso alla home
        And ho la combo codice codice asl valorizzata
        When Seleziono codice asl GENOVESE
        Then la combo comuni contiene
                | comune |
                | GENOVA |
                | ARENZANO |

Scenario: Combo comuni non valorizzata corretamente
        Dato l'accesso alla home
        And ho la combo codice codice asl valorizzata
        When Seleziono codice asl SAVONESE
        Then la combo comuni non contiene
                | comune |
                | GENOVA |
                | ARENZANO |
%_FEATURE_END_%'. See http://wiki.github.com/cucumber/gherkin/lexingerror for more information.
        at gherkin.lexer.It.scan(It.java:831)
        at gherkin.lexer.I18nLexer.scan(I18nLexer.java:36)
        at gherkin.parser.Parser.parse(Parser.java:62)

**Comment by pbmzbr** [comment]
Try to set your project with UTF-8 encoding.

**Comment by lunivore** [comment]
Hi @eemaric, did setting the encoding of this to UTF-8 solve the problem? If not, please let us know that it's still important to you. If we don't hear back, we'll close this ticket in a week. Thanks!

**Comment by brasmusson** [comment]
The `gherkin.lexer.LexingError` is an error from Gherkin v2, now when Cucumber-JVM has been upgraded to use Gherkin v4 (currently available as 2.0.0-SNAPSHOT), this error cannot occur.
