### ISSUE TITLE
Cannot find class in classpath: cucumber.api.testng.CucumberFeatureWrapper

### ISSUE THREAD

**Issue by Utkarsh6793** [cucumber/cucumber-jvm#870]
org.testng.TestNGException: 
Cannot find class in classpath: cucumber.api.testng.CucumberFeatureWrapper
	at org.testng.xml.XmlClass.loadClass(XmlClass.java:81)
	at org.testng.xml.XmlClass.init(XmlClass.java:73)
	at org.testng.xml.XmlClass.<init>(XmlClass.java:59)
	at org.testng.xml.TestNGContentHandler.startElement(TestNGContentHandler.java:548)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.AbstractXMLDocumentParser.emptyElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.dtd.XMLDTDValidator.emptyElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
	at javax.xml.parsers.SAXParser.parse(Unknown Source)
	at org.testng.xml.XMLParser.parse(XMLParser.java:39)
	at org.testng.xml.SuiteXmlParser.parse(SuiteXmlParser.java:17)
	at org.testng.xml.SuiteXmlParser.parse(SuiteXmlParser.java:10)
	at org.testng.xml.Parser.parse(Parser.java:168)
	at org.testng.TestNG.initializeSuitesAndJarFile(TestNG.java:310)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:88)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Picked up JAVA_TOOL_OPTIONS: -agentlib:jvmhook
Picked up _JAVA_OPTIONS: -Xrunjvmhook -Xbootclasspath/a:"D:\QTP_11.5\bin\java_shared\classes";"D:\QTP_11.5\\bin\java_shared\classes\jasmine.jar"

Java 1.7
Cucumber version:- 1.2.2
Windows 2007 32 bit:- 
Eclipse Juno
Can anyone please help us to resolve this error?

**Comment by aslakhellesoy** [comment]
I closed this because the author didn't provide any information beyond a stack trace. It doesn't seem related to Cucumber (stack trace is not from Cucumber). Using [https://cucumber.io/support] is more appropriate here.
