### ISSUE TITLE
feature execution using gherkin in pt-br with "Então" return error

### ISSUE THREAD

**Issue by williamjablonski** [cucumber/cucumber-jvm#887]
cucumber-jvm: version 1.1.5
system: windows

When execute feature in pt-br using "Então" for return cucumber steps the cucumber-jvm returned this exception:

Exception in thread "main" cucumber.runtime.CucumberException: Error parsing feature file C:/Users/william.jablonski/workspace2/androidApp/src/test/java/feature/ValidarTriangulo.feature
	at cucumber.runtime.FeatureBuilder.parse(FeatureBuilder.java:123)
	at cucumber.runtime.model.CucumberFeature.load(CucumberFeature.java:52)
	at cucumber.runtime.model.CucumberFeature.load(CucumberFeature.java:33)
	at cucumber.runtime.RuntimeOptions.cucumberFeatures(RuntimeOptions.java:143)
	at cucumber.runtime.Runtime.run(Runtime.java:107)
	at cucumber.api.cli.Main.run(Main.java:26)
	at cucumber.api.cli.Main.main(Main.java:16)
Caused by: gherkin.lexer.LexingError: Lexing error on line 14: 'Ent?o o sistema apresenta a mensagem "<mensagem_equilatero>".

    Exemplos: 
      | aparelho                                | plataforma | versao | aplicacao        | pasta       | valor_Lado1 | valor_Lado2 | valor_Lado3 | mensagem_equilatero      |
      | Google Nexus 4 - 5.1.0 -API 22-768x1280 | Android    | 4.3    | TrianguloApp.apk | C:/Android/ | 3           | 3           | 3           | O tri?ngulo ? Equil?tero |
      | Google Nexus 4 - 5.1.0 -API 22-768x1280 | Android    | 4.3    | TrianguloApp.apk | C:/Android/ | 3           | 3           | 3           | O tri?ngulo ? Equil?tero |

%_FEATURE_END_%'. See http://wiki.github.com/cucumber/gherkin/lexingerror for more information.
	at gherkin.lexer.Pt.scan(Pt.java:1058)
	at gherkin.lexer.I18nLexer.scan(I18nLexer.java:36)
	at gherkin.parser.Parser.parse(Parser.java:62)
	at cucumber.runtime.FeatureBuilder.parse(FeatureBuilder.java:121)
	... 6 more
Picked up _JAVA_OPTIONS: -Duser.home=C:/Users/william.jablonski/

if i change "Então" to "Entao" don't show this error.

**Comment by aslakhellesoy** [comment]
You need to save your `.feature` file with UTF-8 encoding. The `Ent?o` in the error message tells me you're using a different encoding.
