### ISSUE TITLE
UTF-8 is hard-coded into the cucumber-jvm code

### ISSUE THREAD

**Issue by palerique** [cucumber/cucumber-jvm#891]
Dear,

I went through a problem using the Cucumber in Portuguese and thought it was a problem in another tool, the Serenity!

I had opened an issue there to correct the problems but just identifying the problem is actually in the cucumber-jvm code!

The original Issue is here: https://github.com/serenity-bdd/serenity-cucumber/issues/18

The code that generate the exception is here: https://github.com/palerique/cucumber-serenity-webtests

Some codes to guide:

.feature file:
```gherkin
# language: pt
@component:ui
@version:Sprint-7
Funcionalidade: Buscar por palavra chave
  Para os compradores encontrarem o que estão procurando de forma mais eficiente
  Como um vendedor
  Desejo que os compradores possam buscar por artigos utilizando palavras chave

  Cenário: Buscar artigos por palavra chave
    Dado que quero comprar um cachecol de lã
    Quando eu buscar por 'wool'
    Então devo ver apenas artigos relacionados com 'wool'

  Cenário: Buscar por nome da loja
    Dado que desejo visualizar artigos de uma loja em particular
    Quando eu buscar uma loja por 'docksmith'
    Então devo encontrar 1 loja chamada 'docksmith'

  Delineação do Cenário: Buscar por muitos artigos utilizando palavra chave
    Dado que quero comprar um <article>
    Quando eu buscar por '<article>'
    Então devo ver apenas artigos relacionados com '<keyword>'
    Exemplos:
      | article      | keyword |
      | wool scarf   | wool    |
      | cotton shirt | cotton  |
```

steps file:
```java
package net.thucydides.showcase.cucumber.steps;

import cucumber.api.java.pt.Dado;
import cucumber.api.java.pt.Entao;
import cucumber.api.java.pt.Quando;
import net.thucydides.core.annotations.Steps;
import net.thucydides.core.util.Inflector;
import net.thucydides.showcase.cucumber.steps.serenity.BuyerSteps;

import java.text.ParseException;

public class SearchScenarioSteps {
	@Steps
	BuyerSteps buyer;

	@Dado("que (?:quero|possa querer) comprar um (.*)")
	public void buyerWantsToBuy(String article) {
		buyer.opens_home_page();
	}

	@Quando("eu buscar por '(.*)'")
	public void searchByKeyword(String keyword) {
		buyer.searches_by_keyword(keyword);
	}

	@Entao("devo ver apenas artigos relacionados com '(.*)'")
	public void resultsForACategoryAndKeywordInARegion(String keyword) throws ParseException {
		buyer.should_see_results_summary_containing(keyword);
	}

	@Dado("que desejo visualizar artigos de uma loja em particular")
	public void givenIWantToSeeArticlesFromAParticularShop() {
		buyer.opens_home_page();
	}

	@Quando("eu buscar uma loja por '(.*)'")
	public void whenISearchByShopFor(String shopName) {
		buyer.should_see_nonexistant_field();
		buyer.searches_for_shop_called(shopName);
	}

	@Entao("devo encontrar (\\d+) (?:loja|lojas) chamada '(.*)'")
	public void thenIShouldFindShopsCall(int count, String shopName) {
		String expectedMessage = String.format("%d %s encontrada para %s", count, pluralized(count, "loja"), shopName);
		buyer.should_see_shop_search_result_summary_of(expectedMessage);
	}

	private String pluralized(int count, String word) {
		return Inflector.getInstance().pluralize(word, count);

	}
}
```

serenity.properties:
```properties
#webdriver.driver=chrome
webdriver.driver=firefox
serenity.project.name = Demo Project using Serenity and Cucumber

serenity.use.unique.browser = false

serenity.browser,height = 1200
serenity.browser,width = 1200
serenity.dry.run=false

# How long does Serenity wait for elements that are not present on the screen to load
webdriver.timeouts.implicitlywait = 5000
serenity.take.screenshots=AFTER_EACH_STEP

# Like code
feature.file.language=pt
# Like docs
feature.file,language=pt
```

The stacktrace:
```stacktrace
599 [main] ERROR net.thucydides.core.model.TestOutcome - Tag provider net.thucydides.core.requirements.FileSystemRequirementsTagProvider@7203c7ff failure
gherkin.parser.ParseError: Parse error at search_by_keyword.feature:22. Found examples when expecting one of: background, comment, scenario, scenario_outline, tag. (Current getState: feature).
        at gherkin.parser.Parser$Machine.event(Parser.java:207)
        at gherkin.parser.Parser.event(Parser.java:159)
        at gherkin.parser.Parser.examples(Parser.java:124)
        at gherkin.lexer.Pt.scan(Pt.java:966)
        at gherkin.lexer.I18nLexer.scan(I18nLexer.java:36)
        at gherkin.parser.Parser.parse(Parser.java:62)
        at net.thucydides.core.requirements.model.cucumber.CucumberParser.loadFeatureNarrative(CucumberParser.java:45)
        at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.loadFromFeatureFile(FileSystemRequirementsTagProvider.java:515)
        at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.readRequirementsFromStoryOrFeatureFile(FileSystemRequirementsTagProvider.java:496)
        at net.thucydides.core.requirements.FileSystemRequirementsTagProvider$2.convert(FileSystemRequirementsTagProvider.java:475)
        at net.thucydides.core.requirements.FileSystemRequirementsTagProvider$2.convert(FileSystemRequirementsTagProvider.java:472)
        at ch.lambdaj.function.convert.ConverterIterator.next(ConverterIterator.java:37)
        at ch.lambdaj.Lambda.convert(Lambda.java:986)
        at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.loadStoriesFrom(FileSystemRequirementsTagProvider.java:459)
        at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.getRequirements(FileSystemRequirementsTagProvider.java:138)
        at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.readChildrenFrom(FileSystemRequirementsTagProvider.java:579)
        at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.requirementFromDirectoryName(FileSystemRequirementsTagProvider.java:538)
        at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.readRequirementFrom(FileSystemRequirementsTagProvider.java:488)
        at net.thucydides.core.requirements.FileSystemRequirementsTagProvider$1.convert(FileSystemRequirementsTagProvider.java:466)
        at net.thucydides.core.requirements.FileSystemRequirementsTagProvider$1.convert(FileSystemRequirementsTagProvider.java:463)
        at ch.lambdaj.function.convert.ConverterIterator.next(ConverterIterator.java:37)
        at ch.lambdaj.Lambda.convert(Lambda.java:986)
        at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.loadCapabilitiesFrom(FileSystemRequirementsTagProvider.java:454)
        at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.getRequirements(FileSystemRequirementsTagProvider.java:137)
        at net.thucydides.core.requirements.FileSystemRequirementsTagProvider.getTagsFor(FileSystemRequirementsTagProvider.java:263)
        at net.thucydides.core.model.TestOutcome.getTagsUsingTagProviders(TestOutcome.java:1271)
        at net.thucydides.core.model.TestOutcome.getTags(TestOutcome.java:1261)
        at net.thucydides.core.model.TestOutcome.addTags(TestOutcome.java:1286)
        at net.thucydides.core.steps.StepEventBus.addTagsToCurrentTest(StepEventBus.java:475)
        at net.serenitybdd.cucumber.SerenityReporter.startScenario(SerenityReporter.java:395)
        at net.serenitybdd.cucumber.SerenityReporter.startOfScenarioLifeCycle(SerenityReporter.java:387)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at cucumber.runtime.Utils$1.call(Utils.java:37)
        at cucumber.runtime.Timeout.timeout(Timeout.java:13)
        at cucumber.runtime.Utils.invoke(Utils.java:31)
        at cucumber.runtime.RuntimeOptions$1.invoke(RuntimeOptions.java:290)
        at com.sun.proxy.$Proxy19.startOfScenarioLifeCycle(Unknown Source)
        at cucumber.runtime.junit.JUnitReporter.startOfScenarioLifeCycle(JUnitReporter.java:219)
        at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:39)
        at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:91)
        at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
        at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
        at cucumber.api.junit.Cucumber.runChild(Cucumber.java:93)
        at cucumber.api.junit.Cucumber.runChild(Cucumber.java:37)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at cucumber.api.junit.Cucumber.run(Cucumber.java:98)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:283)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:173
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:128)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBoot
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

pom.xml:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>net.serenity-bdd.demos</groupId>
    <artifactId>cucumber-webtests</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>Sample Serenity Cucumber project</name>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <serenity.version>1.0.59</serenity.version>
        <serenity.maven.version>1.0.58</serenity.maven.version>
        <serenity.cucumber.version>1.0.18</serenity.cucumber.version>
    </properties>

    <!-- Define the Bintray repos for convenience -->
    <repositories>
        <repository>
            <id>serenity</id>
            <name>bintray</name>
            <url>http://dl.bintray.com/serenity/maven</url>
        </repository>
    </repositories>
    <pluginRepositories>
        <pluginRepository>
            <id>serenity</id>
            <name>bintray-plugins</name>
            <url>http://dl.bintray.com/serenity/maven</url>
        </pluginRepository>
    </pluginRepositories>

    <dependencies>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-core</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-rest-assured</artifactId>
            <version>${serenity.version}</version>
        </dependency>
        <dependency>
            <groupId>net.serenity-bdd</groupId>
            <artifactId>serenity-cucumber</artifactId>
            <version>${serenity.cucumber.version}</version>
        </dependency>
        <dependency>
            <groupId>org.slf4j</groupId>
            <artifactId>slf4j-simple</artifactId>
            <version>1.6.1</version>
        </dependency>
        <dependency>
            <groupId>org.codehaus.groovy</groupId>
            <artifactId>groovy-all</artifactId>
            <version>1.8.6</version>
        </dependency>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.11</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.googlecode.lambdaj</groupId>
            <artifactId>lambdaj</artifactId>
            <version>2.3.3</version>
        </dependency>
        <dependency>
            <groupId>org.assertj</groupId>
            <artifactId>assertj-core</artifactId>
            <version>1.7.0</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <plugins>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <version>1.4</version>
                <executions>
                    <execution>
                        <id>enforce</id>
                        <configuration>
                            <rules>
                                <requireUpperBoundDeps/>
                            </rules>
                        </configuration>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.18</version>
                <configuration>
                    <skip>true</skip>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-failsafe-plugin</artifactId>
                <version>2.18</version>
                <configuration>
                    <includes>
                        <include>**/cucumber/*.java</include>
                    </includes>
                    <reuseForks>true</reuseForks>
                    <!--<forkCount>2</forkCount>-->
                    <argLine>-Xmx1024m -XX:MaxPermSize=256m</argLine>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>integration-test</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.2</version>
                <configuration>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
            <plugin>
                <groupId>net.serenity-bdd.maven.plugins</groupId>
                <artifactId>serenity-maven-plugin</artifactId>
                <version>${serenity.maven.version}</version>
                <dependencies>
                    <dependency>
                        <groupId>net.serenity-bdd</groupId>
                        <artifactId>serenity-core</artifactId>
                        <version>${serenity.version}</version>
                    </dependency>
                </dependencies>
                <executions>
                    <execution>
                        <id>serenity-reports</id>
                        <phase>post-integration-test</phase>
                        <goals>
                            <goal>aggregate</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
```

**Comment by aslakhellesoy** [comment]
Try this:

```gherkin
# language: pt
# encoding: iso-8859-1
```

And save your file as iso-8859-1.

/cc @wakaleo

**Comment by aslakhellesoy** [comment]
I'm closing this. Let us know if this doesn't work for you.

**Comment by palerique** [comment]
It worked!

Thank you very much!

**Comment by fabianofda** [comment]
invalid byte sequence in UTF-8 (ArgumentError)?

**Comment by mlvandijk** [comment]
@fabianofda You are commenting on a closed issue. 
If you are currently having an issue and need help, please try one of the [support](https://cucumber.io/support) options, or if you have found a bug, please  open a new issue and provide additional information so we can help you.
