### ISSUE TITLE
java.lang.IndexOutOfBoundsException: Index: 0, Size: 0 Error 

### ISSUE THREAD

**Issue by beemi** [cucumber/cucumber-jvm#908]
Cucumber-jvm :1.2.4 (also tried with different version)
Java : 1.8
Intellj IDA :14.1.4
..............................................
import cucumber.api.CucumberOptions;
import cucumber.api.junit.Cucumber;
import org.junit.runner.RunWith;

@CucumberOptions(
        plugin = {"pretty",
                 "html:target/cucumber/myreport-html-report",
                "json:target/cucumber/myreport-json-report.json"
        },
        tags = "@Login",
        features = "src/test/resources/Features",
        glue = "com.example.stepdefinitions")

@RunWith(Cucumber.class)
public class Test {
}
.....................................................Error..............................................................

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at cucumber.runtime.model.CucumberScenarioOutline.replaceTokens(CucumberScenarioOutline.java:117)
	at cucumber.runtime.model.CucumberScenarioOutline.createExampleScenario(CucumberScenarioOutline.java:57)
	at cucumber.runtime.model.CucumberExamples.createExampleScenarios(CucumberExamples.java:28)
	at cucumber.runtime.junit.ExamplesRunner.buildRunners(ExamplesRunner.java:28)
	at cucumber.runtime.junit.ExamplesRunner.<init>(ExamplesRunner.java:21)
	at cucumber.runtime.junit.ScenarioOutlineRunner.buildRunners(ScenarioOutlineRunner.java:29)
	at cucumber.runtime.junit.ScenarioOutlineRunner.<init>(ScenarioOutlineRunner.java:21)
	at cucumber.runtime.junit.FeatureRunner.buildFeatureElementRunners(FeatureRunner.java:81)
	at cucumber.runtime.junit.FeatureRunner.<init>(FeatureRunner.java:31)
	at cucumber.api.junit.Cucumber.addChildren(Cucumber.java:106)
	at cucumber.api.junit.Cucumber.<init>(Cucumber.java:62)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:41)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:212)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

**Comment by brasmusson** [comment]
Looks like your Examples table is malformed. Make sure that all rows have values for all columns. I can provoke the same backtrace when changing [an example table in the java-calculator example](https://github.com/cucumber/cucumber-jvm/blob/master/examples/java-calculator/src/test/resources/cucumber/examples/java/calculator/basic_arithmetic.feature#L27-L30) to 
```
  Examples: Single digits
    | a | b | c  |
    | 1 | 2 | 8  |
    |
```

**Comment by beemi** [comment]
Thank u , fixed
